============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py first driver inits
1610711720519,275,selenium_login:open_login_page,Success,True
1610711721269,671,selenium_login:login_and_view_dashboard,Success,True
1610711721269,1025,selenium_login,Success,True
.test_0_selenium_a_login,Total:1 Passed:1 Failed:0
1610711721790,507,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:2 Passed:2 Failed:0
1610711722528,736,selenium_create_page:open_create_page_editor,Success,True
1610711723757,604,selenium_create_page:save_created_page,Success,True
1610711723757,1966,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:3 Passed:3 Failed:0
1610711724899,1140,selenium_edit_page:open_create_page_editor,Success,True
1610711725676,757,selenium_edit_page:save_edited_page,Success,True
1610711725676,1917,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:4 Passed:4 Failed:0
1610711726662,681,selenium_create_comment:write_comment,Success,True
1610711727278,615,selenium_create_comment:save_comment,Success,True
1610711727278,1601,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:5 Passed:5 Failed:0
1610711727815,535,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:6 Passed:6 Failed:0
1610711728855,1038,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:7 Passed:7 Failed:0
1610711729410,553,selenium_app_custom_action:view_page,Success,True
1610711729410,553,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:8 Passed:8 Failed:0
1610711729561,149,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:9 Passed:9 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.46s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711729696,87,selenium_login:open_login_page,Success,True
1610711730428,654,selenium_login:login_and_view_dashboard,Success,True
1610711730428,819,selenium_login,Success,True
.test_0_selenium_a_login,Total:10 Passed:10 Failed:0
1610711731231,775,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:11 Passed:11 Failed:0
1610711731919,687,selenium_create_page:open_create_page_editor,Success,True
1610711733167,590,selenium_create_page:save_created_page,Success,True
1610711733167,1935,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:12 Passed:12 Failed:0
1610711734130,961,selenium_edit_page:open_create_page_editor,Success,True
1610711735056,906,selenium_edit_page:save_edited_page,Success,True
1610711735056,1887,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:13 Passed:13 Failed:0
1610711736487,736,selenium_create_comment:write_comment,Success,True
1610711737133,645,selenium_create_comment:save_comment,Success,True
1610711737133,2075,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:14 Passed:14 Failed:0
1610711737607,473,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:15 Passed:15 Failed:0
1610711738632,1022,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:16 Passed:16 Failed:0
1610711739063,430,selenium_app_custom_action:view_page,Success,True
1610711739063,430,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:17 Passed:17 Failed:0
1610711739148,83,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:18 Passed:18 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.55s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711739298,99,selenium_login:open_login_page,Success,True
1610711740025,649,selenium_login:login_and_view_dashboard,Success,True
1610711740025,826,selenium_login,Success,True
.test_0_selenium_a_login,Total:19 Passed:19 Failed:0
1610711740537,485,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:20 Passed:20 Failed:0
1610711741236,697,selenium_create_page:open_create_page_editor,Success,True
1610711742455,593,selenium_create_page:save_created_page,Success,True
1610711742455,1916,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:21 Passed:21 Failed:0
1610711744088,1631,selenium_edit_page:open_create_page_editor,Success,True
1610711744893,784,selenium_edit_page:save_edited_page,Success,True
1610711744893,2436,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:22 Passed:22 Failed:0
1610711745721,360,selenium_create_comment:write_comment,Success,True
1610711745884,163,selenium_create_comment:save_comment,Success,True
1610711745884,989,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:23 Passed:23 Failed:0
1610711746401,516,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:24 Passed:24 Failed:0
1610711747408,1005,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:25 Passed:25 Failed:0
1610711747847,437,selenium_app_custom_action:view_page,Success,True
1610711747847,437,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:26 Passed:26 Failed:0
1610711747955,106,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:27 Passed:27 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.77s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711748098,87,selenium_login:open_login_page,Success,True
1610711748786,609,selenium_login:login_and_view_dashboard,Success,True
1610711748786,775,selenium_login,Success,True
.test_0_selenium_a_login,Total:28 Passed:28 Failed:0
1610711749172,359,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:29 Passed:29 Failed:0
1610711749819,646,selenium_create_page:open_create_page_editor,Success,True
1610711751060,593,selenium_create_page:save_created_page,Success,True
1610711751060,1887,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:30 Passed:30 Failed:0
1610711753095,2033,selenium_edit_page:open_create_page_editor,Success,True
1610711753817,702,selenium_edit_page:save_edited_page,Success,True
1610711753817,2755,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:31 Passed:31 Failed:0
1610711754867,743,selenium_create_comment:write_comment,Success,True
1610711754995,127,selenium_create_comment:save_comment,Success,True
1610711754995,1177,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:32 Passed:32 Failed:0
1610711755483,486,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:33 Passed:33 Failed:0
1610711756518,1034,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:34 Passed:34 Failed:0
1610711756942,422,selenium_app_custom_action:view_page,Success,True
1610711756942,422,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:35 Passed:35 Failed:0
1610711757039,95,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:36 Passed:36 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.04s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711757184,97,selenium_login:open_login_page,Success,True
1610711757973,713,selenium_login:login_and_view_dashboard,Success,True
1610711757973,886,selenium_login,Success,True
.test_0_selenium_a_login,Total:37 Passed:37 Failed:0
1610711758464,475,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:38 Passed:38 Failed:0
1610711759136,671,selenium_create_page:open_create_page_editor,Success,True
1610711760358,599,selenium_create_page:save_created_page,Success,True
1610711760358,1893,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:39 Passed:39 Failed:0
1610711762959,2599,selenium_edit_page:open_create_page_editor,Success,True
1610711763752,774,selenium_edit_page:save_edited_page,Success,True
1610711763752,3392,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:40 Passed:40 Failed:0
1610711764596,282,selenium_create_comment:write_comment,Success,True
1610711764718,121,selenium_create_comment:save_comment,Success,True
1610711764718,964,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:41 Passed:41 Failed:0
1610711765244,525,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:42 Passed:42 Failed:0
1610711766290,1044,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:43 Passed:43 Failed:0
1610711766736,444,selenium_app_custom_action:view_page,Success,True
1610711766736,444,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:44 Passed:44 Failed:0
1610711766844,106,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:45 Passed:45 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.77s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711766990,97,selenium_login:open_login_page,Success,True
1610711767720,650,selenium_login:login_and_view_dashboard,Success,True
1610711767720,827,selenium_login,Success,True
.test_0_selenium_a_login,Total:46 Passed:46 Failed:0
1610711768081,344,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:47 Passed:47 Failed:0
1610711768804,721,selenium_create_page:open_create_page_editor,Success,True
1610711770052,605,selenium_create_page:save_created_page,Success,True
1610711770052,1969,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:48 Passed:48 Failed:0
1610711772094,2040,selenium_edit_page:open_create_page_editor,Success,True
1610711772791,663,selenium_edit_page:save_edited_page,Success,True
1610711772791,2737,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:49 Passed:49 Failed:0
1610711773854,736,selenium_create_comment:write_comment,Success,True
1610711773982,128,selenium_create_comment:save_comment,Success,True
1610711773982,1190,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:50 Passed:50 Failed:0
1610711774542,558,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:51 Passed:51 Failed:0
1610711775597,1054,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:52 Passed:52 Failed:0
1610711776020,421,selenium_app_custom_action:view_page,Success,True
1610711776020,421,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:53 Passed:53 Failed:0
1610711776134,113,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:54 Passed:54 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.25s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711776273,89,selenium_login:open_login_page,Success,True
1610711776979,625,selenium_login:login_and_view_dashboard,Success,True
1610711776979,795,selenium_login,Success,True
.test_0_selenium_a_login,Total:55 Passed:55 Failed:0
1610711777732,739,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:56 Passed:56 Failed:0
1610711778365,631,selenium_create_page:open_create_page_editor,Success,True
1610711779624,595,selenium_create_page:save_created_page,Success,True
1610711779624,1890,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:57 Passed:57 Failed:0
1610711781118,1492,selenium_edit_page:open_create_page_editor,Success,True
1610711782053,916,selenium_edit_page:save_edited_page,Success,True
1610711782053,2428,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:58 Passed:58 Failed:0
1610711783519,742,selenium_create_comment:write_comment,Success,True
1610711783647,128,selenium_create_comment:save_comment,Success,True
1610711783647,1593,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:59 Passed:59 Failed:0
1610711784230,581,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:60 Passed:60 Failed:0
1610711785263,1031,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:61 Passed:61 Failed:0
1610711785622,358,selenium_app_custom_action:view_page,Success,True
1610711785622,358,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:62 Passed:62 Failed:0
1610711785770,145,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:63 Passed:63 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.60s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711785910,86,selenium_login:open_login_page,Success,True
1610711786618,630,selenium_login:login_and_view_dashboard,Success,True
1610711786618,794,selenium_login,Success,True
.test_0_selenium_a_login,Total:64 Passed:64 Failed:0
1610711787007,377,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:65 Passed:65 Failed:0
1610711787593,584,selenium_create_page:open_create_page_editor,Success,True
1610711788854,604,selenium_create_page:save_created_page,Success,True
1610711788854,1844,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:66 Passed:66 Failed:0
1610711791363,2507,selenium_edit_page:open_create_page_editor,Success,True
1610711792073,690,selenium_edit_page:save_edited_page,Success,True
1610711792073,3217,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:67 Passed:67 Failed:0
1610711793015,623,selenium_create_comment:write_comment,Success,True
1610711793665,649,selenium_create_comment:save_comment,Success,True
1610711793665,1591,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:68 Passed:68 Failed:0
1610711794084,417,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:69 Passed:69 Failed:0
1610711795084,999,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:70 Passed:70 Failed:0
1610711795423,337,selenium_app_custom_action:view_page,Success,True
1610711795423,337,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:71 Passed:71 Failed:0
1610711795574,149,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:72 Passed:72 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.76s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711795725,97,selenium_login:open_login_page,Success,True
1610711796438,636,selenium_login:login_and_view_dashboard,Success,True
1610711796438,810,selenium_login,Success,True
.test_0_selenium_a_login,Total:73 Passed:73 Failed:0
1610711796867,404,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:74 Passed:74 Failed:0
1610711797525,656,selenium_create_page:open_create_page_editor,Success,True
1610711798741,592,selenium_create_page:save_created_page,Success,True
1610711798741,1872,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:75 Passed:75 Failed:0
1610711800270,1528,selenium_edit_page:open_create_page_editor,Success,True
1610711800989,698,selenium_edit_page:save_edited_page,Success,True
1610711800989,2246,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:76 Passed:76 Failed:0
1610711802028,737,selenium_create_comment:write_comment,Success,True
1610711802671,643,selenium_create_comment:save_comment,Success,True
1610711802671,1681,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:77 Passed:77 Failed:0
1610711803193,520,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:78 Passed:78 Failed:0
1610711804205,1010,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:79 Passed:79 Failed:0
1610711804634,427,selenium_app_custom_action:view_page,Success,True
1610711804634,428,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:80 Passed:80 Failed:0
1610711804757,121,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:81 Passed:81 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.14s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711804900,94,selenium_login:open_login_page,Success,True
1610711805618,634,selenium_login:login_and_view_dashboard,Success,True
1610711805618,812,selenium_login,Success,True
.test_0_selenium_a_login,Total:82 Passed:82 Failed:0
1610711806250,614,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:83 Passed:83 Failed:0
1610711806900,648,selenium_create_page:open_create_page_editor,Success,True
1610711808163,601,selenium_create_page:save_created_page,Success,True
1610711808163,1911,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:84 Passed:84 Failed:0
1610711810782,2617,selenium_edit_page:open_create_page_editor,Success,True
1610711811565,761,selenium_edit_page:save_edited_page,Success,True
1610711811565,3400,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:85 Passed:85 Failed:0
1610711812335,338,selenium_create_comment:write_comment,Success,True
1610711812983,648,selenium_create_comment:save_comment,Success,True
1610711812983,1416,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:86 Passed:86 Failed:0
1610711813403,418,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:87 Passed:87 Failed:0
1610711814433,1028,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:88 Passed:88 Failed:0
1610711814757,322,selenium_app_custom_action:view_page,Success,True
1610711814757,322,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:89 Passed:89 Failed:0
1610711814865,106,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:90 Passed:90 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.07s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711815012,98,selenium_login:open_login_page,Success,True
1610711815704,615,selenium_login:login_and_view_dashboard,Success,True
1610711815704,790,selenium_login,Success,True
.test_0_selenium_a_login,Total:91 Passed:91 Failed:0
1610711816165,438,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:92 Passed:92 Failed:0
1610711816831,664,selenium_create_page:open_create_page_editor,Success,True
1610711818035,588,selenium_create_page:save_created_page,Success,True
1610711818035,1868,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:93 Passed:93 Failed:0
1610711819563,1526,selenium_edit_page:open_create_page_editor,Success,True
1610711820341,759,selenium_edit_page:save_edited_page,Success,True
1610711820341,2305,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:94 Passed:94 Failed:0
1610711821471,722,selenium_create_comment:write_comment,Success,True
1610711822109,638,selenium_create_comment:save_comment,Success,True
1610711822109,1766,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:95 Passed:95 Failed:0
1610711822767,656,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:96 Passed:96 Failed:0
1610711823777,1009,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:97 Passed:97 Failed:0
1610711824135,356,selenium_app_custom_action:view_page,Success,True
1610711824135,356,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:98 Passed:98 Failed:0
1610711824293,156,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:99 Passed:99 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.39s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711824427,85,selenium_login:open_login_page,Success,True
1610711825102,598,selenium_login:login_and_view_dashboard,Success,True
1610711825103,760,selenium_login,Success,True
.test_0_selenium_a_login,Total:100 Passed:100 Failed:0
1610711825473,357,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:101 Passed:101 Failed:0
1610711826160,685,selenium_create_page:open_create_page_editor,Success,True
1610711827392,606,selenium_create_page:save_created_page,Success,True
1610711827392,1917,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:102 Passed:102 Failed:0
1610711828938,1545,selenium_edit_page:open_create_page_editor,Success,True
1610711829694,736,selenium_edit_page:save_edited_page,Success,True
1610711829694,2301,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:103 Passed:103 Failed:0
1610711830367,264,selenium_create_comment:write_comment,Success,True
1610711830974,606,selenium_create_comment:save_comment,Success,True
1610711830974,1278,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:104 Passed:104 Failed:0
1610711831414,439,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:105 Passed:105 Failed:0
1610711832439,1024,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:106 Passed:106 Failed:0
1610711832806,365,selenium_app_custom_action:view_page,Success,True
1610711832806,365,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:107 Passed:107 Failed:0
1610711832959,151,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:108 Passed:108 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.63s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711833110,89,selenium_login:open_login_page,Success,True
1610711833833,644,selenium_login:login_and_view_dashboard,Success,True
1610711833833,812,selenium_login,Success,True
.test_0_selenium_a_login,Total:109 Passed:109 Failed:0
1610711834172,314,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:110 Passed:110 Failed:0
1610711834849,675,selenium_create_page:open_create_page_editor,Success,True
1610711836065,587,selenium_create_page:save_created_page,Success,True
1610711836065,1891,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:111 Passed:111 Failed:0
1610711838600,2533,selenium_edit_page:open_create_page_editor,Success,True
1610711839280,661,selenium_edit_page:save_edited_page,Success,True
1610711839280,3214,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:112 Passed:112 Failed:0
1610711839925,305,selenium_create_comment:write_comment,Success,True
1610711840564,639,selenium_create_comment:save_comment,Success,True
1610711840564,1282,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:113 Passed:113 Failed:0
1610711841809,1242,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:114 Passed:114 Failed:0
1610711842857,1047,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:115 Passed:115 Failed:0
1610711843216,358,selenium_app_custom_action:view_page,Success,True
1610711843216,358,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:116 Passed:116 Failed:0
1610711843366,148,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:117 Passed:117 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.35s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711843503,88,selenium_login:open_login_page,Success,True
1610711844217,640,selenium_login:login_and_view_dashboard,Success,True
1610711844217,803,selenium_login,Success,True
.test_0_selenium_a_login,Total:118 Passed:118 Failed:0
1610711844543,303,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:119 Passed:119 Failed:0
1610711845241,696,selenium_create_page:open_create_page_editor,Success,True
1610711846491,596,selenium_create_page:save_created_page,Success,True
1610711846491,1946,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:120 Passed:120 Failed:0
1610711848522,2029,selenium_edit_page:open_create_page_editor,Success,True
1610711849193,652,selenium_edit_page:save_edited_page,Success,True
1610711849193,2700,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:121 Passed:121 Failed:0
1610711849845,314,selenium_create_comment:write_comment,Success,True
1610711849979,134,selenium_create_comment:save_comment,Success,True
1610711849979,785,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:122 Passed:122 Failed:0
1610711850519,538,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:123 Passed:123 Failed:0
1610711851546,1025,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:124 Passed:124 Failed:0
1610711851925,377,selenium_app_custom_action:view_page,Success,True
1610711851925,377,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:125 Passed:125 Failed:0
1610711852075,149,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:126 Passed:126 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.67s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711852217,94,selenium_login:open_login_page,Success,True
1610711852919,625,selenium_login:login_and_view_dashboard,Success,True
1610711852919,796,selenium_login,Success,True
.test_0_selenium_a_login,Total:127 Passed:127 Failed:0
1610711853447,504,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:128 Passed:128 Failed:0
1610711854089,640,selenium_create_page:open_create_page_editor,Success,True
1610711855299,590,selenium_create_page:save_created_page,Success,True
1610711855299,1851,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:129 Passed:129 Failed:0
1610711856335,1033,selenium_edit_page:open_create_page_editor,Success,True
1610711857097,743,selenium_edit_page:save_edited_page,Success,True
1610711857097,1796,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:130 Passed:130 Failed:0
1610711857770,302,selenium_create_comment:write_comment,Success,True
1610711858408,637,selenium_create_comment:save_comment,Success,True
1610711858408,1309,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:131 Passed:131 Failed:0
1610711858929,520,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:132 Passed:132 Failed:0
1610711859979,1047,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:133 Passed:133 Failed:0
1610711860393,412,selenium_app_custom_action:view_page,Success,True
1610711860393,412,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:134 Passed:134 Failed:0
1610711860487,92,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:135 Passed:135 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.37s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711860644,92,selenium_login:open_login_page,Success,True
1610711861327,609,selenium_login:login_and_view_dashboard,Success,True
1610711861327,775,selenium_login,Success,True
.test_0_selenium_a_login,Total:136 Passed:136 Failed:0
1610711861718,367,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:137 Passed:137 Failed:0
1610711862373,654,selenium_create_page:open_create_page_editor,Success,True
1610711863611,595,selenium_create_page:save_created_page,Success,True
1610711863612,1892,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:138 Passed:138 Failed:0
1610711865663,2049,selenium_edit_page:open_create_page_editor,Success,True
1610711866319,634,selenium_edit_page:save_edited_page,Success,True
1610711866319,2706,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:139 Passed:139 Failed:0
1610711867364,711,selenium_create_comment:write_comment,Success,True
1610711868009,644,selenium_create_comment:save_comment,Success,True
1610711868009,1688,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:140 Passed:140 Failed:0
1610711868718,707,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:141 Passed:141 Failed:0
1610711869763,1044,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:142 Passed:142 Failed:0
1610711870208,443,selenium_app_custom_action:view_page,Success,True
1610711870208,443,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:143 Passed:143 Failed:0
1610711870293,82,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:144 Passed:144 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.75s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711870436,89,selenium_login:open_login_page,Success,True
1610711871179,669,selenium_login:login_and_view_dashboard,Success,True
1610711871179,832,selenium_login,Success,True
.test_0_selenium_a_login,Total:145 Passed:145 Failed:0
1610711871576,375,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:146 Passed:146 Failed:0
1610711872190,612,selenium_create_page:open_create_page_editor,Success,True
1610711873436,588,selenium_create_page:save_created_page,Success,True
1610711873436,1858,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:147 Passed:147 Failed:0
1610711875464,2026,selenium_edit_page:open_create_page_editor,Success,True
1610711876111,628,selenium_edit_page:save_edited_page,Success,True
1610711876111,2673,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:148 Passed:148 Failed:0
1610711877149,708,selenium_create_comment:write_comment,Success,True
1610711877279,130,selenium_create_comment:save_comment,Success,True
1610711877280,1167,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:149 Passed:149 Failed:0
1610711877764,483,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:150 Passed:150 Failed:0
1610711878810,1044,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:151 Passed:151 Failed:0
1610711879231,419,selenium_app_custom_action:view_page,Success,True
1610711879231,420,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:152 Passed:152 Failed:0
1610711879327,95,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:153 Passed:153 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.99s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711879466,91,selenium_login:open_login_page,Success,True
1610711880265,723,selenium_login:login_and_view_dashboard,Success,True
1610711880265,890,selenium_login,Success,True
.test_0_selenium_a_login,Total:154 Passed:154 Failed:0
1610711880578,287,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:155 Passed:155 Failed:0
1610711881127,547,selenium_create_page:open_create_page_editor,Success,True
1610711882404,654,selenium_create_page:save_created_page,Success,True
1610711882404,1824,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:156 Passed:156 Failed:0
1610711884419,2013,selenium_edit_page:open_create_page_editor,Success,True
1610711885073,635,selenium_edit_page:save_edited_page,Success,True
1610711885073,2668,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:157 Passed:157 Failed:0
1610711886116,725,selenium_create_comment:write_comment,Success,True
1610711886772,655,selenium_create_comment:save_comment,Success,True
1610711886772,1698,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:158 Passed:158 Failed:0
1610711887321,547,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:159 Passed:159 Failed:0
1610711888359,1036,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:160 Passed:160 Failed:0
1610711888804,443,selenium_app_custom_action:view_page,Success,True
1610711888804,443,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:161 Passed:161 Failed:0
1610711888895,90,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:162 Passed:162 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.53s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711889048,105,selenium_login:open_login_page,Success,True
1610711889757,631,selenium_login:login_and_view_dashboard,Success,True
1610711889757,814,selenium_login,Success,True
.test_0_selenium_a_login,Total:163 Passed:163 Failed:0
1610711890467,690,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:164 Passed:164 Failed:0
1610711891166,697,selenium_create_page:open_create_page_editor,Success,True
1610711892347,563,selenium_create_page:save_created_page,Success,True
1610711892347,1878,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:165 Passed:165 Failed:0
1610711893952,1603,selenium_edit_page:open_create_page_editor,Success,True
1610711894832,860,selenium_edit_page:save_edited_page,Success,True
1610711894832,2483,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:166 Passed:166 Failed:0
1610711895640,349,selenium_create_comment:write_comment,Success,True
1610711895795,155,selenium_create_comment:save_comment,Success,True
1610711895795,962,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:167 Passed:167 Failed:0
1610711896377,580,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:168 Passed:168 Failed:0
1610711897386,1007,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:169 Passed:169 Failed:0
1610711897799,411,selenium_app_custom_action:view_page,Success,True
1610711897799,411,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:170 Passed:170 Failed:0
1610711897890,89,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:171 Passed:171 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.96s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711898036,99,selenium_login:open_login_page,Success,True
1610711898757,648,selenium_login:login_and_view_dashboard,Success,True
1610711898757,819,selenium_login,Success,True
.test_0_selenium_a_login,Total:172 Passed:172 Failed:0
1610711899152,380,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:173 Passed:173 Failed:0
1610711899813,660,selenium_create_page:open_create_page_editor,Success,True
1610711901032,599,selenium_create_page:save_created_page,Success,True
1610711901032,1879,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:174 Passed:174 Failed:0
1610711902076,1041,selenium_edit_page:open_create_page_editor,Success,True
1610711902755,660,selenium_edit_page:save_edited_page,Success,True
1610711902755,1721,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:175 Passed:175 Failed:0
1610711903409,304,selenium_create_comment:write_comment,Success,True
1610711904025,615,selenium_create_comment:save_comment,Success,True
1610711904025,1268,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:176 Passed:176 Failed:0
1610711905402,1375,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:177 Passed:177 Failed:0
1610711906407,1003,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:178 Passed:178 Failed:0
1610711906845,436,selenium_app_custom_action:view_page,Success,True
1610711906845,436,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:179 Passed:179 Failed:0
1610711906950,103,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:180 Passed:180 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.02s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711907090,92,selenium_login:open_login_page,Success,True
1610711907808,643,selenium_login:login_and_view_dashboard,Success,True
1610711907808,810,selenium_login,Success,True
.test_0_selenium_a_login,Total:181 Passed:181 Failed:0
1610711908219,398,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:182 Passed:182 Failed:0
1610711908840,619,selenium_create_page:open_create_page_editor,Success,True
1610711910053,595,selenium_create_page:save_created_page,Success,True
1610711910053,1832,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:183 Passed:183 Failed:0
1610711912086,2031,selenium_edit_page:open_create_page_editor,Success,True
1610711912738,633,selenium_edit_page:save_edited_page,Success,True
1610711912738,2683,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:184 Passed:184 Failed:0
1610711913397,295,selenium_create_comment:write_comment,Success,True
1610711913522,124,selenium_create_comment:save_comment,Success,True
1610711913522,782,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:185 Passed:185 Failed:0
1610711914040,516,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:186 Passed:186 Failed:0
1610711915075,1033,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:187 Passed:187 Failed:0
1610711915530,454,selenium_app_custom_action:view_page,Success,True
1610711915530,454,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:188 Passed:188 Failed:0
1610711915629,97,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:189 Passed:189 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.64s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711915775,96,selenium_login:open_login_page,Success,True
1610711916556,705,selenium_login:login_and_view_dashboard,Success,True
1610711916556,878,selenium_login,Success,True
.test_0_selenium_a_login,Total:190 Passed:190 Failed:0
1610711916964,384,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:191 Passed:191 Failed:0
1610711917646,680,selenium_create_page:open_create_page_editor,Success,True
1610711918867,598,selenium_create_page:save_created_page,Success,True
1610711918867,1901,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:192 Passed:192 Failed:0
1610711920393,1524,selenium_edit_page:open_create_page_editor,Success,True
1610711921084,669,selenium_edit_page:save_edited_page,Success,True
1610711921084,2216,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:193 Passed:193 Failed:0
1610711921772,297,selenium_create_comment:write_comment,Success,True
1610711922382,610,selenium_create_comment:save_comment,Success,True
1610711922382,1296,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:194 Passed:194 Failed:0
1610711922972,589,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:195 Passed:195 Failed:0
1610711924022,1048,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:196 Passed:196 Failed:0
1610711924458,434,selenium_app_custom_action:view_page,Success,True
1610711924458,434,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:197 Passed:197 Failed:0
1610711924544,85,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:198 Passed:198 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.88s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711924682,91,selenium_login:open_login_page,Success,True
1610711925452,695,selenium_login:login_and_view_dashboard,Success,True
1610711925452,861,selenium_login,Success,True
.test_0_selenium_a_login,Total:199 Passed:199 Failed:0
1610711925783,317,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:200 Passed:200 Failed:0
1610711926395,611,selenium_create_page:open_create_page_editor,Success,True
1610711927635,617,selenium_create_page:save_created_page,Success,True
1610711927635,1850,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:201 Passed:201 Failed:0
1610711929659,2022,selenium_edit_page:open_create_page_editor,Success,True
1610711930344,664,selenium_edit_page:save_edited_page,Success,True
1610711930344,2708,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:202 Passed:202 Failed:0
1610711931354,691,selenium_create_comment:write_comment,Success,True
1610711931963,608,selenium_create_comment:save_comment,Success,True
1610711931963,1617,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:203 Passed:203 Failed:0
1610711932346,381,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:204 Passed:204 Failed:0
1610711933375,1027,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:205 Passed:205 Failed:0
1610711933690,314,selenium_app_custom_action:view_page,Success,True
1610711933690,314,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:206 Passed:206 Failed:0
1610711933827,135,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:207 Passed:207 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.24s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711933965,85,selenium_login:open_login_page,Success,True
1610711934707,664,selenium_login:login_and_view_dashboard,Success,True
1610711934707,827,selenium_login,Success,True
.test_0_selenium_a_login,Total:208 Passed:208 Failed:0
1610711935431,709,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:209 Passed:209 Failed:0
1610711936146,713,selenium_create_page:open_create_page_editor,Success,True
1610711937369,601,selenium_create_page:save_created_page,Success,True
1610711937369,1937,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:210 Passed:210 Failed:0
1610711939546,2175,selenium_edit_page:open_create_page_editor,Success,True
1610711940474,909,selenium_edit_page:save_edited_page,Success,True
1610711940474,3103,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:211 Passed:211 Failed:0
1610711941338,312,selenium_create_comment:write_comment,Success,True
1610711941492,153,selenium_create_comment:save_comment,Success,True
1610711941492,1016,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:212 Passed:212 Failed:0
1610711942044,550,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:213 Passed:213 Failed:0
1610711943093,1047,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:214 Passed:214 Failed:0
1610711943558,464,selenium_app_custom_action:view_page,Success,True
1610711943558,464,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:215 Passed:215 Failed:0
1610711943649,89,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:216 Passed:216 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.78s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711943792,89,selenium_login:open_login_page,Success,True
1610711944558,681,selenium_login:login_and_view_dashboard,Success,True
1610711944558,855,selenium_login,Success,True
.test_0_selenium_a_login,Total:217 Passed:217 Failed:0
1610711945028,448,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:218 Passed:218 Failed:0
1610711945747,717,selenium_create_page:open_create_page_editor,Success,True
1610711946964,584,selenium_create_page:save_created_page,Success,True
1610711946964,1934,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:219 Passed:219 Failed:0
1610711948396,1430,selenium_edit_page:open_create_page_editor,Success,True
1610711949299,883,selenium_edit_page:save_edited_page,Success,True
1610711949299,2333,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:220 Passed:220 Failed:0
1610711950586,760,selenium_create_comment:write_comment,Success,True
1610711950728,141,selenium_create_comment:save_comment,Success,True
1610711950728,1428,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:221 Passed:221 Failed:0
1610711951145,414,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:222 Passed:222 Failed:0
1610711952239,1092,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:223 Passed:223 Failed:0
1610711952605,365,selenium_app_custom_action:view_page,Success,True
1610711952605,365,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:224 Passed:224 Failed:0
1610711952758,151,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:225 Passed:225 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.06s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711952894,88,selenium_login:open_login_page,Success,True
1610711953640,669,selenium_login:login_and_view_dashboard,Success,True
1610711953640,834,selenium_login,Success,True
.test_0_selenium_a_login,Total:226 Passed:226 Failed:0
1610711954369,711,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:227 Passed:227 Failed:0
1610711954995,623,selenium_create_page:open_create_page_editor,Success,True
1610711956225,599,selenium_create_page:save_created_page,Success,True
1610711956225,1854,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:228 Passed:228 Failed:0
1610711958412,2185,selenium_edit_page:open_create_page_editor,Success,True
1610711959232,800,selenium_edit_page:save_edited_page,Success,True
1610711959232,3005,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:229 Passed:229 Failed:0
1610711960517,620,selenium_create_comment:write_comment,Success,True
1610711961175,658,selenium_create_comment:save_comment,Success,True
1610711961175,1941,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:230 Passed:230 Failed:0
1610711961596,419,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:231 Passed:231 Failed:0
1610711962638,1040,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:232 Passed:232 Failed:0
1610711963005,366,selenium_app_custom_action:view_page,Success,True
1610711963005,366,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:233 Passed:233 Failed:0
1610711963163,156,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:234 Passed:234 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.37s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711963298,87,selenium_login:open_login_page,Success,True
1610711964038,662,selenium_login:login_and_view_dashboard,Success,True
1610711964038,827,selenium_login,Success,True
.test_0_selenium_a_login,Total:235 Passed:235 Failed:0
1610711964439,387,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:236 Passed:236 Failed:0
1610711965086,645,selenium_create_page:open_create_page_editor,Success,True
1610711966339,593,selenium_create_page:save_created_page,Success,True
1610711966339,1898,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:237 Passed:237 Failed:0
1610711967299,958,selenium_edit_page:open_create_page_editor,Success,True
1610711967972,652,selenium_edit_page:save_edited_page,Success,True
1610711967972,1632,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:238 Passed:238 Failed:0
1610711968612,287,selenium_create_comment:write_comment,Success,True
1610711969220,607,selenium_create_comment:save_comment,Success,True
1610711969220,1246,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:239 Passed:239 Failed:0
1610711969743,521,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:240 Passed:240 Failed:0
1610711970975,1231,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:241 Passed:241 Failed:0
1610711971382,405,selenium_app_custom_action:view_page,Success,True
1610711971382,405,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:242 Passed:242 Failed:0
1610711971485,101,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:243 Passed:243 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.28s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711971619,87,selenium_login:open_login_page,Success,True
1610711972311,611,selenium_login:login_and_view_dashboard,Success,True
1610711972311,779,selenium_login,Success,True
.test_0_selenium_a_login,Total:244 Passed:244 Failed:0
1610711972782,413,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:245 Passed:245 Failed:0
1610711973517,733,selenium_create_page:open_create_page_editor,Success,True
1610711974748,609,selenium_create_page:save_created_page,Success,True
1610711974748,1965,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:246 Passed:246 Failed:0
1610711977320,2570,selenium_edit_page:open_create_page_editor,Success,True
1610711978057,717,selenium_edit_page:save_edited_page,Success,True
1610711978057,3307,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:247 Passed:247 Failed:0
1610711979190,759,selenium_create_comment:write_comment,Success,True
1610711979814,624,selenium_create_comment:save_comment,Success,True
1610711979814,1756,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:248 Passed:248 Failed:0
1610711980326,510,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:249 Passed:249 Failed:0
1610711981605,1277,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:250 Passed:250 Failed:0
1610711982064,458,selenium_app_custom_action:view_page,Success,True
1610711982064,458,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:251 Passed:251 Failed:0
1610711982170,104,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:252 Passed:252 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.65s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711982312,92,selenium_login:open_login_page,Success,True
1610711982979,591,selenium_login:login_and_view_dashboard,Success,True
1610711982979,758,selenium_login,Success,True
.test_0_selenium_a_login,Total:253 Passed:253 Failed:0
1610711983312,320,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:254 Passed:254 Failed:0
1610711983860,547,selenium_create_page:open_create_page_editor,Success,True
1610711985050,564,selenium_create_page:save_created_page,Success,True
1610711985050,1736,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:255 Passed:255 Failed:0
1610711987052,2001,selenium_edit_page:open_create_page_editor,Success,True
1610711987758,686,selenium_edit_page:save_edited_page,Success,True
1610711987758,2707,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:256 Passed:256 Failed:0
1610711988365,295,selenium_create_comment:write_comment,Success,True
1610711988506,140,selenium_create_comment:save_comment,Success,True
1610711988506,747,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:257 Passed:257 Failed:0
1610711989637,1129,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:258 Passed:258 Failed:0
1610711990673,1034,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:259 Passed:259 Failed:0
1610711990985,311,selenium_app_custom_action:view_page,Success,True
1610711990985,311,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:260 Passed:260 Failed:0
1610711991099,111,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:261 Passed:261 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.89s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610711991282,110,selenium_login:open_login_page,Success,True
1610711992046,682,selenium_login:login_and_view_dashboard,Success,True
1610711992046,874,selenium_login,Success,True
.test_0_selenium_a_login,Total:262 Passed:262 Failed:0
1610711992404,338,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:263 Passed:263 Failed:0
1610711993067,661,selenium_create_page:open_create_page_editor,Success,True
1610711994283,593,selenium_create_page:save_created_page,Success,True
1610711994283,1877,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:264 Passed:264 Failed:0
1610711996307,2022,selenium_edit_page:open_create_page_editor,Success,True
1610711997063,735,selenium_edit_page:save_edited_page,Success,True
1610711997063,2778,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:265 Passed:265 Failed:0
1610711998150,746,selenium_create_comment:write_comment,Success,True
1610711998794,643,selenium_create_comment:save_comment,Success,True
1610711998794,1729,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:266 Passed:266 Failed:0
1610711999427,631,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:267 Passed:267 Failed:0
1610712000615,1186,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:268 Passed:268 Failed:0
1610712000992,376,selenium_app_custom_action:view_page,Success,True
1610712000992,376,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:269 Passed:269 Failed:0
1610712001117,123,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:270 Passed:270 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.95s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712001260,93,selenium_login:open_login_page,Success,True
1610712001993,658,selenium_login:login_and_view_dashboard,Success,True
1610712001993,827,selenium_login,Success,True
.test_0_selenium_a_login,Total:271 Passed:271 Failed:0
1610712002814,807,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:272 Passed:272 Failed:0
1610712003472,657,selenium_create_page:open_create_page_editor,Success,True
1610712004682,588,selenium_create_page:save_created_page,Success,True
1610712004682,1867,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:273 Passed:273 Failed:0
1610712006200,1515,selenium_edit_page:open_create_page_editor,Success,True
1610712007215,996,selenium_edit_page:save_edited_page,Success,True
1610712007215,2531,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:274 Passed:274 Failed:0
1610712008768,721,selenium_create_comment:write_comment,Success,True
1610712009405,637,selenium_create_comment:save_comment,Success,True
1610712009405,2188,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:275 Passed:275 Failed:0
1610712010000,593,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:276 Passed:276 Failed:0
1610712011087,1085,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:277 Passed:277 Failed:0
1610712011533,445,selenium_app_custom_action:view_page,Success,True
1610712011533,445,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:278 Passed:278 Failed:0
1610712011622,87,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:279 Passed:279 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.46s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712011781,103,selenium_login:open_login_page,Success,True
1610712012809,953,selenium_login:login_and_view_dashboard,Success,True
1610712012809,1131,selenium_login,Success,True
.test_0_selenium_a_login,Total:280 Passed:280 Failed:0
1610712013326,494,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:281 Passed:281 Failed:0
1610712014033,705,selenium_create_page:open_create_page_editor,Success,True
1610712015282,595,selenium_create_page:save_created_page,Success,True
1610712015282,1954,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:282 Passed:282 Failed:0
1610712016936,1651,selenium_edit_page:open_create_page_editor,Success,True
1610712017831,876,selenium_edit_page:save_edited_page,Success,True
1610712017831,2547,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:283 Passed:283 Failed:0
1610712018666,362,selenium_create_comment:write_comment,Success,True
1610712019324,657,selenium_create_comment:save_comment,Success,True
1610712019324,1491,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:284 Passed:284 Failed:0
1610712019790,465,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:285 Passed:285 Failed:0
1610712020982,1189,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:286 Passed:286 Failed:0
1610712021347,364,selenium_app_custom_action:view_page,Success,True
1610712021347,364,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:287 Passed:287 Failed:0
1610712021466,118,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:288 Passed:288 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.80s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712021608,92,selenium_login:open_login_page,Success,True
1610712022447,760,selenium_login:login_and_view_dashboard,Success,True
1610712022448,932,selenium_login,Success,True
.test_0_selenium_a_login,Total:289 Passed:289 Failed:0
1610712022893,431,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:290 Passed:290 Failed:0
1610712023540,645,selenium_create_page:open_create_page_editor,Success,True
1610712024764,603,selenium_create_page:save_created_page,Success,True
1610712024764,1869,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:291 Passed:291 Failed:0
1610712026556,1791,selenium_edit_page:open_create_page_editor,Success,True
1610712027329,751,selenium_edit_page:save_edited_page,Success,True
1610712027329,2564,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:292 Passed:292 Failed:0
1610712028016,315,selenium_create_comment:write_comment,Success,True
1610712028658,642,selenium_create_comment:save_comment,Success,True
1610712028658,1327,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:293 Passed:293 Failed:0
1610712029213,553,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:294 Passed:294 Failed:0
1610712030447,1232,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:295 Passed:295 Failed:0
1610712030827,379,selenium_app_custom_action:view_page,Success,True
1610712030827,379,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:296 Passed:296 Failed:0
1610712030981,151,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:297 Passed:297 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.47s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712031125,96,selenium_login:open_login_page,Success,True
1610712031908,700,selenium_login:login_and_view_dashboard,Success,True
1610712031908,879,selenium_login,Success,True
.test_0_selenium_a_login,Total:298 Passed:298 Failed:0
1610712032285,356,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:299 Passed:299 Failed:0
1610712032909,621,selenium_create_page:open_create_page_editor,Success,True
1610712034154,596,selenium_create_page:save_created_page,Success,True
1610712034154,1866,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:300 Passed:300 Failed:0
1610712035163,1007,selenium_edit_page:open_create_page_editor,Success,True
1610712035814,632,selenium_edit_page:save_edited_page,Success,True
1610712035814,1659,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:301 Passed:301 Failed:0
1610712036443,300,selenium_create_comment:write_comment,Success,True
1610712037084,640,selenium_create_comment:save_comment,Success,True
1610712037084,1268,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:302 Passed:302 Failed:0
1610712037516,431,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:303 Passed:303 Failed:0
1610712038584,1066,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:304 Passed:304 Failed:0
1610712038919,333,selenium_app_custom_action:view_page,Success,True
1610712038919,334,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:305 Passed:305 Failed:0
1610712039034,113,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:306 Passed:306 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.01s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712039181,98,selenium_login:open_login_page,Success,True
1610712039899,643,selenium_login:login_and_view_dashboard,Success,True
1610712039899,816,selenium_login,Success,True
.test_0_selenium_a_login,Total:307 Passed:307 Failed:0
1610712040349,435,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:308 Passed:308 Failed:0
1610712041083,733,selenium_create_page:open_create_page_editor,Success,True
1610712042296,594,selenium_create_page:save_created_page,Success,True
1610712042296,1945,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:309 Passed:309 Failed:0
1610712043946,1647,selenium_edit_page:open_create_page_editor,Success,True
1610712045042,1076,selenium_edit_page:save_edited_page,Success,True
1610712045042,2744,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:310 Passed:310 Failed:0
1610712046310,715,selenium_create_comment:write_comment,Success,True
1610712046441,130,selenium_create_comment:save_comment,Success,True
1610712046441,1397,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:311 Passed:311 Failed:0
1610712047776,1333,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:312 Passed:312 Failed:0
1610712048878,1100,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:313 Passed:313 Failed:0
1610712049252,372,selenium_app_custom_action:view_page,Success,True
1610712049252,372,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:314 Passed:314 Failed:0
1610712049408,154,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:315 Passed:315 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.33s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712049546,88,selenium_login:open_login_page,Success,True
1610712050341,719,selenium_login:login_and_view_dashboard,Success,True
1610712050341,883,selenium_login,Success,True
.test_0_selenium_a_login,Total:316 Passed:316 Failed:0
1610712050853,499,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:317 Passed:317 Failed:0
1610712051530,675,selenium_create_page:open_create_page_editor,Success,True
1610712052745,596,selenium_create_page:save_created_page,Success,True
1610712052745,1890,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:318 Passed:318 Failed:0
1610712054330,1584,selenium_edit_page:open_create_page_editor,Success,True
1610712055199,847,selenium_edit_page:save_edited_page,Success,True
1610712055199,2453,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:319 Passed:319 Failed:0
1610712056064,382,selenium_create_comment:write_comment,Success,True
1610712056198,133,selenium_create_comment:save_comment,Success,True
1610712056198,997,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:320 Passed:320 Failed:0
1610712056788,589,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:321 Passed:321 Failed:0
1610712057895,1105,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:322 Passed:322 Failed:0
1610712058252,355,selenium_app_custom_action:view_page,Success,True
1610712058252,355,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:323 Passed:323 Failed:0
1610712058372,119,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:324 Passed:324 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.92s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712058517,94,selenium_login:open_login_page,Success,True
1610712059234,637,selenium_login:login_and_view_dashboard,Success,True
1610712059234,812,selenium_login,Success,True
.test_0_selenium_a_login,Total:325 Passed:325 Failed:0
1610712059731,482,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:326 Passed:326 Failed:0
1610712060442,709,selenium_create_page:open_create_page_editor,Success,True
1610712061700,597,selenium_create_page:save_created_page,Success,True
1610712061700,1967,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:327 Passed:327 Failed:0
1610712064466,2764,selenium_edit_page:open_create_page_editor,Success,True
1610712065311,826,selenium_edit_page:save_edited_page,Success,True
1610712065311,3610,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:328 Passed:328 Failed:0
1610712066400,665,selenium_create_comment:write_comment,Success,True
1610712067050,649,selenium_create_comment:save_comment,Success,True
1610712067050,1737,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:329 Passed:329 Failed:0
1610712067633,581,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:330 Passed:330 Failed:0
1610712068732,1097,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:331 Passed:331 Failed:0
1610712069121,388,selenium_app_custom_action:view_page,Success,True
1610712069121,388,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:332 Passed:332 Failed:0
1610712069280,156,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:333 Passed:333 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.87s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712069417,88,selenium_login:open_login_page,Success,True
1610712070117,626,selenium_login:login_and_view_dashboard,Success,True
1610712070117,788,selenium_login,Success,True
.test_0_selenium_a_login,Total:334 Passed:334 Failed:0
1610712070529,388,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:335 Passed:335 Failed:0
1610712071165,634,selenium_create_page:open_create_page_editor,Success,True
1610712072384,596,selenium_create_page:save_created_page,Success,True
1610712072384,1854,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:336 Passed:336 Failed:0
1610712074431,2045,selenium_edit_page:open_create_page_editor,Success,True
1610712075110,658,selenium_edit_page:save_edited_page,Success,True
1610712075110,2724,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:337 Passed:337 Failed:0
1610712076138,719,selenium_create_comment:write_comment,Success,True
1610712076270,131,selenium_create_comment:save_comment,Success,True
1610712076270,1158,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:338 Passed:338 Failed:0
1610712076969,697,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:339 Passed:339 Failed:0
1610712078001,1030,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:340 Passed:340 Failed:0
1610712078365,363,selenium_app_custom_action:view_page,Success,True
1610712078365,363,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:341 Passed:341 Failed:0
1610712078519,152,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:342 Passed:342 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.20s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712078669,96,selenium_login:open_login_page,Success,True
1610712079488,743,selenium_login:login_and_view_dashboard,Success,True
1610712079488,915,selenium_login,Success,True
.test_0_selenium_a_login,Total:343 Passed:343 Failed:0
1610712079810,308,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:344 Passed:344 Failed:0
1610712080420,608,selenium_create_page:open_create_page_editor,Success,True
1610712081640,599,selenium_create_page:save_created_page,Success,True
1610712081641,1829,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:345 Passed:345 Failed:0
1610712082616,974,selenium_edit_page:open_create_page_editor,Success,True
1610712083357,720,selenium_edit_page:save_edited_page,Success,True
1610712083357,1715,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:346 Passed:346 Failed:0
1610712084312,622,selenium_create_comment:write_comment,Success,True
1610712084438,125,selenium_create_comment:save_comment,Success,True
1610712084438,1079,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:347 Passed:347 Failed:0
1610712084983,544,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:348 Passed:348 Failed:0
1610712086036,1051,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:349 Passed:349 Failed:0
1610712086358,320,selenium_app_custom_action:view_page,Success,True
1610712086358,320,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:350 Passed:350 Failed:0
1610712086506,146,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:351 Passed:351 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 7.94s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712086643,89,selenium_login:open_login_page,Success,True
1610712087393,676,selenium_login:login_and_view_dashboard,Success,True
1610712087393,839,selenium_login,Success,True
.test_0_selenium_a_login,Total:352 Passed:352 Failed:0
1610712087834,418,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:353 Passed:353 Failed:0
1610712088471,635,selenium_create_page:open_create_page_editor,Success,True
1610712089714,609,selenium_create_page:save_created_page,Success,True
1610712089714,1878,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:354 Passed:354 Failed:0
1610712091212,1496,selenium_edit_page:open_create_page_editor,Success,True
1610712091911,677,selenium_edit_page:save_edited_page,Success,True
1610712091911,2195,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:355 Passed:355 Failed:0
1610712092569,286,selenium_create_comment:write_comment,Success,True
1610712093179,610,selenium_create_comment:save_comment,Success,True
1610712093179,1267,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:356 Passed:356 Failed:0
1610712093652,471,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:357 Passed:357 Failed:0
1610712094697,1043,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:358 Passed:358 Failed:0
1610712095059,360,selenium_app_custom_action:view_page,Success,True
1610712095059,360,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:359 Passed:359 Failed:0
1610712095214,154,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:360 Passed:360 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.67s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712095351,89,selenium_login:open_login_page,Success,True
1610712096113,682,selenium_login:login_and_view_dashboard,Success,True
1610712096113,850,selenium_login,Success,True
.test_0_selenium_a_login,Total:361 Passed:361 Failed:0
1610712096523,384,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:362 Passed:362 Failed:0
1610712097155,630,selenium_create_page:open_create_page_editor,Success,True
1610712098375,597,selenium_create_page:save_created_page,Success,True
1610712098375,1850,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:363 Passed:363 Failed:0
1610712099333,957,selenium_edit_page:open_create_page_editor,Success,True
1610712099986,631,selenium_edit_page:save_edited_page,Success,True
1610712099986,1610,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:364 Passed:364 Failed:0
1610712101068,748,selenium_create_comment:write_comment,Success,True
1610712101670,602,selenium_create_comment:save_comment,Success,True
1610712101670,1682,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:365 Passed:365 Failed:0
1610712102201,530,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:366 Passed:366 Failed:0
1610712103337,1134,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:367 Passed:367 Failed:0
1610712103708,369,selenium_app_custom_action:view_page,Success,True
1610712103708,369,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:368 Passed:368 Failed:0
1610712103859,149,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:369 Passed:369 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.61s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712103998,86,selenium_login:open_login_page,Success,True
1610712104752,677,selenium_login:login_and_view_dashboard,Success,True
1610712104753,841,selenium_login,Success,True
.test_0_selenium_a_login,Total:370 Passed:370 Failed:0
1610712105148,381,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:371 Passed:371 Failed:0
1610712105831,681,selenium_create_page:open_create_page_editor,Success,True
1610712107084,623,selenium_create_page:save_created_page,Success,True
1610712107084,1934,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:372 Passed:372 Failed:0
1610712108085,1000,selenium_edit_page:open_create_page_editor,Success,True
1610712108776,668,selenium_edit_page:save_edited_page,Success,True
1610712108776,1690,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:373 Passed:373 Failed:0
1610712109829,721,selenium_create_comment:write_comment,Success,True
1610712110442,612,selenium_create_comment:save_comment,Success,True
1610712110442,1665,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:374 Passed:374 Failed:0
1610712110935,491,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:375 Passed:375 Failed:0
1610712111979,1043,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:376 Passed:376 Failed:0
1610712112423,442,selenium_app_custom_action:view_page,Success,True
1610712112423,442,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:377 Passed:377 Failed:0
1610712112529,104,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:378 Passed:378 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.63s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712112670,92,selenium_login:open_login_page,Success,True
1610712113497,750,selenium_login:login_and_view_dashboard,Success,True
1610712113497,918,selenium_login,Success,True
.test_0_selenium_a_login,Total:379 Passed:379 Failed:0
1610712114134,618,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:380 Passed:380 Failed:0
1610712114847,711,selenium_create_page:open_create_page_editor,Success,True
1610712116088,594,selenium_create_page:save_created_page,Success,True
1610712116088,1952,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:381 Passed:381 Failed:0
1610712118293,2204,selenium_edit_page:open_create_page_editor,Success,True
1610712119138,824,selenium_edit_page:save_edited_page,Success,True
1610712119138,3048,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:382 Passed:382 Failed:0
1610712120576,701,selenium_create_comment:write_comment,Success,True
1610712121196,620,selenium_create_comment:save_comment,Success,True
1610712121196,2056,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:383 Passed:383 Failed:0
1610712121768,570,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:384 Passed:384 Failed:0
1610712122816,1046,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:385 Passed:385 Failed:0
1610712123167,350,selenium_app_custom_action:view_page,Success,True
1610712123167,350,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:386 Passed:386 Failed:0
1610712123317,148,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:387 Passed:387 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.75s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712123455,90,selenium_login:open_login_page,Success,True
1610712124200,672,selenium_login:login_and_view_dashboard,Success,True
1610712124200,835,selenium_login,Success,True
.test_0_selenium_a_login,Total:388 Passed:388 Failed:0
1610712124572,356,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:389 Passed:389 Failed:0
1610712125232,659,selenium_create_page:open_create_page_editor,Success,True
1610712126455,598,selenium_create_page:save_created_page,Success,True
1610712126456,1882,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:390 Passed:390 Failed:0
1610712128527,2070,selenium_edit_page:open_create_page_editor,Success,True
1610712129237,689,selenium_edit_page:save_edited_page,Success,True
1610712129237,2780,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:391 Passed:391 Failed:0
1610712130272,712,selenium_create_comment:write_comment,Success,True
1610712130401,128,selenium_create_comment:save_comment,Success,True
1610712130401,1163,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:392 Passed:392 Failed:0
1610712131023,619,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:393 Passed:393 Failed:0
1610712132085,1061,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:394 Passed:394 Failed:0
1610712132456,369,selenium_app_custom_action:view_page,Success,True
1610712132456,369,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:395 Passed:395 Failed:0
1610712132616,158,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:396 Passed:396 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.26s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712132791,87,selenium_login:open_login_page,Success,True
1610712133527,663,selenium_login:login_and_view_dashboard,Success,True
1610712133527,824,selenium_login,Success,True
.test_0_selenium_a_login,Total:397 Passed:397 Failed:0
1610712133910,358,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:398 Passed:398 Failed:0
1610712134581,669,selenium_create_page:open_create_page_editor,Success,True
1610712135796,596,selenium_create_page:save_created_page,Success,True
1610712135796,1885,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:399 Passed:399 Failed:0
1610712138373,2575,selenium_edit_page:open_create_page_editor,Success,True
1610712139062,667,selenium_edit_page:save_edited_page,Success,True
1610712139062,3264,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:400 Passed:400 Failed:0
1610712139721,302,selenium_create_comment:write_comment,Success,True
1610712140331,609,selenium_create_comment:save_comment,Success,True
1610712140331,1268,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:401 Passed:401 Failed:0
1610712140827,495,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:402 Passed:402 Failed:0
1610712141932,1103,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:403 Passed:403 Failed:0
1610712142363,429,selenium_app_custom_action:view_page,Success,True
1610712142363,430,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:404 Passed:404 Failed:0
1610712142464,99,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:405 Passed:405 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.77s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712142601,90,selenium_login:open_login_page,Success,True
1610712143468,783,selenium_login:login_and_view_dashboard,Success,True
1610712143469,958,selenium_login,Success,True
.test_0_selenium_a_login,Total:406 Passed:406 Failed:0
1610712143916,423,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:407 Passed:407 Failed:0
1610712144578,659,selenium_create_page:open_create_page_editor,Success,True
1610712145810,605,selenium_create_page:save_created_page,Success,True
1610712145810,1891,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:408 Passed:408 Failed:0
1610712147371,1560,selenium_edit_page:open_create_page_editor,Success,True
1610712148070,677,selenium_edit_page:save_edited_page,Success,True
1610712148070,2258,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:409 Passed:409 Failed:0
1610712149152,746,selenium_create_comment:write_comment,Success,True
1610712149284,132,selenium_create_comment:save_comment,Success,True
1610712149284,1213,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:410 Passed:410 Failed:0
1610712149904,618,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:411 Passed:411 Failed:0
1610712150938,1032,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:412 Passed:412 Failed:0
1610712151379,439,selenium_app_custom_action:view_page,Success,True
1610712151379,439,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:413 Passed:413 Failed:0
1610712151472,91,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:414 Passed:414 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.97s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712151613,93,selenium_login:open_login_page,Success,True
1610712152348,662,selenium_login:login_and_view_dashboard,Success,True
1610712152348,827,selenium_login,Success,True
.test_0_selenium_a_login,Total:415 Passed:415 Failed:0
1610712152705,343,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:416 Passed:416 Failed:0
1610712153387,680,selenium_create_page:open_create_page_editor,Success,True
1610712154608,596,selenium_create_page:save_created_page,Success,True
1610712154608,1901,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:417 Passed:417 Failed:0
1610712156668,2059,selenium_edit_page:open_create_page_editor,Success,True
1610712157340,652,selenium_edit_page:save_edited_page,Success,True
1610712157340,2731,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:418 Passed:418 Failed:0
1610712158025,322,selenium_create_comment:write_comment,Success,True
1610712158647,621,selenium_create_comment:save_comment,Success,True
1610712158647,1305,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:419 Passed:419 Failed:0
1610712159150,502,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:420 Passed:420 Failed:0
1610712160193,1041,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:421 Passed:421 Failed:0
1610712160613,418,selenium_app_custom_action:view_page,Success,True
1610712160613,419,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:422 Passed:422 Failed:0
1610712160722,107,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:423 Passed:423 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.21s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712160864,92,selenium_login:open_login_page,Success,True
1610712161640,698,selenium_login:login_and_view_dashboard,Success,True
1610712161640,869,selenium_login,Success,True
.test_0_selenium_a_login,Total:424 Passed:424 Failed:0
1610712162090,434,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:425 Passed:425 Failed:0
1610712162771,679,selenium_create_page:open_create_page_editor,Success,True
1610712164017,617,selenium_create_page:save_created_page,Success,True
1610712164017,1926,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:426 Passed:426 Failed:0
1610712166051,2032,selenium_edit_page:open_create_page_editor,Success,True
1610712166756,683,selenium_edit_page:save_edited_page,Success,True
1610712166756,2737,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:427 Passed:427 Failed:0
1610712167894,815,selenium_create_comment:write_comment,Success,True
1610712168543,649,selenium_create_comment:save_comment,Success,True
1610712168543,1786,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:428 Passed:428 Failed:0
1610712169842,1297,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:429 Passed:429 Failed:0
1610712171029,1186,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:430 Passed:430 Failed:0
1610712171408,376,selenium_app_custom_action:view_page,Success,True
1610712171408,376,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:431 Passed:431 Failed:0
1610712171518,109,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:432 Passed:432 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.76s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712171661,95,selenium_login:open_login_page,Success,True
1610712172460,726,selenium_login:login_and_view_dashboard,Success,True
1610712172460,893,selenium_login,Success,True
.test_0_selenium_a_login,Total:433 Passed:433 Failed:0
1610712173347,865,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:434 Passed:434 Failed:0
1610712173999,650,selenium_create_page:open_create_page_editor,Success,True
1610712175223,605,selenium_create_page:save_created_page,Success,True
1610712175223,1874,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:435 Passed:435 Failed:0
1610712177813,2588,selenium_edit_page:open_create_page_editor,Success,True
1610712178659,826,selenium_edit_page:save_edited_page,Success,True
1610712178659,3435,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:436 Passed:436 Failed:0
1610712180079,802,selenium_create_comment:write_comment,Success,True
1610712180216,137,selenium_create_comment:save_comment,Success,True
1610712180216,1555,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:437 Passed:437 Failed:0
1610712180758,541,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:438 Passed:438 Failed:0
1610712181799,1039,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:439 Passed:439 Failed:0
1610712182215,414,selenium_app_custom_action:view_page,Success,True
1610712182215,414,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:440 Passed:440 Failed:0
1610712182377,160,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:441 Passed:441 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.82s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712182528,101,selenium_login:open_login_page,Success,True
1610712183532,882,selenium_login:login_and_view_dashboard,Success,True
1610712183532,1105,selenium_login,Success,True
.test_0_selenium_a_login,Total:442 Passed:442 Failed:0
1610712184133,575,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:443 Passed:443 Failed:0
1610712184794,659,selenium_create_page:open_create_page_editor,Success,True
1610712186031,596,selenium_create_page:save_created_page,Success,True
1610712186031,1896,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:444 Passed:444 Failed:0
1610712187453,1420,selenium_edit_page:open_create_page_editor,Success,True
1610712188372,898,selenium_edit_page:save_edited_page,Success,True
1610712188372,2339,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:445 Passed:445 Failed:0
1610712189638,841,selenium_create_comment:write_comment,Success,True
1610712189788,149,selenium_create_comment:save_comment,Success,True
1610712189788,1415,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:446 Passed:446 Failed:0
1610712190392,602,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:447 Passed:447 Failed:0
1610712191520,1126,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:448 Passed:448 Failed:0
1610712191948,427,selenium_app_custom_action:view_page,Success,True
1610712191948,427,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:449 Passed:449 Failed:0
1610712192061,111,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:450 Passed:450 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.64s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712192197,88,selenium_login:open_login_page,Success,True
1610712192946,674,selenium_login:login_and_view_dashboard,Success,True
1610712192946,838,selenium_login,Success,True
.test_0_selenium_a_login,Total:451 Passed:451 Failed:0
1610712193361,389,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:452 Passed:452 Failed:0
1610712194096,734,selenium_create_page:open_create_page_editor,Success,True
1610712195312,600,selenium_create_page:save_created_page,Success,True
1610712195313,1950,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:453 Passed:453 Failed:0
1610712197867,2553,selenium_edit_page:open_create_page_editor,Success,True
1610712198605,711,selenium_edit_page:save_edited_page,Success,True
1610712198605,3291,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:454 Passed:454 Failed:0
1610712199732,768,selenium_create_comment:write_comment,Success,True
1610712199882,150,selenium_create_comment:save_comment,Success,True
1610712199882,1276,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:455 Passed:455 Failed:0
1610712200412,528,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:456 Passed:456 Failed:0
1610712201527,1113,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:457 Passed:457 Failed:0
1610712201961,432,selenium_app_custom_action:view_page,Success,True
1610712201961,432,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:458 Passed:458 Failed:0
1610712202086,123,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:459 Passed:459 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.99s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712202291,156,selenium_login:open_login_page,Success,True
1610712202989,618,selenium_login:login_and_view_dashboard,Success,True
1610712202989,853,selenium_login,Success,True
.test_0_selenium_a_login,Total:460 Passed:460 Failed:0
1610712203381,369,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:461 Passed:461 Failed:0
1610712204046,663,selenium_create_page:open_create_page_editor,Success,True
1610712205269,595,selenium_create_page:save_created_page,Success,True
1610712205269,1886,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:462 Passed:462 Failed:0
1610712207308,2038,selenium_edit_page:open_create_page_editor,Success,True
1610712207972,644,selenium_edit_page:save_edited_page,Success,True
1610712207972,2702,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:463 Passed:463 Failed:0
1610712208592,301,selenium_create_comment:write_comment,Success,True
1610712209231,638,selenium_create_comment:save_comment,Success,True
1610712209231,1257,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:464 Passed:464 Failed:0
1610712209829,597,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:465 Passed:465 Failed:0
1610712211049,1218,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:466 Passed:466 Failed:0
1610712211487,436,selenium_app_custom_action:view_page,Success,True
1610712211487,437,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:467 Passed:467 Failed:0
1610712211598,109,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:468 Passed:468 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.47s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712211742,96,selenium_login:open_login_page,Success,True
1610712212482,662,selenium_login:login_and_view_dashboard,Success,True
1610712212482,836,selenium_login,Success,True
.test_0_selenium_a_login,Total:469 Passed:469 Failed:0
1610712212866,360,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:470 Passed:470 Failed:0
1610712213484,616,selenium_create_page:open_create_page_editor,Success,True
1610712214715,604,selenium_create_page:save_created_page,Success,True
1610712214715,1847,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:471 Passed:471 Failed:0
1610712215784,1068,selenium_edit_page:open_create_page_editor,Success,True
1610712216454,647,selenium_edit_page:save_edited_page,Success,True
1610712216454,1737,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:472 Passed:472 Failed:0
1610712217505,736,selenium_create_comment:write_comment,Success,True
1610712218123,618,selenium_create_comment:save_comment,Success,True
1610712218123,1668,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:473 Passed:473 Failed:0
1610712218685,560,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:474 Passed:474 Failed:0
1610712219723,1036,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:475 Passed:475 Failed:0
1610712220109,384,selenium_app_custom_action:view_page,Success,True
1610712220109,384,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:476 Passed:476 Failed:0
1610712220287,176,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:477 Passed:477 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.65s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712220427,93,selenium_login:open_login_page,Success,True
1610712221363,821,selenium_login:login_and_view_dashboard,Success,True
1610712221363,1028,selenium_login,Success,True
.test_0_selenium_a_login,Total:478 Passed:478 Failed:0
1610712221738,361,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:479 Passed:479 Failed:0
1610712222461,721,selenium_create_page:open_create_page_editor,Success,True
1610712223678,596,selenium_create_page:save_created_page,Success,True
1610712223678,1938,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:480 Passed:480 Failed:0
1610712225217,1537,selenium_edit_page:open_create_page_editor,Success,True
1610712225878,642,selenium_edit_page:save_edited_page,Success,True
1610712225878,2198,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:481 Passed:481 Failed:0
1610712226501,302,selenium_create_comment:write_comment,Success,True
1610712226631,129,selenium_create_comment:save_comment,Success,True
1610712226631,751,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:482 Passed:482 Failed:0
1610712227102,469,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:483 Passed:483 Failed:0
1610712228146,1042,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:484 Passed:484 Failed:0
1610712228502,354,selenium_app_custom_action:view_page,Success,True
1610712228502,354,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:485 Passed:485 Failed:0
1610712228616,112,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:486 Passed:486 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.29s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712228759,94,selenium_login:open_login_page,Success,True
1610712229684,852,selenium_login:login_and_view_dashboard,Success,True
1610712229684,1020,selenium_login,Success,True
.test_0_selenium_a_login,Total:487 Passed:487 Failed:0
1610712230200,487,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:488 Passed:488 Failed:0
1610712230829,627,selenium_create_page:open_create_page_editor,Success,True
1610712232052,597,selenium_create_page:save_created_page,Success,True
1610712232052,1850,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:489 Passed:489 Failed:0
1610712233634,1580,selenium_edit_page:open_create_page_editor,Success,True
1610712234297,643,selenium_edit_page:save_edited_page,Success,True
1610712234297,2243,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:490 Passed:490 Failed:0
1610712235494,738,selenium_create_comment:write_comment,Success,True
1610712236149,654,selenium_create_comment:save_comment,Success,True
1610712236149,1850,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:491 Passed:491 Failed:0
1610712236614,463,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:492 Passed:492 Failed:0
1610712237698,1083,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:493 Passed:493 Failed:0
1610712238059,359,selenium_app_custom_action:view_page,Success,True
1610712238059,359,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:494 Passed:494 Failed:0
1610712238210,149,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:495 Passed:495 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.55s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712238346,88,selenium_login:open_login_page,Success,True
1610712239138,679,selenium_login:login_and_view_dashboard,Success,True
1610712239138,879,selenium_login,Success,True
.test_0_selenium_a_login,Total:496 Passed:496 Failed:0
1610712239519,365,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:497 Passed:497 Failed:0
1610712240202,682,selenium_create_page:open_create_page_editor,Success,True
1610712241417,592,selenium_create_page:save_created_page,Success,True
1610712241417,1896,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:498 Passed:498 Failed:0
1610712243486,2067,selenium_edit_page:open_create_page_editor,Success,True
1610712244195,690,selenium_edit_page:save_edited_page,Success,True
1610712244195,2777,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:499 Passed:499 Failed:0
1610712245189,683,selenium_create_comment:write_comment,Success,True
1610712245803,614,selenium_create_comment:save_comment,Success,True
1610712245803,1607,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:500 Passed:500 Failed:0
1610712246356,551,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:501 Passed:501 Failed:0
1610712247449,1091,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:502 Passed:502 Failed:0
1610712247822,371,selenium_app_custom_action:view_page,Success,True
1610712247822,371,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:503 Passed:503 Failed:0
1610712247934,110,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:504 Passed:504 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.68s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712248069,88,selenium_login:open_login_page,Success,True
1610712248977,798,selenium_login:login_and_view_dashboard,Success,True
1610712248977,996,selenium_login,Success,True
.test_0_selenium_a_login,Total:505 Passed:505 Failed:0
1610712249460,469,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:506 Passed:506 Failed:0
1610712250221,759,selenium_create_page:open_create_page_editor,Success,True
1610712251490,636,selenium_create_page:save_created_page,Success,True
1610712251491,2029,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:507 Passed:507 Failed:0
1610712253138,1645,selenium_edit_page:open_create_page_editor,Success,True
1610712253966,809,selenium_edit_page:save_edited_page,Success,True
1610712253966,2474,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:508 Passed:508 Failed:0
1610712254847,334,selenium_create_comment:write_comment,Success,True
1610712255463,616,selenium_create_comment:save_comment,Success,True
1610712255463,1495,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:509 Passed:509 Failed:0
1610712256059,594,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:510 Passed:510 Failed:0
1610712257138,1076,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:511 Passed:511 Failed:0
1610712257571,432,selenium_app_custom_action:view_page,Success,True
1610712257571,432,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:512 Passed:512 Failed:0
1610712257694,121,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:513 Passed:513 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.72s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712257835,93,selenium_login:open_login_page,Success,True
1610712258843,933,selenium_login:login_and_view_dashboard,Success,True
1610712258843,1101,selenium_login,Success,True
.test_0_selenium_a_login,Total:514 Passed:514 Failed:0
1610712259330,474,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:515 Passed:515 Failed:0
1610712260024,692,selenium_create_page:open_create_page_editor,Success,True
1610712261287,634,selenium_create_page:save_created_page,Success,True
1610712261287,1955,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:516 Passed:516 Failed:0
1610712262922,1633,selenium_edit_page:open_create_page_editor,Success,True
1610712263789,848,selenium_edit_page:save_edited_page,Success,True
1610712263789,2501,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:517 Passed:517 Failed:0
1610712264943,670,selenium_create_comment:write_comment,Success,True
1610712265569,625,selenium_create_comment:save_comment,Success,True
1610712265569,1778,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:518 Passed:518 Failed:0
1610712266051,481,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:519 Passed:519 Failed:0
1610712267278,1225,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:520 Passed:520 Failed:0
1610712267604,325,selenium_app_custom_action:view_page,Success,True
1610712267604,325,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:521 Passed:521 Failed:0
1610712267751,145,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:522 Passed:522 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.02s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712267930,94,selenium_login:open_login_page,Success,True
1610712268650,645,selenium_login:login_and_view_dashboard,Success,True
1610712268650,814,selenium_login,Success,True
.test_0_selenium_a_login,Total:523 Passed:523 Failed:0
1610712269048,383,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:524 Passed:524 Failed:0
1610712269759,709,selenium_create_page:open_create_page_editor,Success,True
1610712270969,593,selenium_create_page:save_created_page,Success,True
1610712270969,1920,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:525 Passed:525 Failed:0
1610712273609,2638,selenium_edit_page:open_create_page_editor,Success,True
1610712274374,745,selenium_edit_page:save_edited_page,Success,True
1610712274374,3403,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:526 Passed:526 Failed:0
1610712275490,712,selenium_create_comment:write_comment,Success,True
1610712276133,642,selenium_create_comment:save_comment,Success,True
1610712276133,1757,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:527 Passed:527 Failed:0
1610712276723,588,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:528 Passed:528 Failed:0
1610712277848,1123,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:529 Passed:529 Failed:0
1610712278266,417,selenium_app_custom_action:view_page,Success,True
1610712278266,417,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:530 Passed:530 Failed:0
1610712278379,112,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:531 Passed:531 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.55s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712278524,94,selenium_login:open_login_page,Success,True
1610712279471,871,selenium_login:login_and_view_dashboard,Success,True
1610712279471,1041,selenium_login,Success,True
.test_0_selenium_a_login,Total:532 Passed:532 Failed:0
1610712280481,986,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:533 Passed:533 Failed:0
1610712281167,684,selenium_create_page:open_create_page_editor,Success,True
1610712282423,597,selenium_create_page:save_created_page,Success,True
1610712282423,1941,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:534 Passed:534 Failed:0
1610712283445,1020,selenium_edit_page:open_create_page_editor,Success,True
1610712284519,1053,selenium_edit_page:save_edited_page,Success,True
1610712284519,2094,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:535 Passed:535 Failed:0
1610712286179,757,selenium_create_comment:write_comment,Success,True
1610712286313,134,selenium_create_comment:save_comment,Success,True
1610712286313,1793,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:536 Passed:536 Failed:0
1610712286915,600,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:537 Passed:537 Failed:0
1610712288019,1102,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:538 Passed:538 Failed:0
1610712288404,384,selenium_app_custom_action:view_page,Success,True
1610712288404,384,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:539 Passed:539 Failed:0
1610712288560,154,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:540 Passed:540 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 10.14s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712288702,90,selenium_login:open_login_page,Success,True
1610712289496,716,selenium_login:login_and_view_dashboard,Success,True
1610712289496,884,selenium_login,Success,True
.test_0_selenium_a_login,Total:541 Passed:541 Failed:0
1610712289855,345,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:542 Passed:542 Failed:0
1610712290552,695,selenium_create_page:open_create_page_editor,Success,True
1610712291766,594,selenium_create_page:save_created_page,Success,True
1610712291766,1910,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:543 Passed:543 Failed:0
1610712292814,1046,selenium_edit_page:open_create_page_editor,Success,True
1610712293556,722,selenium_edit_page:save_edited_page,Success,True
1610712293556,1788,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:544 Passed:544 Failed:0
1610712294545,681,selenium_create_comment:write_comment,Success,True
1610712294674,129,selenium_create_comment:save_comment,Success,True
1610712294674,1116,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:545 Passed:545 Failed:0
1610712295137,461,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:546 Passed:546 Failed:0
1610712296363,1225,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:547 Passed:547 Failed:0
1610712296829,464,selenium_app_custom_action:view_page,Success,True
1610712296829,464,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:548 Passed:548 Failed:0
1610712296926,95,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:549 Passed:549 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.33s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712297065,92,selenium_login:open_login_page,Success,True
1610712297782,642,selenium_login:login_and_view_dashboard,Success,True
1610712297782,809,selenium_login,Success,True
.test_0_selenium_a_login,Total:550 Passed:550 Failed:0
1610712298141,334,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:551 Passed:551 Failed:0
1610712298816,673,selenium_create_page:open_create_page_editor,Success,True
1610712300073,593,selenium_create_page:save_created_page,Success,True
1610712300073,1931,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:552 Passed:552 Failed:0
1610712302145,2070,selenium_edit_page:open_create_page_editor,Success,True
1610712302823,655,selenium_edit_page:save_edited_page,Success,True
1610712302823,2749,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:553 Passed:553 Failed:0
1610712303885,699,selenium_create_comment:write_comment,Success,True
1610712304495,610,selenium_create_comment:save_comment,Success,True
1610712304495,1670,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:554 Passed:554 Failed:0
1610712305045,548,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:555 Passed:555 Failed:0
1610712306107,1061,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:556 Passed:556 Failed:0
1610712306497,388,selenium_app_custom_action:view_page,Success,True
1610712306497,388,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:557 Passed:557 Failed:0
1610712306658,160,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:558 Passed:558 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 9.69s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712306800,94,selenium_login:open_login_page,Success,True
1610712307516,638,selenium_login:login_and_view_dashboard,Success,True
1610712307516,810,selenium_login,Success,True
.test_0_selenium_a_login,Total:559 Passed:559 Failed:0
1610712307908,379,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:560 Passed:560 Failed:0
1610712308568,658,selenium_create_page:open_create_page_editor,Success,True
1610712309831,592,selenium_create_page:save_created_page,Success,True
1610712309831,1921,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:561 Passed:561 Failed:0
1610712311384,1551,selenium_edit_page:open_create_page_editor,Success,True
1610712312077,669,selenium_edit_page:save_edited_page,Success,True
1610712312077,2245,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:562 Passed:562 Failed:0
1610712312731,315,selenium_create_comment:write_comment,Success,True
1610712312862,130,selenium_create_comment:save_comment,Success,True
1610712312862,783,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:563 Passed:563 Failed:0
1610712313387,523,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:564 Passed:564 Failed:0
1610712314556,1168,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:565 Passed:565 Failed:0
1610712314919,361,selenium_app_custom_action:view_page,Success,True
1610712314919,361,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:566 Passed:566 Failed:0
1610712315043,122,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:567 Passed:567 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.35s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1610712315186,95,selenium_login:open_login_page,Success,True
1610712315934,674,selenium_login:login_and_view_dashboard,Success,True
1610712315935,843,selenium_login,Success,True
.test_0_selenium_a_login,Total:568 Passed:568 Failed:0
1610712316326,374,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:569 Passed:569 Failed:0
1610712316999,671,selenium_create_page:open_create_page_editor,Success,True
1610712318238,593,selenium_create_page:save_created_page,Success,True
1610712318238,1910,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:570 Passed:570 Failed:0
1610712319727,1487,selenium_edit_page:open_create_page_editor,Success,True
1610712320432,684,selenium_edit_page:save_edited_page,Success,True
1610712320432,2192,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:571 Passed:571 Failed:0
1610712321475,743,selenium_create_comment:write_comment,Success,True
1610712321615,139,selenium_create_comment:save_comment,Success,True
1610712321615,1182,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:572 Passed:572 Failed:0
1610712322299,682,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:573 Passed:573 Failed:0
1610712323330,1030,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:574 Passed:574 Failed:0
1610712323680,348,selenium_app_custom_action:view_page,Success,True
1610712323680,348,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:575 Passed:575 Failed:0
1610712323796,115,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:576 Passed:576 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================= 9 passed, 1 warning in 8.71s =========================
