============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py first driver inits
1613038023172,322,selenium_login:open_login_page,Success,True
1613038024059,805,selenium_login:login_and_view_dashboard,Success,True
1613038024060,1209,selenium_login,Success,True
.test_0_selenium_a_login,Total:1 Passed:1 Failed:0
1613038024640,546,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:2 Passed:2 Failed:0
1613038025419,777,selenium_create_page:open_create_page_editor,Success,True
1613038026649,603,selenium_create_page:save_created_page,Success,True
1613038026649,2007,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:3 Passed:3 Failed:0
1613038028288,1636,selenium_edit_page:open_create_page_editor,Success,True
1613038029010,702,selenium_edit_page:save_edited_page,Success,True
1613038029010,2359,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:4 Passed:4 Failed:0
1613038030063,679,selenium_create_comment:write_comment,Success,True
1613038030678,615,selenium_create_comment:save_comment,Success,True
1613038030679,1667,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:5 Passed:5 Failed:0
1613038031405,725,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:6 Passed:6 Failed:0
1613038033086,1678,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:7 Passed:7 Failed:0
1613038035907,2820,selenium_app_custom_action:view_page,Success,True
1613038035907,2820,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:8 Passed:8 Failed:0
1613038036106,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:9 Passed:9 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.39s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038036284,124,selenium_login:open_login_page,Success,True
1613038037158,792,selenium_login:login_and_view_dashboard,Success,True
1613038037158,998,selenium_login,Success,True
.test_0_selenium_a_login,Total:10 Passed:10 Failed:0
1613038037668,449,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:11 Passed:11 Failed:0
1613038038321,652,selenium_create_page:open_create_page_editor,Success,True
1613038039606,645,selenium_create_page:save_created_page,Success,True
1613038039606,1937,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:12 Passed:12 Failed:0
1613038041159,1551,selenium_edit_page:open_create_page_editor,Success,True
1613038041936,756,selenium_edit_page:save_edited_page,Success,True
1613038041936,2328,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:13 Passed:13 Failed:0
1613038042985,684,selenium_create_comment:write_comment,Success,True
1613038043601,616,selenium_create_comment:save_comment,Success,True
1613038043601,1663,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:14 Passed:14 Failed:0
1613038044184,581,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:15 Passed:15 Failed:0
1613038045882,1697,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:16 Passed:16 Failed:0
1613038048923,3039,selenium_app_custom_action:view_page,Success,True
1613038048923,3039,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:17 Passed:17 Failed:0
1613038049147,222,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:18 Passed:18 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.00s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038049321,123,selenium_login:open_login_page,Success,True
1613038050205,805,selenium_login:login_and_view_dashboard,Success,True
1613038050205,1006,selenium_login,Success,True
.test_0_selenium_a_login,Total:19 Passed:19 Failed:0
1613038050616,353,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:20 Passed:20 Failed:0
1613038051368,750,selenium_create_page:open_create_page_editor,Success,True
1613038052651,613,selenium_create_page:save_created_page,Success,True
1613038052651,2034,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:21 Passed:21 Failed:0
1613038055260,2607,selenium_edit_page:open_create_page_editor,Success,True
1613038056050,770,selenium_edit_page:save_edited_page,Success,True
1613038056050,3398,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:22 Passed:22 Failed:0
1613038057078,683,selenium_create_comment:write_comment,Success,True
1613038057705,626,selenium_create_comment:save_comment,Success,True
1613038057705,1653,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:23 Passed:23 Failed:0
1613038058250,543,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:24 Passed:24 Failed:0
1613038059941,1689,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:25 Passed:25 Failed:0
1613038062765,2822,selenium_app_custom_action:view_page,Success,True
1613038062765,2822,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:26 Passed:26 Failed:0
1613038062960,194,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:27 Passed:27 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.77s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038063136,123,selenium_login:open_login_page,Success,True
1613038063989,772,selenium_login:login_and_view_dashboard,Success,True
1613038063989,977,selenium_login,Success,True
.test_0_selenium_a_login,Total:28 Passed:28 Failed:0
1613038064975,972,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:29 Passed:29 Failed:0
1613038065778,801,selenium_create_page:open_create_page_editor,Success,True
1613038067046,633,selenium_create_page:save_created_page,Success,True
1613038067046,2069,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:30 Passed:30 Failed:0
1613038068065,1017,selenium_edit_page:open_create_page_editor,Success,True
1613038069335,1250,selenium_edit_page:save_edited_page,Success,True
1613038069335,2288,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:31 Passed:31 Failed:0
1613038070982,693,selenium_create_comment:write_comment,Success,True
1613038071606,623,selenium_create_comment:save_comment,Success,True
1613038071606,2269,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:32 Passed:32 Failed:0
1613038072248,640,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:33 Passed:33 Failed:0
1613038073951,1702,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:34 Passed:34 Failed:0
1613038076792,2839,selenium_app_custom_action:view_page,Success,True
1613038076792,2839,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:35 Passed:35 Failed:0
1613038076986,192,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:36 Passed:36 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.98s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038077171,124,selenium_login:open_login_page,Success,True
1613038078022,769,selenium_login:login_and_view_dashboard,Success,True
1613038078022,975,selenium_login,Success,True
.test_0_selenium_a_login,Total:37 Passed:37 Failed:0
1613038078967,887,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:38 Passed:38 Failed:0
1613038079657,688,selenium_create_page:open_create_page_editor,Success,True
1613038080905,619,selenium_create_page:save_created_page,Success,True
1613038080905,1936,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:39 Passed:39 Failed:0
1613038081924,1017,selenium_edit_page:open_create_page_editor,Success,True
1613038083026,1078,selenium_edit_page:save_edited_page,Success,True
1613038083026,2119,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:40 Passed:40 Failed:0
1613038084556,681,selenium_create_comment:write_comment,Success,True
1613038085176,620,selenium_create_comment:save_comment,Success,True
1613038085176,2149,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:41 Passed:41 Failed:0
1613038085862,684,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:42 Passed:42 Failed:0
1613038087533,1670,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:43 Passed:43 Failed:0
1613038090465,2930,selenium_app_custom_action:view_page,Success,True
1613038090465,2930,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:44 Passed:44 Failed:0
1613038090659,192,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:45 Passed:45 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.62s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038090830,121,selenium_login:open_login_page,Success,True
1613038091735,822,selenium_login:login_and_view_dashboard,Success,True
1613038091735,1025,selenium_login,Success,True
.test_0_selenium_a_login,Total:46 Passed:46 Failed:0
1613038092191,442,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:47 Passed:47 Failed:0
1613038092792,599,selenium_create_page:open_create_page_editor,Success,True
1613038094068,648,selenium_create_page:save_created_page,Success,True
1613038094068,1875,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:48 Passed:48 Failed:0
1613038096260,2190,selenium_edit_page:open_create_page_editor,Success,True
1613038097215,934,selenium_edit_page:save_edited_page,Success,True
1613038097216,3146,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:49 Passed:49 Failed:0
1613038098193,556,selenium_create_comment:write_comment,Success,True
1613038098828,634,selenium_create_comment:save_comment,Success,True
1613038098828,1611,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:50 Passed:50 Failed:0
1613038099463,633,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:51 Passed:51 Failed:0
1613038101128,1663,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:52 Passed:52 Failed:0
1613038103964,2835,selenium_app_custom_action:view_page,Success,True
1613038103964,2835,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:53 Passed:53 Failed:0
1613038104175,209,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:54 Passed:54 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.47s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038104348,121,selenium_login:open_login_page,Success,True
1613038105176,746,selenium_login:login_and_view_dashboard,Success,True
1613038105176,949,selenium_login,Success,True
.test_0_selenium_a_login,Total:55 Passed:55 Failed:0
1613038105604,414,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:56 Passed:56 Failed:0
1613038106172,567,selenium_create_page:open_create_page_editor,Success,True
1613038107450,573,selenium_create_page:save_created_page,Success,True
1613038107450,1844,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:57 Passed:57 Failed:0
1613038109008,1556,selenium_edit_page:open_create_page_editor,Success,True
1613038109813,785,selenium_edit_page:save_edited_page,Success,True
1613038109813,2362,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:58 Passed:58 Failed:0
1613038110782,555,selenium_create_comment:write_comment,Success,True
1613038111415,632,selenium_create_comment:save_comment,Success,True
1613038111415,1600,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:59 Passed:59 Failed:0
1613038112769,1352,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:60 Passed:60 Failed:0
1613038114440,1669,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:61 Passed:61 Failed:0
1613038117004,2562,selenium_app_custom_action:view_page,Success,True
1613038117004,2562,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:62 Passed:62 Failed:0
1613038117198,192,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:63 Passed:63 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.98s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038117374,124,selenium_login:open_login_page,Success,True
1613038118207,753,selenium_login:login_and_view_dashboard,Success,True
1613038118207,958,selenium_login,Success,True
.test_0_selenium_a_login,Total:64 Passed:64 Failed:0
1613038118742,477,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:65 Passed:65 Failed:0
1613038119601,857,selenium_create_page:open_create_page_editor,Success,True
1613038120892,632,selenium_create_page:save_created_page,Success,True
1613038120892,2149,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:66 Passed:66 Failed:0
1613038122623,1729,selenium_edit_page:open_create_page_editor,Success,True
1613038123694,1050,selenium_edit_page:save_edited_page,Success,True
1613038123694,2800,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:67 Passed:67 Failed:0
1613038125105,835,selenium_create_comment:write_comment,Success,True
1613038125730,624,selenium_create_comment:save_comment,Success,True
1613038125730,2033,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:68 Passed:68 Failed:0
1613038126378,647,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:69 Passed:69 Failed:0
1613038128056,1676,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:70 Passed:70 Failed:0
1613038131210,3152,selenium_app_custom_action:view_page,Success,True
1613038131210,3152,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:71 Passed:71 Failed:0
1613038131415,202,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:72 Passed:72 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.17s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038131600,130,selenium_login:open_login_page,Success,True
1613038132557,877,selenium_login:login_and_view_dashboard,Success,True
1613038132557,1088,selenium_login,Success,True
.test_0_selenium_a_login,Total:73 Passed:73 Failed:0
1613038133168,587,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:74 Passed:74 Failed:0
1613038133778,609,selenium_create_page:open_create_page_editor,Success,True
1613038135066,652,selenium_create_page:save_created_page,Success,True
1613038135067,1897,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:75 Passed:75 Failed:0
1613038136721,1652,selenium_edit_page:open_create_page_editor,Success,True
1613038137668,926,selenium_edit_page:save_edited_page,Success,True
1613038137668,2599,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:76 Passed:76 Failed:0
1613038138540,375,selenium_create_comment:write_comment,Success,True
1613038139163,623,selenium_create_comment:save_comment,Success,True
1613038139163,1494,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:77 Passed:77 Failed:0
1613038139852,687,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:78 Passed:78 Failed:0
1613038141532,1678,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:79 Passed:79 Failed:0
1613038144642,3108,selenium_app_custom_action:view_page,Success,True
1613038144642,3108,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:80 Passed:80 Failed:0
1613038144836,192,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:81 Passed:81 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.38s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038145033,146,selenium_login:open_login_page,Success,True
1613038145918,802,selenium_login:login_and_view_dashboard,Success,True
1613038145918,1031,selenium_login,Success,True
.test_0_selenium_a_login,Total:82 Passed:82 Failed:0
1613038146490,557,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:83 Passed:83 Failed:0
1613038147319,828,selenium_create_page:open_create_page_editor,Success,True
1613038148599,641,selenium_create_page:save_created_page,Success,True
1613038148599,2107,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:84 Passed:84 Failed:0
1613038150339,1738,selenium_edit_page:open_create_page_editor,Success,True
1613038151519,1159,selenium_edit_page:save_edited_page,Success,True
1613038151519,2919,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:85 Passed:85 Failed:0
1613038152771,752,selenium_create_comment:write_comment,Success,True
1613038153399,627,selenium_create_comment:save_comment,Success,True
1613038153399,1878,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:86 Passed:86 Failed:0
1613038154045,643,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:87 Passed:87 Failed:0
1613038155780,1733,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:88 Passed:88 Failed:0
1613038158700,2918,selenium_app_custom_action:view_page,Success,True
1613038158700,2918,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:89 Passed:89 Failed:0
1613038158899,196,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:90 Passed:90 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.02s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038159077,125,selenium_login:open_login_page,Success,True
1613038160040,881,selenium_login:login_and_view_dashboard,Success,True
1613038160040,1089,selenium_login,Success,True
.test_0_selenium_a_login,Total:91 Passed:91 Failed:0
1613038161034,934,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:92 Passed:92 Failed:0
1613038161712,676,selenium_create_page:open_create_page_editor,Success,True
1613038163061,721,selenium_create_page:save_created_page,Success,True
1613038163061,2025,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:93 Passed:93 Failed:0
1613038165694,2631,selenium_edit_page:open_create_page_editor,Success,True
1613038167081,1317,selenium_edit_page:save_edited_page,Success,True
1613038167081,4019,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:94 Passed:94 Failed:0
1613038168611,676,selenium_create_comment:write_comment,Success,True
1613038169241,630,selenium_create_comment:save_comment,Success,True
1613038169241,2158,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:95 Passed:95 Failed:0
1613038169818,575,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:96 Passed:96 Failed:0
1613038171499,1679,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:97 Passed:97 Failed:0
1613038174481,2981,selenium_app_custom_action:view_page,Success,True
1613038174481,2981,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:98 Passed:98 Failed:0
1613038174696,213,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:99 Passed:99 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.75s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038174870,123,selenium_login:open_login_page,Success,True
1613038175747,795,selenium_login:login_and_view_dashboard,Success,True
1613038175747,999,selenium_login,Success,True
.test_0_selenium_a_login,Total:100 Passed:100 Failed:0
1613038176217,414,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:101 Passed:101 Failed:0
1613038177085,866,selenium_create_page:open_create_page_editor,Success,True
1613038178341,617,selenium_create_page:save_created_page,Success,True
1613038178341,2123,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:102 Passed:102 Failed:0
1613038179884,1541,selenium_edit_page:open_create_page_editor,Success,True
1613038180815,907,selenium_edit_page:save_edited_page,Success,True
1613038180815,2472,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:103 Passed:103 Failed:0
1613038182017,728,selenium_create_comment:write_comment,Success,True
1613038182667,649,selenium_create_comment:save_comment,Success,True
1613038182667,1850,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:104 Passed:104 Failed:0
1613038183250,582,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:105 Passed:105 Failed:0
1613038184960,1707,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:106 Passed:106 Failed:0
1613038187918,2956,selenium_app_custom_action:view_page,Success,True
1613038187918,2956,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:107 Passed:107 Failed:0
1613038188117,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:108 Passed:108 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.38s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038188311,121,selenium_login:open_login_page,Success,True
1613038189346,951,selenium_login:login_and_view_dashboard,Success,True
1613038189346,1156,selenium_login,Success,True
.test_0_selenium_a_login,Total:109 Passed:109 Failed:0
1613038189889,486,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:110 Passed:110 Failed:0
1613038190756,865,selenium_create_page:open_create_page_editor,Success,True
1613038192052,623,selenium_create_page:save_created_page,Success,True
1613038192053,2161,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:111 Passed:111 Failed:0
1613038193946,1892,selenium_edit_page:open_create_page_editor,Success,True
1613038195345,1377,selenium_edit_page:save_edited_page,Success,True
1613038195345,3291,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:112 Passed:112 Failed:0
1613038196617,815,selenium_create_comment:write_comment,Success,True
1613038197244,626,selenium_create_comment:save_comment,Success,True
1613038197244,1897,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:113 Passed:113 Failed:0
1613038198000,754,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:114 Passed:114 Failed:0
1613038199671,1669,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:115 Passed:115 Failed:0
1613038202854,3182,selenium_app_custom_action:view_page,Success,True
1613038202854,3182,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:116 Passed:116 Failed:0
1613038203051,195,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:117 Passed:117 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.87s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038203226,122,selenium_login:open_login_page,Success,True
1613038204110,802,selenium_login:login_and_view_dashboard,Success,True
1613038204110,1006,selenium_login,Success,True
.test_0_selenium_a_login,Total:118 Passed:118 Failed:0
1613038204506,364,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:119 Passed:119 Failed:0
1613038205269,761,selenium_create_page:open_create_page_editor,Success,True
1613038206555,627,selenium_create_page:save_created_page,Success,True
1613038206556,2048,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:120 Passed:120 Failed:0
1613038208154,1596,selenium_edit_page:open_create_page_editor,Success,True
1613038208898,723,selenium_edit_page:save_edited_page,Success,True
1613038208898,2341,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:121 Passed:121 Failed:0
1613038210045,711,selenium_create_comment:write_comment,Success,True
1613038210665,619,selenium_create_comment:save_comment,Success,True
1613038210665,1765,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:122 Passed:122 Failed:0
1613038211349,682,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:123 Passed:123 Failed:0
1613038213037,1687,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:124 Passed:124 Failed:0
1613038216109,3070,selenium_app_custom_action:view_page,Success,True
1613038216109,3070,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:125 Passed:125 Failed:0
1613038216321,210,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:126 Passed:126 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.23s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038216495,122,selenium_login:open_login_page,Success,True
1613038217420,846,selenium_login:login_and_view_dashboard,Success,True
1613038217420,1048,selenium_login,Success,True
.test_0_selenium_a_login,Total:127 Passed:127 Failed:0
1613038217837,359,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:128 Passed:128 Failed:0
1613038218501,662,selenium_create_page:open_create_page_editor,Success,True
1613038219808,641,selenium_create_page:save_created_page,Success,True
1613038219808,1969,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:129 Passed:129 Failed:0
1613038222429,2620,selenium_edit_page:open_create_page_editor,Success,True
1613038223225,775,selenium_edit_page:save_edited_page,Success,True
1613038223225,3416,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:130 Passed:130 Failed:0
1613038224261,687,selenium_create_comment:write_comment,Success,True
1613038224885,623,selenium_create_comment:save_comment,Success,True
1613038224885,1658,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:131 Passed:131 Failed:0
1613038225488,601,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:132 Passed:132 Failed:0
1613038227313,1823,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:133 Passed:133 Failed:0
1613038230510,3196,selenium_app_custom_action:view_page,Success,True
1613038230510,3196,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:134 Passed:134 Failed:0
1613038230707,195,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:135 Passed:135 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.34s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038230888,124,selenium_login:open_login_page,Success,True
1613038231808,836,selenium_login:login_and_view_dashboard,Success,True
1613038231808,1044,selenium_login,Success,True
.test_0_selenium_a_login,Total:136 Passed:136 Failed:0
1613038232434,569,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:137 Passed:137 Failed:0
1613038233205,769,selenium_create_page:open_create_page_editor,Success,True
1613038234550,666,selenium_create_page:save_created_page,Success,True
1613038234550,2114,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:138 Passed:138 Failed:0
1613038236681,2129,selenium_edit_page:open_create_page_editor,Success,True
1613038237742,1040,selenium_edit_page:save_edited_page,Success,True
1613038237742,3190,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:139 Passed:139 Failed:0
1613038238927,709,selenium_create_comment:write_comment,Success,True
1613038239574,646,selenium_create_comment:save_comment,Success,True
1613038239574,1830,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:140 Passed:140 Failed:0
1613038240250,675,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:141 Passed:141 Failed:0
1613038241975,1723,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:142 Passed:142 Failed:0
1613038245363,3386,selenium_app_custom_action:view_page,Success,True
1613038245363,3386,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:143 Passed:143 Failed:0
1613038245564,199,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:144 Passed:144 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.81s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038245740,124,selenium_login:open_login_page,Success,True
1613038246653,831,selenium_login:login_and_view_dashboard,Success,True
1613038246653,1037,selenium_login,Success,True
.test_0_selenium_a_login,Total:145 Passed:145 Failed:0
1613038247306,623,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:146 Passed:146 Failed:0
1613038248153,845,selenium_create_page:open_create_page_editor,Success,True
1613038249459,639,selenium_create_page:save_created_page,Success,True
1613038249459,2151,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:147 Passed:147 Failed:0
1613038251731,2270,selenium_edit_page:open_create_page_editor,Success,True
1613038252873,1117,selenium_edit_page:save_edited_page,Success,True
1613038252873,3412,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:148 Passed:148 Failed:0
1613038254012,594,selenium_create_comment:write_comment,Success,True
1613038254638,625,selenium_create_comment:save_comment,Success,True
1613038254638,1763,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:149 Passed:149 Failed:0
1613038255321,682,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:150 Passed:150 Failed:0
1613038257026,1702,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:151 Passed:151 Failed:0
1613038260388,3361,selenium_app_custom_action:view_page,Success,True
1613038260388,3361,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:152 Passed:152 Failed:0
1613038260585,195,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:153 Passed:153 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.98s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038260762,124,selenium_login:open_login_page,Success,True
1613038261647,802,selenium_login:login_and_view_dashboard,Success,True
1613038261648,1009,selenium_login,Success,True
.test_0_selenium_a_login,Total:154 Passed:154 Failed:0
1613038262134,462,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:155 Passed:155 Failed:0
1613038262959,823,selenium_create_page:open_create_page_editor,Success,True
1613038264252,657,selenium_create_page:save_created_page,Success,True
1613038264252,2116,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:156 Passed:156 Failed:0
1613038265382,1128,selenium_edit_page:open_create_page_editor,Success,True
1613038266229,788,selenium_edit_page:save_edited_page,Success,True
1613038266230,1975,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:157 Passed:157 Failed:0
1613038267357,689,selenium_create_comment:write_comment,Success,True
1613038267999,641,selenium_create_comment:save_comment,Success,True
1613038268000,1768,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:158 Passed:158 Failed:0
1613038268674,673,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:159 Passed:159 Failed:0
1613038270470,1794,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:160 Passed:160 Failed:0
1613038274062,3590,selenium_app_custom_action:view_page,Success,True
1613038274062,3591,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:161 Passed:161 Failed:0
1613038274264,200,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:162 Passed:162 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.64s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038274438,123,selenium_login:open_login_page,Success,True
1613038275361,840,selenium_login:login_and_view_dashboard,Success,True
1613038275361,1045,selenium_login,Success,True
.test_0_selenium_a_login,Total:163 Passed:163 Failed:0
1613038275901,483,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:164 Passed:164 Failed:0
1613038276635,732,selenium_create_page:open_create_page_editor,Success,True
1613038277990,684,selenium_create_page:save_created_page,Success,True
1613038277990,2088,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:165 Passed:165 Failed:0
1613038279596,1604,selenium_edit_page:open_create_page_editor,Success,True
1613038280557,939,selenium_edit_page:save_edited_page,Success,True
1613038280557,2566,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:166 Passed:166 Failed:0
1613038281722,722,selenium_create_comment:write_comment,Success,True
1613038282361,639,selenium_create_comment:save_comment,Success,True
1613038282361,1802,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:167 Passed:167 Failed:0
1613038282932,569,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:168 Passed:168 Failed:0
1613038284620,1686,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:169 Passed:169 Failed:0
1613038287974,3353,selenium_app_custom_action:view_page,Success,True
1613038287975,3353,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:170 Passed:170 Failed:0
1613038288179,203,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:171 Passed:171 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.87s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038288355,124,selenium_login:open_login_page,Success,True
1613038289297,860,selenium_login:login_and_view_dashboard,Success,True
1613038289298,1067,selenium_login,Success,True
.test_0_selenium_a_login,Total:172 Passed:172 Failed:0
1613038289771,445,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:173 Passed:173 Failed:0
1613038290477,704,selenium_create_page:open_create_page_editor,Success,True
1613038291732,622,selenium_create_page:save_created_page,Success,True
1613038291732,1959,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:174 Passed:174 Failed:0
1613038293301,1567,selenium_edit_page:open_create_page_editor,Success,True
1613038294003,682,selenium_edit_page:save_edited_page,Success,True
1613038294003,2270,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:175 Passed:175 Failed:0
1613038295124,691,selenium_create_comment:write_comment,Success,True
1613038295744,619,selenium_create_comment:save_comment,Success,True
1613038295744,1739,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:176 Passed:176 Failed:0
1613038296349,603,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:177 Passed:177 Failed:0
1613038298094,1743,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:178 Passed:178 Failed:0
1613038301424,3329,selenium_app_custom_action:view_page,Success,True
1613038301424,3329,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:179 Passed:179 Failed:0
1613038301629,203,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:180 Passed:180 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.41s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038301816,134,selenium_login:open_login_page,Success,True
1613038302802,901,selenium_login:login_and_view_dashboard,Success,True
1613038302802,1120,selenium_login,Success,True
.test_0_selenium_a_login,Total:181 Passed:181 Failed:0
1613038303441,580,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:182 Passed:182 Failed:0
1613038304254,811,selenium_create_page:open_create_page_editor,Success,True
1613038305538,659,selenium_create_page:save_created_page,Success,True
1613038305538,2095,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:183 Passed:183 Failed:0
1613038307812,2272,selenium_edit_page:open_create_page_editor,Success,True
1613038308660,826,selenium_edit_page:save_edited_page,Success,True
1613038308661,3121,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:184 Passed:184 Failed:0
1613038309861,727,selenium_create_comment:write_comment,Success,True
1613038310489,628,selenium_create_comment:save_comment,Success,True
1613038310489,1827,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:185 Passed:185 Failed:0
1613038311293,801,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:186 Passed:186 Failed:0
1613038313063,1769,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:187 Passed:187 Failed:0
1613038316715,3650,selenium_app_custom_action:view_page,Success,True
1613038316715,3650,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:188 Passed:188 Failed:0
1613038316918,202,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:189 Passed:189 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.25s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038317106,129,selenium_login:open_login_page,Success,True
1613038318115,925,selenium_login:login_and_view_dashboard,Success,True
1613038318115,1139,selenium_login,Success,True
.test_0_selenium_a_login,Total:190 Passed:190 Failed:0
1613038318709,535,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:191 Passed:191 Failed:0
1613038319438,727,selenium_create_page:open_create_page_editor,Success,True
1613038320715,644,selenium_create_page:save_created_page,Success,True
1613038320716,2005,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:192 Passed:192 Failed:0
1613038323709,2992,selenium_edit_page:open_create_page_editor,Success,True
1613038324699,969,selenium_edit_page:save_edited_page,Success,True
1613038324699,3982,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:193 Passed:193 Failed:0
1613038325923,732,selenium_create_comment:write_comment,Success,True
1613038326554,630,selenium_create_comment:save_comment,Success,True
1613038326554,1852,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:194 Passed:194 Failed:0
1613038327330,775,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:195 Passed:195 Failed:0
1613038329061,1729,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:196 Passed:196 Failed:0
1613038332379,3316,selenium_app_custom_action:view_page,Success,True
1613038332379,3316,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:197 Passed:197 Failed:0
1613038332591,210,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:198 Passed:198 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.62s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038332780,138,selenium_login:open_login_page,Success,True
1613038333773,910,selenium_login:login_and_view_dashboard,Success,True
1613038333773,1131,selenium_login,Success,True
.test_0_selenium_a_login,Total:199 Passed:199 Failed:0
1613038334264,435,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:200 Passed:200 Failed:0
1613038335097,831,selenium_create_page:open_create_page_editor,Success,True
1613038336422,695,selenium_create_page:save_created_page,Success,True
1613038336423,2157,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:201 Passed:201 Failed:0
1613038339085,2661,selenium_edit_page:open_create_page_editor,Success,True
1613038339729,622,selenium_edit_page:save_edited_page,Success,True
1613038339729,3305,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:202 Passed:202 Failed:0
1613038340710,621,selenium_create_comment:write_comment,Success,True
1613038341340,630,selenium_create_comment:save_comment,Success,True
1613038341341,1610,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:203 Passed:203 Failed:0
1613038342856,1513,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:204 Passed:204 Failed:0
1613038344567,1710,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:205 Passed:205 Failed:0
1613038346950,2381,selenium_app_custom_action:view_page,Success,True
1613038346951,2381,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:206 Passed:206 Failed:0
1613038347154,201,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:207 Passed:207 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.52s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038347329,124,selenium_login:open_login_page,Success,True
1613038348380,967,selenium_login:login_and_view_dashboard,Success,True
1613038348380,1175,selenium_login,Success,True
.test_0_selenium_a_login,Total:208 Passed:208 Failed:0
1613038348896,442,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:209 Passed:209 Failed:0
1613038349625,727,selenium_create_page:open_create_page_editor,Success,True
1613038350935,649,selenium_create_page:save_created_page,Success,True
1613038350935,2037,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:210 Passed:210 Failed:0
1613038352482,1546,selenium_edit_page:open_create_page_editor,Success,True
1613038353233,729,selenium_edit_page:save_edited_page,Success,True
1613038353233,2297,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:211 Passed:211 Failed:0
1613038354327,704,selenium_create_comment:write_comment,Success,True
1613038354977,650,selenium_create_comment:save_comment,Success,True
1613038354978,1743,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:212 Passed:212 Failed:0
1613038355589,609,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:213 Passed:213 Failed:0
1613038357366,1776,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:214 Passed:214 Failed:0
1613038360561,3193,selenium_app_custom_action:view_page,Success,True
1613038360561,3193,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:215 Passed:215 Failed:0
1613038360775,212,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:216 Passed:216 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.58s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038360965,136,selenium_login:open_login_page,Success,True
1613038361961,904,selenium_login:login_and_view_dashboard,Success,True
1613038361961,1133,selenium_login,Success,True
.test_0_selenium_a_login,Total:217 Passed:217 Failed:0
1613038362556,535,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:218 Passed:218 Failed:0
1613038363309,751,selenium_create_page:open_create_page_editor,Success,True
1613038364702,749,selenium_create_page:save_created_page,Success,True
1613038364703,2145,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:219 Passed:219 Failed:0
1613038367524,2819,selenium_edit_page:open_create_page_editor,Success,True
1613038368556,1011,selenium_edit_page:save_edited_page,Success,True
1613038368556,3852,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:220 Passed:220 Failed:0
1613038370040,897,selenium_create_comment:write_comment,Success,True
1613038370690,649,selenium_create_comment:save_comment,Success,True
1613038370690,2132,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:221 Passed:221 Failed:0
1613038371352,660,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:222 Passed:222 Failed:0
1613038373219,1865,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:223 Passed:223 Failed:0
1613038375587,2366,selenium_app_custom_action:view_page,Success,True
1613038375587,2367,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:224 Passed:224 Failed:0
1613038375792,202,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:225 Passed:225 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.97s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038375981,129,selenium_login:open_login_page,Success,True
1613038376876,808,selenium_login:login_and_view_dashboard,Success,True
1613038376876,1024,selenium_login,Success,True
.test_0_selenium_a_login,Total:226 Passed:226 Failed:0
1613038377910,1004,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:227 Passed:227 Failed:0
1613038378586,674,selenium_create_page:open_create_page_editor,Success,True
1613038379919,667,selenium_create_page:save_created_page,Success,True
1613038379919,2007,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:228 Passed:228 Failed:0
1613038382582,2661,selenium_edit_page:open_create_page_editor,Success,True
1613038383858,1255,selenium_edit_page:save_edited_page,Success,True
1613038383858,3937,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:229 Passed:229 Failed:0
1613038385464,689,selenium_create_comment:write_comment,Success,True
1613038386091,626,selenium_create_comment:save_comment,Success,True
1613038386091,2231,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:230 Passed:230 Failed:0
1613038387562,1469,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:231 Passed:231 Failed:0
1613038389352,1788,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:232 Passed:232 Failed:0
1613038391934,2581,selenium_app_custom_action:view_page,Success,True
1613038391934,2581,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:233 Passed:233 Failed:0
1613038392136,200,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:234 Passed:234 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 16.29s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038392353,129,selenium_login:open_login_page,Success,True
1613038393240,789,selenium_login:login_and_view_dashboard,Success,True
1613038393240,1017,selenium_login,Success,True
.test_0_selenium_a_login,Total:235 Passed:235 Failed:0
1613038393676,376,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:236 Passed:236 Failed:0
1613038394411,733,selenium_create_page:open_create_page_editor,Success,True
1613038395691,648,selenium_create_page:save_created_page,Success,True
1613038395691,2014,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:237 Passed:237 Failed:0
1613038396745,1052,selenium_edit_page:open_create_page_editor,Success,True
1613038397539,769,selenium_edit_page:save_edited_page,Success,True
1613038397539,1846,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:238 Passed:238 Failed:0
1613038398769,769,selenium_create_comment:write_comment,Success,True
1613038399391,622,selenium_create_comment:save_comment,Success,True
1613038399391,1850,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:239 Passed:239 Failed:0
1613038400001,608,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:240 Passed:240 Failed:0
1613038401733,1730,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:241 Passed:241 Failed:0
1613038404976,3241,selenium_app_custom_action:view_page,Success,True
1613038404976,3241,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:242 Passed:242 Failed:0
1613038405177,200,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:243 Passed:243 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.96s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038405361,132,selenium_login:open_login_page,Success,True
1613038406444,996,selenium_login:login_and_view_dashboard,Success,True
1613038406444,1216,selenium_login,Success,True
.test_0_selenium_a_login,Total:244 Passed:244 Failed:0
1613038406980,477,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:245 Passed:245 Failed:0
1613038407806,824,selenium_create_page:open_create_page_editor,Success,True
1613038409078,634,selenium_create_page:save_created_page,Success,True
1613038409078,2096,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:246 Passed:246 Failed:0
1613038411294,2214,selenium_edit_page:open_create_page_editor,Success,True
1613038412103,788,selenium_edit_page:save_edited_page,Success,True
1613038412103,3023,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:247 Passed:247 Failed:0
1613038413249,685,selenium_create_comment:write_comment,Success,True
1613038413874,624,selenium_create_comment:save_comment,Success,True
1613038413874,1769,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:248 Passed:248 Failed:0
1613038414544,668,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:249 Passed:249 Failed:0
1613038416453,1908,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:250 Passed:250 Failed:0
1613038419665,3210,selenium_app_custom_action:view_page,Success,True
1613038419665,3210,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:251 Passed:251 Failed:0
1613038419862,196,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:252 Passed:252 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.64s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038420043,129,selenium_login:open_login_page,Success,True
1613038421161,1036,selenium_login:login_and_view_dashboard,Success,True
1613038421162,1247,selenium_login,Success,True
.test_0_selenium_a_login,Total:253 Passed:253 Failed:0
1613038422173,954,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:254 Passed:254 Failed:0
1613038422977,802,selenium_create_page:open_create_page_editor,Success,True
1613038424267,646,selenium_create_page:save_created_page,Success,True
1613038424268,2093,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:255 Passed:255 Failed:0
1613038425831,1561,selenium_edit_page:open_create_page_editor,Success,True
1613038427030,1177,selenium_edit_page:save_edited_page,Success,True
1613038427030,2761,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:256 Passed:256 Failed:0
1613038428627,702,selenium_create_comment:write_comment,Success,True
1613038429257,629,selenium_create_comment:save_comment,Success,True
1613038429257,2226,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:257 Passed:257 Failed:0
1613038429907,647,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:258 Passed:258 Failed:0
1613038431632,1724,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:259 Passed:259 Failed:0
1613038434879,3245,selenium_app_custom_action:view_page,Success,True
1613038434879,3245,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:260 Passed:260 Failed:0
1613038435077,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:261 Passed:261 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.17s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038435252,123,selenium_login:open_login_page,Success,True
1613038436203,868,selenium_login:login_and_view_dashboard,Success,True
1613038436203,1074,selenium_login,Success,True
.test_0_selenium_a_login,Total:262 Passed:262 Failed:0
1613038436844,607,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:263 Passed:263 Failed:0
1613038437631,785,selenium_create_page:open_create_page_editor,Success,True
1613038438927,664,selenium_create_page:save_created_page,Success,True
1613038438928,2082,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:264 Passed:264 Failed:0
1613038440680,1751,selenium_edit_page:open_create_page_editor,Success,True
1613038441873,1171,selenium_edit_page:save_edited_page,Success,True
1613038441874,2944,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:265 Passed:265 Failed:0
1613038443226,782,selenium_create_comment:write_comment,Success,True
1613038443863,636,selenium_create_comment:save_comment,Success,True
1613038443863,1988,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:266 Passed:266 Failed:0
1613038444648,783,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:267 Passed:267 Failed:0
1613038446354,1704,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:268 Passed:268 Failed:0
1613038449516,3160,selenium_app_custom_action:view_page,Success,True
1613038449516,3160,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:269 Passed:269 Failed:0
1613038449714,195,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:270 Passed:270 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.59s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038449889,124,selenium_login:open_login_page,Success,True
1613038450945,975,selenium_login:login_and_view_dashboard,Success,True
1613038450945,1180,selenium_login,Success,True
.test_0_selenium_a_login,Total:271 Passed:271 Failed:0
1613038451392,375,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:272 Passed:272 Failed:0
1613038452111,717,selenium_create_page:open_create_page_editor,Success,True
1613038453392,637,selenium_create_page:save_created_page,Success,True
1613038453392,1998,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:273 Passed:273 Failed:0
1613038454989,1595,selenium_edit_page:open_create_page_editor,Success,True
1613038455817,806,selenium_edit_page:save_edited_page,Success,True
1613038455817,2423,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:274 Passed:274 Failed:0
1613038456875,695,selenium_create_comment:write_comment,Success,True
1613038457499,623,selenium_create_comment:save_comment,Success,True
1613038457499,1680,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:275 Passed:275 Failed:0
1613038458119,618,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:276 Passed:276 Failed:0
1613038459888,1768,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:277 Passed:277 Failed:0
1613038463290,3400,selenium_app_custom_action:view_page,Success,True
1613038463290,3400,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:278 Passed:278 Failed:0
1613038463488,196,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:279 Passed:279 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.73s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038463672,125,selenium_login:open_login_page,Success,True
1613038464547,794,selenium_login:login_and_view_dashboard,Success,True
1613038464547,1001,selenium_login,Success,True
.test_0_selenium_a_login,Total:280 Passed:280 Failed:0
1613038465234,629,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:281 Passed:281 Failed:0
1613038466066,830,selenium_create_page:open_create_page_editor,Success,True
1613038467417,714,selenium_create_page:save_created_page,Success,True
1613038467418,2182,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:282 Passed:282 Failed:0
1613038469266,1846,selenium_edit_page:open_create_page_editor,Success,True
1613038470590,1303,selenium_edit_page:save_edited_page,Success,True
1613038470590,3171,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:283 Passed:283 Failed:0
1613038471892,756,selenium_create_comment:write_comment,Success,True
1613038472526,633,selenium_create_comment:save_comment,Success,True
1613038472526,1934,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:284 Passed:284 Failed:0
1613038473272,744,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:285 Passed:285 Failed:0
1613038475043,1770,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:286 Passed:286 Failed:0
1613038478729,3684,selenium_app_custom_action:view_page,Success,True
1613038478729,3684,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:287 Passed:287 Failed:0
1613038478927,196,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:288 Passed:288 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.39s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038479109,123,selenium_login:open_login_page,Success,True
1613038480155,963,selenium_login:login_and_view_dashboard,Success,True
1613038480155,1170,selenium_login,Success,True
.test_0_selenium_a_login,Total:289 Passed:289 Failed:0
1613038480754,567,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:290 Passed:290 Failed:0
1613038481599,844,selenium_create_page:open_create_page_editor,Success,True
1613038482942,659,selenium_create_page:save_created_page,Success,True
1613038482942,2186,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:291 Passed:291 Failed:0
1613038484688,1745,selenium_edit_page:open_create_page_editor,Success,True
1613038485814,1102,selenium_edit_page:save_edited_page,Success,True
1613038485814,2871,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:292 Passed:292 Failed:0
1613038487144,779,selenium_create_comment:write_comment,Success,True
1613038487773,628,selenium_create_comment:save_comment,Success,True
1613038487773,1957,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:293 Passed:293 Failed:0
1613038488528,753,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:294 Passed:294 Failed:0
1613038490262,1732,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:295 Passed:295 Failed:0
1613038493653,3389,selenium_app_custom_action:view_page,Success,True
1613038493653,3390,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:296 Passed:296 Failed:0
1613038493852,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:297 Passed:297 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.88s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038494028,123,selenium_login:open_login_page,Success,True
1613038494910,799,selenium_login:login_and_view_dashboard,Success,True
1613038494910,1005,selenium_login,Success,True
.test_0_selenium_a_login,Total:298 Passed:298 Failed:0
1613038495240,269,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:299 Passed:299 Failed:0
1613038495902,661,selenium_create_page:open_create_page_editor,Success,True
1613038497135,603,selenium_create_page:save_created_page,Success,True
1613038497135,1893,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:300 Passed:300 Failed:0
1613038498714,1577,selenium_edit_page:open_create_page_editor,Success,True
1613038499449,714,selenium_edit_page:save_edited_page,Success,True
1613038499449,2313,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:301 Passed:301 Failed:0
1613038500346,654,selenium_create_comment:write_comment,Success,True
1613038500961,614,selenium_create_comment:save_comment,Success,True
1613038500961,1510,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:302 Passed:302 Failed:0
1613038502461,1499,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:303 Passed:303 Failed:0
1613038504248,1785,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:304 Passed:304 Failed:0
1613038506531,2281,selenium_app_custom_action:view_page,Success,True
1613038506531,2281,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:305 Passed:305 Failed:0
1613038506742,210,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:306 Passed:306 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.85s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038506919,125,selenium_login:open_login_page,Success,True
1613038507853,852,selenium_login:login_and_view_dashboard,Success,True
1613038507854,1059,selenium_login,Success,True
.test_0_selenium_a_login,Total:307 Passed:307 Failed:0
1613038508443,529,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:308 Passed:308 Failed:0
1613038509259,814,selenium_create_page:open_create_page_editor,Success,True
1613038510552,662,selenium_create_page:save_created_page,Success,True
1613038510552,2108,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:309 Passed:309 Failed:0
1613038512368,1814,selenium_edit_page:open_create_page_editor,Success,True
1613038513437,1048,selenium_edit_page:save_edited_page,Success,True
1613038513437,2883,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:310 Passed:310 Failed:0
1613038514701,692,selenium_create_comment:write_comment,Success,True
1613038515318,617,selenium_create_comment:save_comment,Success,True
1613038515318,1880,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:311 Passed:311 Failed:0
1613038515905,585,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:312 Passed:312 Failed:0
1613038517645,1738,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:313 Passed:313 Failed:0
1613038521075,3428,selenium_app_custom_action:view_page,Success,True
1613038521075,3428,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:314 Passed:314 Failed:0
1613038521275,199,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:315 Passed:315 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.49s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038521458,126,selenium_login:open_login_page,Success,True
1613038522435,890,selenium_login:login_and_view_dashboard,Success,True
1613038522435,1103,selenium_login,Success,True
.test_0_selenium_a_login,Total:316 Passed:316 Failed:0
1613038522975,478,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:317 Passed:317 Failed:0
1613038523713,737,selenium_create_page:open_create_page_editor,Success,True
1613038524988,646,selenium_create_page:save_created_page,Success,True
1613038524988,2011,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:318 Passed:318 Failed:0
1613038526553,1563,selenium_edit_page:open_create_page_editor,Success,True
1613038527336,761,selenium_edit_page:save_edited_page,Success,True
1613038527336,2347,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:319 Passed:319 Failed:0
1613038528414,675,selenium_create_comment:write_comment,Success,True
1613038529052,637,selenium_create_comment:save_comment,Success,True
1613038529052,1714,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:320 Passed:320 Failed:0
1613038529644,590,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:321 Passed:321 Failed:0
1613038531381,1734,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:322 Passed:322 Failed:0
1613038534886,3504,selenium_app_custom_action:view_page,Success,True
1613038534886,3504,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:323 Passed:323 Failed:0
1613038535085,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:324 Passed:324 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.76s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038535259,123,selenium_login:open_login_page,Success,True
1613038536248,906,selenium_login:login_and_view_dashboard,Success,True
1613038536248,1112,selenium_login,Success,True
.test_0_selenium_a_login,Total:325 Passed:325 Failed:0
1613038536732,453,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:326 Passed:326 Failed:0
1613038537586,852,selenium_create_page:open_create_page_editor,Success,True
1613038538892,646,selenium_create_page:save_created_page,Success,True
1613038538892,2158,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:327 Passed:327 Failed:0
1613038541683,2788,selenium_edit_page:open_create_page_editor,Success,True
1613038542737,1033,selenium_edit_page:save_edited_page,Success,True
1613038542737,3843,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:328 Passed:328 Failed:0
1613038543816,640,selenium_create_comment:write_comment,Success,True
1613038544439,622,selenium_create_comment:save_comment,Success,True
1613038544439,1700,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:329 Passed:329 Failed:0
1613038545209,768,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:330 Passed:330 Failed:0
1613038546981,1771,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:331 Passed:331 Failed:0
1613038549971,2988,selenium_app_custom_action:view_page,Success,True
1613038549972,2988,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:332 Passed:332 Failed:0
1613038550174,201,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:333 Passed:333 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.05s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038550352,127,selenium_login:open_login_page,Success,True
1613038551233,798,selenium_login:login_and_view_dashboard,Success,True
1613038551233,1008,selenium_login,Success,True
.test_0_selenium_a_login,Total:334 Passed:334 Failed:0
1613038551661,398,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:335 Passed:335 Failed:0
1613038552368,705,selenium_create_page:open_create_page_editor,Success,True
1613038553695,664,selenium_create_page:save_created_page,Success,True
1613038553695,2032,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:336 Passed:336 Failed:0
1613038555304,1606,selenium_edit_page:open_create_page_editor,Success,True
1613038556028,703,selenium_edit_page:save_edited_page,Success,True
1613038556029,2331,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:337 Passed:337 Failed:0
1613038557122,693,selenium_create_comment:write_comment,Success,True
1613038557756,633,selenium_create_comment:save_comment,Success,True
1613038557756,1725,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:338 Passed:338 Failed:0
1613038558396,638,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:339 Passed:339 Failed:0
1613038560182,1783,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:340 Passed:340 Failed:0
1613038563130,2946,selenium_app_custom_action:view_page,Success,True
1613038563130,2946,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:341 Passed:341 Failed:0
1613038563336,204,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:342 Passed:342 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.12s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038563518,130,selenium_login:open_login_page,Success,True
1613038564433,832,selenium_login:login_and_view_dashboard,Success,True
1613038564433,1045,selenium_login,Success,True
.test_0_selenium_a_login,Total:343 Passed:343 Failed:0
1613038564948,456,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:344 Passed:344 Failed:0
1613038565613,664,selenium_create_page:open_create_page_editor,Success,True
1613038566865,624,selenium_create_page:save_created_page,Success,True
1613038566865,1916,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:345 Passed:345 Failed:0
1613038568488,1621,selenium_edit_page:open_create_page_editor,Success,True
1613038569220,710,selenium_edit_page:save_edited_page,Success,True
1613038569220,2353,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:346 Passed:346 Failed:0
1613038570283,635,selenium_create_comment:write_comment,Success,True
1613038570903,619,selenium_create_comment:save_comment,Success,True
1613038570903,1681,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:347 Passed:347 Failed:0
1613038571598,693,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:348 Passed:348 Failed:0
1613038573516,1916,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:349 Passed:349 Failed:0
1613038576895,3377,selenium_app_custom_action:view_page,Success,True
1613038576895,3377,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:350 Passed:350 Failed:0
1613038577093,196,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:351 Passed:351 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.71s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038577277,132,selenium_login:open_login_page,Success,True
1613038578245,883,selenium_login:login_and_view_dashboard,Success,True
1613038578245,1100,selenium_login,Success,True
.test_0_selenium_a_login,Total:352 Passed:352 Failed:0
1613038578662,382,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:353 Passed:353 Failed:0
1613038579398,734,selenium_create_page:open_create_page_editor,Success,True
1613038580647,621,selenium_create_page:save_created_page,Success,True
1613038580648,1984,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:354 Passed:354 Failed:0
1613038583395,2746,selenium_edit_page:open_create_page_editor,Success,True
1613038584102,685,selenium_edit_page:save_edited_page,Success,True
1613038584102,3453,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:355 Passed:355 Failed:0
1613038585153,632,selenium_create_comment:write_comment,Success,True
1613038585788,634,selenium_create_comment:save_comment,Success,True
1613038585788,1684,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:356 Passed:356 Failed:0
1613038586405,616,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:357 Passed:357 Failed:0
1613038588243,1836,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:358 Passed:358 Failed:0
1613038591614,3370,selenium_app_custom_action:view_page,Success,True
1613038591615,3370,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:359 Passed:359 Failed:0
1613038591817,200,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:360 Passed:360 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.68s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038592036,127,selenium_login:open_login_page,Success,True
1613038592968,849,selenium_login:login_and_view_dashboard,Success,True
1613038592968,1060,selenium_login,Success,True
.test_0_selenium_a_login,Total:361 Passed:361 Failed:0
1613038593446,421,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:362 Passed:362 Failed:0
1613038594267,819,selenium_create_page:open_create_page_editor,Success,True
1613038595522,620,selenium_create_page:save_created_page,Success,True
1613038595522,2075,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:363 Passed:363 Failed:0
1613038597102,1578,selenium_edit_page:open_create_page_editor,Success,True
1613038597840,716,selenium_edit_page:save_edited_page,Success,True
1613038597840,2316,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:364 Passed:364 Failed:0
1613038598894,656,selenium_create_comment:write_comment,Success,True
1613038599518,624,selenium_create_comment:save_comment,Success,True
1613038599518,1677,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:365 Passed:365 Failed:0
1613038600248,727,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:366 Passed:366 Failed:0
1613038602095,1846,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:367 Passed:367 Failed:0
1613038605710,3613,selenium_app_custom_action:view_page,Success,True
1613038605710,3613,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:368 Passed:368 Failed:0
1613038605909,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:369 Passed:369 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.01s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038606085,124,selenium_login:open_login_page,Success,True
1613038606967,799,selenium_login:login_and_view_dashboard,Success,True
1613038606967,1006,selenium_login,Success,True
.test_0_selenium_a_login,Total:370 Passed:370 Failed:0
1613038607479,454,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:371 Passed:371 Failed:0
1613038608188,708,selenium_create_page:open_create_page_editor,Success,True
1613038609523,664,selenium_create_page:save_created_page,Success,True
1613038609523,2043,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:372 Passed:372 Failed:0
1613038611072,1547,selenium_edit_page:open_create_page_editor,Success,True
1613038611773,680,selenium_edit_page:save_edited_page,Success,True
1613038611773,2248,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:373 Passed:373 Failed:0
1613038612897,686,selenium_create_comment:write_comment,Success,True
1613038613517,619,selenium_create_comment:save_comment,Success,True
1613038613517,1742,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:374 Passed:374 Failed:0
1613038614914,1395,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:375 Passed:375 Failed:0
1613038616668,1752,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:376 Passed:376 Failed:0
1613038618939,2269,selenium_app_custom_action:view_page,Success,True
1613038618939,2270,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:377 Passed:377 Failed:0
1613038619139,198,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:378 Passed:378 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.19s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613038619314,125,selenium_login:open_login_page,Success,True
1613038620409,1013,selenium_login:login_and_view_dashboard,Success,True
1613038620409,1220,selenium_login,Success,True
.test_0_selenium_a_login,Total:379 Passed:379 Failed:0
1613038620876,433,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:380 Passed:380 Failed:0
1613038621675,797,selenium_create_page:open_create_page_editor,Success,True
1613038622979,660,selenium_create_page:save_created_page,Success,True
1613038622979,2102,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:381 Passed:381 Failed:0
1613038625153,2172,selenium_edit_page:open_create_page_editor,Success,True
1613038625889,714,selenium_edit_page:save_edited_page,Success,True
1613038625889,2908,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:382 Passed:382 Failed:0
1613038626986,692,selenium_create_comment:write_comment,Success,True
1613038627611,624,selenium_create_comment:save_comment,Success,True
1613038627612,1721,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:383 Passed:383 Failed:0
1613038628385,772,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:384 Passed:384 Failed:0
1613038630288,1901,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:385 Passed:385 Failed:0
1613038633533,3244,selenium_app_custom_action:view_page,Success,True
1613038633533,3244,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:386 Passed:386 Failed:0
1613038633736,201,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:387 Passed:387 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.56s =========================
