============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py first driver inits
1613039113397,322,selenium_login:open_login_page,Success,True
1613039114303,824,selenium_login:login_and_view_dashboard,Success,True
1613039114303,1229,selenium_login,Success,True
.test_0_selenium_a_login,Total:1 Passed:1 Failed:0
1613039115410,1074,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:2 Passed:2 Failed:0
1613039116198,786,selenium_create_page:open_create_page_editor,Success,True
1613039117468,634,selenium_create_page:save_created_page,Success,True
1613039117468,2056,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:3 Passed:3 Failed:0
1613039118637,1168,selenium_edit_page:open_create_page_editor,Success,True
1613039119853,1195,selenium_edit_page:save_edited_page,Success,True
1613039119853,2384,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:4 Passed:4 Failed:0
1613039121404,683,selenium_create_comment:write_comment,Success,True
1613039122018,614,selenium_create_comment:save_comment,Success,True
1613039122018,2164,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:5 Passed:5 Failed:0
1613039122749,729,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:6 Passed:6 Failed:0
1613039124417,1666,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:7 Passed:7 Failed:0
1613039126704,2286,selenium_app_custom_action:view_page,Success,True
1613039126704,2286,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:8 Passed:8 Failed:0
1613039126904,198,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:9 Passed:9 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.96s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039127082,124,selenium_login:open_login_page,Success,True
1613039127922,756,selenium_login:login_and_view_dashboard,Success,True
1613039127922,965,selenium_login,Success,True
.test_0_selenium_a_login,Total:10 Passed:10 Failed:0
1613039128522,543,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:11 Passed:11 Failed:0
1613039129238,715,selenium_create_page:open_create_page_editor,Success,True
1613039130525,650,selenium_create_page:save_created_page,Success,True
1613039130525,2001,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:12 Passed:12 Failed:0
1613039132176,1649,selenium_edit_page:open_create_page_editor,Success,True
1613039133128,931,selenium_edit_page:save_edited_page,Success,True
1613039133128,2602,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:13 Passed:13 Failed:0
1613039134371,752,selenium_create_comment:write_comment,Success,True
1613039134982,611,selenium_create_comment:save_comment,Success,True
1613039134982,1852,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:14 Passed:14 Failed:0
1613039136369,1385,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:15 Passed:15 Failed:0
1613039138040,1670,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:16 Passed:16 Failed:0
1613039140935,2893,selenium_app_custom_action:view_page,Success,True
1613039140935,2893,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:17 Passed:17 Failed:0
1613039141131,195,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:18 Passed:18 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.18s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039141311,128,selenium_login:open_login_page,Success,True
1613039142226,833,selenium_login:login_and_view_dashboard,Success,True
1613039142226,1043,selenium_login,Success,True
.test_0_selenium_a_login,Total:19 Passed:19 Failed:0
1613039142686,401,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:20 Passed:20 Failed:0
1613039143443,755,selenium_create_page:open_create_page_editor,Success,True
1613039144694,626,selenium_create_page:save_created_page,Success,True
1613039144694,2007,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:21 Passed:21 Failed:0
1613039147343,2647,selenium_edit_page:open_create_page_editor,Success,True
1613039148072,709,selenium_edit_page:save_edited_page,Success,True
1613039148072,3376,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:22 Passed:22 Failed:0
1613039149118,670,selenium_create_comment:write_comment,Success,True
1613039149749,630,selenium_create_comment:save_comment,Success,True
1613039149749,1674,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:23 Passed:23 Failed:0
1613039150508,758,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:24 Passed:24 Failed:0
1613039152202,1692,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:25 Passed:25 Failed:0
1613039154957,2753,selenium_app_custom_action:view_page,Success,True
1613039154957,2753,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:26 Passed:26 Failed:0
1613039155163,204,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:27 Passed:27 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.99s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039155336,122,selenium_login:open_login_page,Success,True
1613039156260,842,selenium_login:login_and_view_dashboard,Success,True
1613039156260,1046,selenium_login,Success,True
.test_0_selenium_a_login,Total:28 Passed:28 Failed:0
1613039156722,404,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:29 Passed:29 Failed:0
1613039157433,709,selenium_create_page:open_create_page_editor,Success,True
1613039158729,624,selenium_create_page:save_created_page,Success,True
1613039158729,2005,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:30 Passed:30 Failed:0
1613039159750,1020,selenium_edit_page:open_create_page_editor,Success,True
1613039160503,725,selenium_edit_page:save_edited_page,Success,True
1613039160503,1773,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:31 Passed:31 Failed:0
1613039161582,675,selenium_create_comment:write_comment,Success,True
1613039162197,615,selenium_create_comment:save_comment,Success,True
1613039162197,1692,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:32 Passed:32 Failed:0
1613039162885,686,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:33 Passed:33 Failed:0
1613039164576,1689,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:34 Passed:34 Failed:0
1613039167268,2690,selenium_app_custom_action:view_page,Success,True
1613039167268,2690,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:35 Passed:35 Failed:0
1613039167462,192,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:36 Passed:36 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.26s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039167637,122,selenium_login:open_login_page,Success,True
1613039168535,816,selenium_login:login_and_view_dashboard,Success,True
1613039168535,1020,selenium_login,Success,True
.test_0_selenium_a_login,Total:37 Passed:37 Failed:0
1613039169536,942,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:38 Passed:38 Failed:0
1613039170327,789,selenium_create_page:open_create_page_editor,Success,True
1613039171566,605,selenium_create_page:save_created_page,Success,True
1613039171566,2028,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:39 Passed:39 Failed:0
1613039173108,1540,selenium_edit_page:open_create_page_editor,Success,True
1613039174346,1218,selenium_edit_page:save_edited_page,Success,True
1613039174346,2779,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:40 Passed:40 Failed:0
1613039175972,711,selenium_create_comment:write_comment,Success,True
1613039176599,627,selenium_create_comment:save_comment,Success,True
1613039176600,2251,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:41 Passed:41 Failed:0
1613039177278,676,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:42 Passed:42 Failed:0
1613039178950,1671,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:43 Passed:43 Failed:0
1613039181835,2883,selenium_app_custom_action:view_page,Success,True
1613039181835,2883,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:44 Passed:44 Failed:0
1613039182037,200,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:45 Passed:45 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.53s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039182218,127,selenium_login:open_login_page,Success,True
1613039183169,866,selenium_login:login_and_view_dashboard,Success,True
1613039183169,1078,selenium_login,Success,True
.test_0_selenium_a_login,Total:46 Passed:46 Failed:0
1613039183622,388,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:47 Passed:47 Failed:0
1613039184422,798,selenium_create_page:open_create_page_editor,Success,True
1613039185657,605,selenium_create_page:save_created_page,Success,True
1613039185657,2034,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:48 Passed:48 Failed:0
1613039188262,2603,selenium_edit_page:open_create_page_editor,Success,True
1613039189043,759,selenium_edit_page:save_edited_page,Success,True
1613039189043,3384,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:49 Passed:49 Failed:0
1613039190127,672,selenium_create_comment:write_comment,Success,True
1613039190758,630,selenium_create_comment:save_comment,Success,True
1613039190758,1714,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:50 Passed:50 Failed:0
1613039191341,581,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:51 Passed:51 Failed:0
1613039193020,1678,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:52 Passed:52 Failed:0
1613039195977,2955,selenium_app_custom_action:view_page,Success,True
1613039195977,2955,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:53 Passed:53 Failed:0
1613039196182,203,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:54 Passed:54 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.10s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039196361,127,selenium_login:open_login_page,Success,True
1613039197246,797,selenium_login:login_and_view_dashboard,Success,True
1613039197246,1011,selenium_login,Success,True
.test_0_selenium_a_login,Total:55 Passed:55 Failed:0
1613039197767,491,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:56 Passed:56 Failed:0
1613039198468,699,selenium_create_page:open_create_page_editor,Success,True
1613039199747,645,selenium_create_page:save_created_page,Success,True
1613039199747,1978,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:57 Passed:57 Failed:0
1613039202739,2990,selenium_edit_page:open_create_page_editor,Success,True
1613039203664,904,selenium_edit_page:save_edited_page,Success,True
1613039203664,3915,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:58 Passed:58 Failed:0
1613039204562,379,selenium_create_comment:write_comment,Success,True
1613039205182,620,selenium_create_comment:save_comment,Success,True
1613039205182,1516,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:59 Passed:59 Failed:0
1613039205750,565,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:60 Passed:60 Failed:0
1613039207428,1676,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:61 Passed:61 Failed:0
1613039209936,2507,selenium_app_custom_action:view_page,Success,True
1613039209936,2507,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:62 Passed:62 Failed:0
1613039210132,194,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:63 Passed:63 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.91s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039210307,122,selenium_login:open_login_page,Success,True
1613039211202,814,selenium_login:login_and_view_dashboard,Success,True
1613039211202,1017,selenium_login,Success,True
.test_0_selenium_a_login,Total:64 Passed:64 Failed:0
1613039211736,506,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:65 Passed:65 Failed:0
1613039212560,822,selenium_create_page:open_create_page_editor,Success,True
1613039213897,698,selenium_create_page:save_created_page,Success,True
1613039213897,2160,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:66 Passed:66 Failed:0
1613039216823,2923,selenium_edit_page:open_create_page_editor,Success,True
1613039217777,934,selenium_edit_page:save_edited_page,Success,True
1613039217778,3878,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:67 Passed:67 Failed:0
1613039219072,765,selenium_create_comment:write_comment,Success,True
1613039219701,628,selenium_create_comment:save_comment,Success,True
1613039219701,1921,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:68 Passed:68 Failed:0
1613039220345,642,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:69 Passed:69 Failed:0
1613039222026,1678,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:70 Passed:70 Failed:0
1613039224710,2682,selenium_app_custom_action:view_page,Success,True
1613039224710,2683,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:71 Passed:71 Failed:0
1613039224912,200,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:72 Passed:72 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.74s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039225084,121,selenium_login:open_login_page,Success,True
1613039225996,829,selenium_login:login_and_view_dashboard,Success,True
1613039225996,1033,selenium_login,Success,True
.test_0_selenium_a_login,Total:73 Passed:73 Failed:0
1613039226949,922,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:74 Passed:74 Failed:0
1613039227722,771,selenium_create_page:open_create_page_editor,Success,True
1613039229008,615,selenium_create_page:save_created_page,Success,True
1613039229008,2057,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:75 Passed:75 Failed:0
1613039230643,1633,selenium_edit_page:open_create_page_editor,Success,True
1613039231869,1204,selenium_edit_page:save_edited_page,Success,True
1613039231869,2860,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:76 Passed:76 Failed:0
1613039233483,689,selenium_create_comment:write_comment,Success,True
1613039234104,620,selenium_create_comment:save_comment,Success,True
1613039234104,2233,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:77 Passed:77 Failed:0
1613039234832,727,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:78 Passed:78 Failed:0
1613039236508,1674,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:79 Passed:79 Failed:0
1613039239135,2625,selenium_app_custom_action:view_page,Success,True
1613039239136,2626,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:80 Passed:80 Failed:0
1613039239333,195,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:81 Passed:81 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.38s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039239513,121,selenium_login:open_login_page,Success,True
1613039240432,836,selenium_login:login_and_view_dashboard,Success,True
1613039240432,1040,selenium_login,Success,True
.test_0_selenium_a_login,Total:82 Passed:82 Failed:0
1613039240885,395,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:83 Passed:83 Failed:0
1613039241609,722,selenium_create_page:open_create_page_editor,Success,True
1613039242898,652,selenium_create_page:save_created_page,Success,True
1613039242898,2011,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:84 Passed:84 Failed:0
1613039243919,1019,selenium_edit_page:open_create_page_editor,Success,True
1613039244720,778,selenium_edit_page:save_edited_page,Success,True
1613039244720,1820,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:85 Passed:85 Failed:0
1613039245820,699,selenium_create_comment:write_comment,Success,True
1613039246445,624,selenium_create_comment:save_comment,Success,True
1613039246445,1723,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:86 Passed:86 Failed:0
1613039247125,678,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:87 Passed:87 Failed:0
1613039248862,1735,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:88 Passed:88 Failed:0
1613039251988,3125,selenium_app_custom_action:view_page,Success,True
1613039251989,3125,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:89 Passed:89 Failed:0
1613039252184,193,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:90 Passed:90 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.80s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039252356,120,selenium_login:open_login_page,Success,True
1613039253253,815,selenium_login:login_and_view_dashboard,Success,True
1613039253253,1018,selenium_login,Success,True
.test_0_selenium_a_login,Total:91 Passed:91 Failed:0
1613039253769,459,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:92 Passed:92 Failed:0
1613039254538,767,selenium_create_page:open_create_page_editor,Success,True
1613039255841,633,selenium_create_page:save_created_page,Success,True
1613039255841,2071,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:93 Passed:93 Failed:0
1613039257424,1581,selenium_edit_page:open_create_page_editor,Success,True
1613039258110,663,selenium_edit_page:save_edited_page,Success,True
1613039258110,2267,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:94 Passed:94 Failed:0
1613039259143,567,selenium_create_comment:write_comment,Success,True
1613039259763,620,selenium_create_comment:save_comment,Success,True
1613039259764,1652,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:95 Passed:95 Failed:0
1613039260426,661,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:96 Passed:96 Failed:0
1613039262147,1719,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:97 Passed:97 Failed:0
1613039264048,1899,selenium_app_custom_action:view_page,Success,True
1613039264048,1899,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:98 Passed:98 Failed:0
1613039264255,206,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:99 Passed:99 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.03s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039264439,123,selenium_login:open_login_page,Success,True
1613039265303,782,selenium_login:login_and_view_dashboard,Success,True
1613039265303,987,selenium_login,Success,True
.test_0_selenium_a_login,Total:100 Passed:100 Failed:0
1613039265840,474,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:101 Passed:101 Failed:0
1613039266656,814,selenium_create_page:open_create_page_editor,Success,True
1613039267987,696,selenium_create_page:save_created_page,Success,True
1613039267987,2146,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:102 Passed:102 Failed:0
1613039269541,1552,selenium_edit_page:open_create_page_editor,Success,True
1613039270237,672,selenium_edit_page:save_edited_page,Success,True
1613039270237,2248,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:103 Passed:103 Failed:0
1613039271249,619,selenium_create_comment:write_comment,Success,True
1613039271904,654,selenium_create_comment:save_comment,Success,True
1613039271904,1666,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:104 Passed:104 Failed:0
1613039272494,588,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:105 Passed:105 Failed:0
1613039274328,1833,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:106 Passed:106 Failed:0
1613039277264,2934,selenium_app_custom_action:view_page,Success,True
1613039277264,2934,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:107 Passed:107 Failed:0
1613039277467,201,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:108 Passed:108 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.16s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039277677,127,selenium_login:open_login_page,Success,True
1613039278650,889,selenium_login:login_and_view_dashboard,Success,True
1613039278650,1101,selenium_login,Success,True
.test_0_selenium_a_login,Total:109 Passed:109 Failed:0
1613039279130,423,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:110 Passed:110 Failed:0
1613039279958,825,selenium_create_page:open_create_page_editor,Success,True
1613039281257,670,selenium_create_page:save_created_page,Success,True
1613039281258,2125,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:111 Passed:111 Failed:0
1613039282848,1589,selenium_edit_page:open_create_page_editor,Success,True
1613039283572,703,selenium_edit_page:save_edited_page,Success,True
1613039283572,2313,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:112 Passed:112 Failed:0
1613039284626,630,selenium_create_comment:write_comment,Success,True
1613039285264,637,selenium_create_comment:save_comment,Success,True
1613039285264,1690,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:113 Passed:113 Failed:0
1613039286054,788,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:114 Passed:114 Failed:0
1613039287931,1876,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:115 Passed:115 Failed:0
1613039290920,2987,selenium_app_custom_action:view_page,Success,True
1613039290920,2987,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:116 Passed:116 Failed:0
1613039291117,196,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:117 Passed:117 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.58s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039291301,124,selenium_login:open_login_page,Success,True
1613039292199,816,selenium_login:login_and_view_dashboard,Success,True
1613039292199,1022,selenium_login,Success,True
.test_0_selenium_a_login,Total:118 Passed:118 Failed:0
1613039292823,594,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:119 Passed:119 Failed:0
1613039293552,727,selenium_create_page:open_create_page_editor,Success,True
1613039294861,638,selenium_create_page:save_created_page,Success,True
1613039294861,2037,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:120 Passed:120 Failed:0
1613039297585,2722,selenium_edit_page:open_create_page_editor,Success,True
1613039298407,800,selenium_edit_page:save_edited_page,Success,True
1613039298407,3544,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:121 Passed:121 Failed:0
1613039299257,333,selenium_create_comment:write_comment,Success,True
1613039299887,629,selenium_create_comment:save_comment,Success,True
1613039299887,1478,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:122 Passed:122 Failed:0
1613039300514,625,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:123 Passed:123 Failed:0
1613039302197,1682,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:124 Passed:124 Failed:0
1613039304699,2500,selenium_app_custom_action:view_page,Success,True
1613039304699,2500,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:125 Passed:125 Failed:0
1613039304894,194,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:126 Passed:126 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.73s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039305072,126,selenium_login:open_login_page,Success,True
1613039305905,750,selenium_login:login_and_view_dashboard,Success,True
1613039305905,959,selenium_login,Success,True
.test_0_selenium_a_login,Total:127 Passed:127 Failed:0
1613039306486,521,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:128 Passed:128 Failed:0
1613039307348,860,selenium_create_page:open_create_page_editor,Success,True
1613039308638,631,selenium_create_page:save_created_page,Success,True
1613039308638,2150,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:129 Passed:129 Failed:0
1613039310353,1713,selenium_edit_page:open_create_page_editor,Success,True
1613039312012,1639,selenium_edit_page:save_edited_page,Success,True
1613039312012,3373,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:130 Passed:130 Failed:0
1613039313414,889,selenium_create_comment:write_comment,Success,True
1613039314053,638,selenium_create_comment:save_comment,Success,True
1613039314053,2039,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:131 Passed:131 Failed:0
1613039314724,669,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:132 Passed:132 Failed:0
1613039316470,1744,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:133 Passed:133 Failed:0
1613039319143,2672,selenium_app_custom_action:view_page,Success,True
1613039319144,2672,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:134 Passed:134 Failed:0
1613039319357,211,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:135 Passed:135 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.42s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039319541,132,selenium_login:open_login_page,Success,True
1613039320565,943,selenium_login:login_and_view_dashboard,Success,True
1613039320565,1156,selenium_login,Success,True
.test_0_selenium_a_login,Total:136 Passed:136 Failed:0
1613039321048,419,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:137 Passed:137 Failed:0
1613039321797,747,selenium_create_page:open_create_page_editor,Success,True
1613039323040,617,selenium_create_page:save_created_page,Success,True
1613039323040,1991,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:138 Passed:138 Failed:0
1613039324627,1585,selenium_edit_page:open_create_page_editor,Success,True
1613039325363,715,selenium_edit_page:save_edited_page,Success,True
1613039325363,2321,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:139 Passed:139 Failed:0
1613039326468,737,selenium_create_comment:write_comment,Success,True
1613039327095,626,selenium_create_comment:save_comment,Success,True
1613039327095,1731,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:140 Passed:140 Failed:0
1613039327688,590,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:141 Passed:141 Failed:0
1613039329396,1707,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:142 Passed:142 Failed:0
1613039332316,2918,selenium_app_custom_action:view_page,Success,True
1613039332316,2918,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:143 Passed:143 Failed:0
1613039332512,193,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:144 Passed:144 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.11s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039332695,124,selenium_login:open_login_page,Success,True
1613039333577,799,selenium_login:login_and_view_dashboard,Success,True
1613039333578,1006,selenium_login,Success,True
.test_0_selenium_a_login,Total:145 Passed:145 Failed:0
1613039333988,355,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:146 Passed:146 Failed:0
1613039334685,695,selenium_create_page:open_create_page_editor,Success,True
1613039335983,627,selenium_create_page:save_created_page,Success,True
1613039335983,1993,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:147 Passed:147 Failed:0
1613039338077,2092,selenium_edit_page:open_create_page_editor,Success,True
1613039338861,760,selenium_edit_page:save_edited_page,Success,True
1613039338862,2877,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:148 Passed:148 Failed:0
1613039339901,668,selenium_create_comment:write_comment,Success,True
1613039340527,626,selenium_create_comment:save_comment,Success,True
1613039340527,1664,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:149 Passed:149 Failed:0
1613039341222,693,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:150 Passed:150 Failed:0
1613039342927,1703,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:151 Passed:151 Failed:0
1613039345698,2770,selenium_app_custom_action:view_page,Success,True
1613039345698,2770,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:152 Passed:152 Failed:0
1613039345904,204,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:153 Passed:153 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.34s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039346085,128,selenium_login:open_login_page,Success,True
1613039347083,915,selenium_login:login_and_view_dashboard,Success,True
1613039347083,1127,selenium_login,Success,True
.test_0_selenium_a_login,Total:154 Passed:154 Failed:0
1613039347565,453,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:155 Passed:155 Failed:0
1613039348268,700,selenium_create_page:open_create_page_editor,Success,True
1613039349614,715,selenium_create_page:save_created_page,Success,True
1613039349614,2047,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:156 Passed:156 Failed:0
1613039351233,1617,selenium_edit_page:open_create_page_editor,Success,True
1613039351965,711,selenium_edit_page:save_edited_page,Success,True
1613039351965,2349,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:157 Passed:157 Failed:0
1613039353050,705,selenium_create_comment:write_comment,Success,True
1613039353691,641,selenium_create_comment:save_comment,Success,True
1613039353692,1724,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:158 Passed:158 Failed:0
1613039354448,755,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:159 Passed:159 Failed:0
1613039356174,1724,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:160 Passed:160 Failed:0
1613039358439,2262,selenium_app_custom_action:view_page,Success,True
1613039358439,2263,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:161 Passed:161 Failed:0
1613039358674,234,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:162 Passed:162 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.73s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039358854,128,selenium_login:open_login_page,Success,True
1613039359847,909,selenium_login:login_and_view_dashboard,Success,True
1613039359847,1121,selenium_login,Success,True
.test_0_selenium_a_login,Total:163 Passed:163 Failed:0
1613039360279,405,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:164 Passed:164 Failed:0
1613039361043,762,selenium_create_page:open_create_page_editor,Success,True
1613039362312,642,selenium_create_page:save_created_page,Success,True
1613039362312,2031,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:165 Passed:165 Failed:0
1613039363888,1574,selenium_edit_page:open_create_page_editor,Success,True
1613039364548,639,selenium_edit_page:save_edited_page,Success,True
1613039364549,2235,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:166 Passed:166 Failed:0
1613039365682,722,selenium_create_comment:write_comment,Success,True
1613039366291,609,selenium_create_comment:save_comment,Success,True
1613039366291,1741,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:167 Passed:167 Failed:0
1613039366909,616,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:168 Passed:168 Failed:0
1613039368838,1927,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:169 Passed:169 Failed:0
1613039371585,2746,selenium_app_custom_action:view_page,Success,True
1613039371585,2746,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:170 Passed:170 Failed:0
1613039371788,201,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:171 Passed:171 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.07s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039371962,123,selenium_login:open_login_page,Success,True
1613039372948,905,selenium_login:login_and_view_dashboard,Success,True
1613039372949,1109,selenium_login,Success,True
.test_0_selenium_a_login,Total:172 Passed:172 Failed:0
1613039373405,398,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:173 Passed:173 Failed:0
1613039374114,707,selenium_create_page:open_create_page_editor,Success,True
1613039375442,662,selenium_create_page:save_created_page,Success,True
1613039375442,2035,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:174 Passed:174 Failed:0
1613039377049,1606,selenium_edit_page:open_create_page_editor,Success,True
1613039377709,638,selenium_edit_page:save_edited_page,Success,True
1613039377710,2266,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:175 Passed:175 Failed:0
1613039378853,651,selenium_create_comment:write_comment,Success,True
1613039379472,618,selenium_create_comment:save_comment,Success,True
1613039379472,1761,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:176 Passed:176 Failed:0
1613039380234,760,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:177 Passed:177 Failed:0
1613039382062,1827,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:178 Passed:178 Failed:0
1613039386680,4616,selenium_app_custom_action:view_page,Success,True
1613039386680,4617,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:179 Passed:179 Failed:0
1613039386887,205,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:180 Passed:180 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.06s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039387069,129,selenium_login:open_login_page,Success,True
1613039388063,893,selenium_login:login_and_view_dashboard,Success,True
1613039388063,1123,selenium_login,Success,True
.test_0_selenium_a_login,Total:181 Passed:181 Failed:0
1613039388716,598,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:182 Passed:182 Failed:0
1613039389545,827,selenium_create_page:open_create_page_editor,Success,True
1613039390791,614,selenium_create_page:save_created_page,Success,True
1613039390791,2073,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:183 Passed:183 Failed:0
1613039392552,1759,selenium_edit_page:open_create_page_editor,Success,True
1613039393781,1203,selenium_edit_page:save_edited_page,Success,True
1613039393781,2989,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:184 Passed:184 Failed:0
1613039395154,773,selenium_create_comment:write_comment,Success,True
1613039395782,627,selenium_create_comment:save_comment,Success,True
1613039395782,1999,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:185 Passed:185 Failed:0
1613039396391,607,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:186 Passed:186 Failed:0
1613039398246,1853,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:187 Passed:187 Failed:0
1613039401601,3353,selenium_app_custom_action:view_page,Success,True
1613039401601,3353,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:188 Passed:188 Failed:0
1613039401800,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:189 Passed:189 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.87s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039401989,138,selenium_login:open_login_page,Success,True
1613039403047,977,selenium_login:login_and_view_dashboard,Success,True
1613039403047,1196,selenium_login,Success,True
.test_0_selenium_a_login,Total:190 Passed:190 Failed:0
1613039404121,1011,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:191 Passed:191 Failed:0
1613039404840,717,selenium_create_page:open_create_page_editor,Success,True
1613039406146,670,selenium_create_page:save_created_page,Success,True
1613039406146,2023,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:192 Passed:192 Failed:0
1613039407774,1627,selenium_edit_page:open_create_page_editor,Success,True
1613039408972,1176,selenium_edit_page:save_edited_page,Success,True
1613039408972,2824,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:193 Passed:193 Failed:0
1613039410546,701,selenium_create_comment:write_comment,Success,True
1613039411189,642,selenium_create_comment:save_comment,Success,True
1613039411189,2215,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:194 Passed:194 Failed:0
1613039411883,693,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:195 Passed:195 Failed:0
1613039413801,1915,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:196 Passed:196 Failed:0
1613039417242,3439,selenium_app_custom_action:view_page,Success,True
1613039417242,3439,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:197 Passed:197 Failed:0
1613039417437,193,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:198 Passed:198 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.59s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039417614,124,selenium_login:open_login_page,Success,True
1613039418594,899,selenium_login:login_and_view_dashboard,Success,True
1613039418594,1105,selenium_login,Success,True
.test_0_selenium_a_login,Total:199 Passed:199 Failed:0
1613039419094,467,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:200 Passed:200 Failed:0
1613039419941,844,selenium_create_page:open_create_page_editor,Success,True
1613039421287,713,selenium_create_page:save_created_page,Success,True
1613039421287,2190,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:201 Passed:201 Failed:0
1613039423049,1761,selenium_edit_page:open_create_page_editor,Success,True
1613039424386,1312,selenium_edit_page:save_edited_page,Success,True
1613039424386,3097,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:202 Passed:202 Failed:0
1613039425714,756,selenium_create_comment:write_comment,Success,True
1613039426346,631,selenium_create_comment:save_comment,Success,True
1613039426346,1958,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:203 Passed:203 Failed:0
1613039427151,804,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:204 Passed:204 Failed:0
1613039428913,1759,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:205 Passed:205 Failed:0
1613039431621,2706,selenium_app_custom_action:view_page,Success,True
1613039431621,2706,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:206 Passed:206 Failed:0
1613039431824,202,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:207 Passed:207 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.34s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039432007,132,selenium_login:open_login_page,Success,True
1613039433058,968,selenium_login:login_and_view_dashboard,Success,True
1613039433058,1183,selenium_login,Success,True
.test_0_selenium_a_login,Total:208 Passed:208 Failed:0
1613039433623,536,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:209 Passed:209 Failed:0
1613039434315,690,selenium_create_page:open_create_page_editor,Success,True
1613039435638,674,selenium_create_page:save_created_page,Success,True
1613039435638,2013,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:210 Passed:210 Failed:0
1613039437841,2202,selenium_edit_page:open_create_page_editor,Success,True
1613039438673,810,selenium_edit_page:save_edited_page,Success,True
1613039438673,3034,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:211 Passed:211 Failed:0
1613039439747,634,selenium_create_comment:write_comment,Success,True
1613039440390,642,selenium_create_comment:save_comment,Success,True
1613039440390,1714,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:212 Passed:212 Failed:0
1613039441216,825,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:213 Passed:213 Failed:0
1613039443095,1877,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:214 Passed:214 Failed:0
1613039445762,2665,selenium_app_custom_action:view_page,Success,True
1613039445762,2665,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:215 Passed:215 Failed:0
1613039445967,204,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:216 Passed:216 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.10s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039446150,130,selenium_login:open_login_page,Success,True
1613039447144,909,selenium_login:login_and_view_dashboard,Success,True
1613039447144,1124,selenium_login,Success,True
.test_0_selenium_a_login,Total:217 Passed:217 Failed:0
1613039447568,366,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:218 Passed:218 Failed:0
1613039448281,711,selenium_create_page:open_create_page_editor,Success,True
1613039449602,657,selenium_create_page:save_created_page,Success,True
1613039449603,2033,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:219 Passed:219 Failed:0
1613039451188,1584,selenium_edit_page:open_create_page_editor,Success,True
1613039451924,714,selenium_edit_page:save_edited_page,Success,True
1613039451924,2320,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:220 Passed:220 Failed:0
1613039452971,673,selenium_create_comment:write_comment,Success,True
1613039453603,632,selenium_create_comment:save_comment,Success,True
1613039453604,1678,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:221 Passed:221 Failed:0
1613039454293,688,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:222 Passed:222 Failed:0
1613039455993,1698,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:223 Passed:223 Failed:0
1613039459501,3506,selenium_app_custom_action:view_page,Success,True
1613039459502,3507,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:224 Passed:224 Failed:0
1613039459698,194,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:225 Passed:225 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.69s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039459881,124,selenium_login:open_login_page,Success,True
1613039460785,824,selenium_login:login_and_view_dashboard,Success,True
1613039460785,1028,selenium_login,Success,True
.test_0_selenium_a_login,Total:226 Passed:226 Failed:0
1613039461269,449,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:227 Passed:227 Failed:0
1613039462038,767,selenium_create_page:open_create_page_editor,Success,True
1613039463354,679,selenium_create_page:save_created_page,Success,True
1613039463354,2083,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:228 Passed:228 Failed:0
1613039464939,1584,selenium_edit_page:open_create_page_editor,Success,True
1613039465651,690,selenium_edit_page:save_edited_page,Success,True
1613039465651,2296,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:229 Passed:229 Failed:0
1613039466839,742,selenium_create_comment:write_comment,Success,True
1613039467459,619,selenium_create_comment:save_comment,Success,True
1613039467459,1806,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:230 Passed:230 Failed:0
1613039468138,677,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:231 Passed:231 Failed:0
1613039469932,1792,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:232 Passed:232 Failed:0
1613039473416,3482,selenium_app_custom_action:view_page,Success,True
1613039473416,3482,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:233 Passed:233 Failed:0
1613039473610,192,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:234 Passed:234 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.86s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039473818,128,selenium_login:open_login_page,Success,True
1613039474756,857,selenium_login:login_and_view_dashboard,Success,True
1613039474757,1067,selenium_login,Success,True
.test_0_selenium_a_login,Total:235 Passed:235 Failed:0
1613039475281,466,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:236 Passed:236 Failed:0
1613039475993,710,selenium_create_page:open_create_page_editor,Success,True
1613039477357,680,selenium_create_page:save_created_page,Success,True
1613039477358,2075,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:237 Passed:237 Failed:0
1613039478936,1577,selenium_edit_page:open_create_page_editor,Success,True
1613039479719,762,selenium_edit_page:save_edited_page,Success,True
1613039479720,2360,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:238 Passed:238 Failed:0
1613039480872,696,selenium_create_comment:write_comment,Success,True
1613039481517,645,selenium_create_comment:save_comment,Success,True
1613039481518,1796,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:239 Passed:239 Failed:0
1613039482126,606,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:240 Passed:240 Failed:0
1613039483863,1735,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:241 Passed:241 Failed:0
1613039487214,3350,selenium_app_custom_action:view_page,Success,True
1613039487214,3350,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:242 Passed:242 Failed:0
1613039487418,202,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:243 Passed:243 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.74s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039487601,131,selenium_login:open_login_page,Success,True
1613039488534,849,selenium_login:login_and_view_dashboard,Success,True
1613039488534,1064,selenium_login,Success,True
.test_0_selenium_a_login,Total:244 Passed:244 Failed:0
1613039489020,460,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:245 Passed:245 Failed:0
1613039489732,710,selenium_create_page:open_create_page_editor,Success,True
1613039491043,642,selenium_create_page:save_created_page,Success,True
1613039491043,2021,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:246 Passed:246 Failed:0
1613039492604,1559,selenium_edit_page:open_create_page_editor,Success,True
1613039493322,696,selenium_edit_page:save_edited_page,Success,True
1613039493322,2277,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:247 Passed:247 Failed:0
1613039494496,697,selenium_create_comment:write_comment,Success,True
1613039495149,652,selenium_create_comment:save_comment,Success,True
1613039495149,1825,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:248 Passed:248 Failed:0
1613039495757,607,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:249 Passed:249 Failed:0
1613039497538,1778,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:250 Passed:250 Failed:0
1613039500308,2769,selenium_app_custom_action:view_page,Success,True
1613039500308,2769,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:251 Passed:251 Failed:0
1613039500510,201,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:252 Passed:252 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.05s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039500690,128,selenium_login:open_login_page,Success,True
1613039501732,957,selenium_login:login_and_view_dashboard,Success,True
1613039501732,1171,selenium_login,Success,True
.test_0_selenium_a_login,Total:253 Passed:253 Failed:0
1613039502991,1243,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:254 Passed:254 Failed:0
1613039503687,694,selenium_create_page:open_create_page_editor,Success,True
1613039504957,642,selenium_create_page:save_created_page,Success,True
1613039504957,1963,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:255 Passed:255 Failed:0
1613039506033,1075,selenium_edit_page:open_create_page_editor,Success,True
1613039507294,1239,selenium_edit_page:save_edited_page,Success,True
1613039507294,2335,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:256 Passed:256 Failed:0
1613039508837,700,selenium_create_comment:write_comment,Success,True
1613039509477,639,selenium_create_comment:save_comment,Success,True
1613039509477,2181,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:257 Passed:257 Failed:0
1613039510146,667,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:258 Passed:258 Failed:0
1613039512108,1960,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:259 Passed:259 Failed:0
1613039514810,2700,selenium_app_custom_action:view_page,Success,True
1613039514810,2700,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:260 Passed:260 Failed:0
1613039515011,200,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:261 Passed:261 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.46s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039515188,124,selenium_login:open_login_page,Success,True
1613039516243,974,selenium_login:login_and_view_dashboard,Success,True
1613039516244,1180,selenium_login,Success,True
.test_0_selenium_a_login,Total:262 Passed:262 Failed:0
1613039516784,484,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:263 Passed:263 Failed:0
1613039517469,683,selenium_create_page:open_create_page_editor,Success,True
1613039518755,637,selenium_create_page:save_created_page,Success,True
1613039518756,1970,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:264 Passed:264 Failed:0
1613039520404,1647,selenium_edit_page:open_create_page_editor,Success,True
1613039521222,794,selenium_edit_page:save_edited_page,Success,True
1613039521222,2465,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:265 Passed:265 Failed:0
1613039522308,679,selenium_create_comment:write_comment,Success,True
1613039522926,617,selenium_create_comment:save_comment,Success,True
1613039522926,1701,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:266 Passed:266 Failed:0
1613039524479,1552,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:267 Passed:267 Failed:0
1613039526359,1878,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:268 Passed:268 Failed:0
1613039529494,3132,selenium_app_custom_action:view_page,Success,True
1613039529494,3133,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:269 Passed:269 Failed:0
1613039529695,199,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:270 Passed:270 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.64s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039529873,127,selenium_login:open_login_page,Success,True
1613039530821,865,selenium_login:login_and_view_dashboard,Success,True
1613039530821,1075,selenium_login,Success,True
.test_0_selenium_a_login,Total:271 Passed:271 Failed:0
1613039531275,398,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:272 Passed:272 Failed:0
1613039531975,698,selenium_create_page:open_create_page_editor,Success,True
1613039533285,679,selenium_create_page:save_created_page,Success,True
1613039533285,2009,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:273 Passed:273 Failed:0
1613039534901,1614,selenium_edit_page:open_create_page_editor,Success,True
1613039535642,718,selenium_edit_page:save_edited_page,Success,True
1613039535642,2355,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:274 Passed:274 Failed:0
1613039536684,709,selenium_create_comment:write_comment,Success,True
1613039537334,649,selenium_create_comment:save_comment,Success,True
1613039537334,1690,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:275 Passed:275 Failed:0
1613039537966,631,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:276 Passed:276 Failed:0
1613039539771,1803,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:277 Passed:277 Failed:0
1613039542783,3010,selenium_app_custom_action:view_page,Success,True
1613039542783,3010,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:278 Passed:278 Failed:0
1613039542990,205,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:279 Passed:279 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.25s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039543181,138,selenium_login:open_login_page,Success,True
1613039544290,1021,selenium_login:login_and_view_dashboard,Success,True
1613039544290,1248,selenium_login,Success,True
.test_0_selenium_a_login,Total:280 Passed:280 Failed:0
1613039544761,410,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:281 Passed:281 Failed:0
1613039545475,713,selenium_create_page:open_create_page_editor,Success,True
1613039546788,653,selenium_create_page:save_created_page,Success,True
1613039546788,2025,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:282 Passed:282 Failed:0
1613039548402,1612,selenium_edit_page:open_create_page_editor,Success,True
1613039549222,795,selenium_edit_page:save_edited_page,Success,True
1613039549222,2433,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:283 Passed:283 Failed:0
1613039550304,659,selenium_create_comment:write_comment,Success,True
1613039550940,635,selenium_create_comment:save_comment,Success,True
1613039550940,1716,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:284 Passed:284 Failed:0
1613039551579,638,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:285 Passed:285 Failed:0
1613039553430,1849,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:286 Passed:286 Failed:0
1613039556841,3409,selenium_app_custom_action:view_page,Success,True
1613039556841,3409,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:287 Passed:287 Failed:0
1613039557037,194,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:288 Passed:288 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.00s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039557216,126,selenium_login:open_login_page,Success,True
1613039558246,949,selenium_login:login_and_view_dashboard,Success,True
1613039558247,1157,selenium_login,Success,True
.test_0_selenium_a_login,Total:289 Passed:289 Failed:0
1613039558920,608,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:290 Passed:290 Failed:0
1613039559780,858,selenium_create_page:open_create_page_editor,Success,True
1613039561033,614,selenium_create_page:save_created_page,Success,True
1613039561033,2111,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:291 Passed:291 Failed:0
1613039562712,1677,selenium_edit_page:open_create_page_editor,Success,True
1613039564029,1295,selenium_edit_page:save_edited_page,Success,True
1613039564029,2995,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:292 Passed:292 Failed:0
1613039565275,754,selenium_create_comment:write_comment,Success,True
1613039565925,649,selenium_create_comment:save_comment,Success,True
1613039565925,1893,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:293 Passed:293 Failed:0
1613039566657,730,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:294 Passed:294 Failed:0
1613039568490,1832,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:295 Passed:295 Failed:0
1613039572056,3564,selenium_app_custom_action:view_page,Success,True
1613039572056,3565,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:296 Passed:296 Failed:0
1613039572255,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:297 Passed:297 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.18s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039572433,127,selenium_login:open_login_page,Success,True
1613039573354,839,selenium_login:login_and_view_dashboard,Success,True
1613039573354,1048,selenium_login,Success,True
.test_0_selenium_a_login,Total:298 Passed:298 Failed:0
1613039574389,1003,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:299 Passed:299 Failed:0
1613039575166,775,selenium_create_page:open_create_page_editor,Success,True
1613039576426,628,selenium_create_page:save_created_page,Success,True
1613039576426,2036,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:300 Passed:300 Failed:0
1613039579113,2685,selenium_edit_page:open_create_page_editor,Success,True
1613039580323,1188,selenium_edit_page:save_edited_page,Success,True
1613039580323,3895,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:301 Passed:301 Failed:0
1613039581877,683,selenium_create_comment:write_comment,Success,True
1613039582501,623,selenium_create_comment:save_comment,Success,True
1613039582501,2176,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:302 Passed:302 Failed:0
1613039583220,717,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:303 Passed:303 Failed:0
1613039585012,1790,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:304 Passed:304 Failed:0
1613039587760,2746,selenium_app_custom_action:view_page,Success,True
1613039587760,2746,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:305 Passed:305 Failed:0
1613039587965,203,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:306 Passed:306 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.67s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039588146,128,selenium_login:open_login_page,Success,True
1613039589288,1054,selenium_login:login_and_view_dashboard,Success,True
1613039589289,1271,selenium_login,Success,True
.test_0_selenium_a_login,Total:307 Passed:307 Failed:0
1613039589819,472,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:308 Passed:308 Failed:0
1613039590577,756,selenium_create_page:open_create_page_editor,Success,True
1613039591943,700,selenium_create_page:save_created_page,Success,True
1613039591943,2122,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:309 Passed:309 Failed:0
1613039593515,1569,selenium_edit_page:open_create_page_editor,Success,True
1613039594256,720,selenium_edit_page:save_edited_page,Success,True
1613039594256,2311,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:310 Passed:310 Failed:0
1613039595393,711,selenium_create_comment:write_comment,Success,True
1613039596038,644,selenium_create_comment:save_comment,Success,True
1613039596038,1780,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:311 Passed:311 Failed:0
1613039596788,748,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:312 Passed:312 Failed:0
1613039598514,1725,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:313 Passed:313 Failed:0
1613039601962,3446,selenium_app_custom_action:view_page,Success,True
1613039601962,3446,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:314 Passed:314 Failed:0
1613039602164,200,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:315 Passed:315 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.16s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039602351,125,selenium_login:open_login_page,Success,True
1613039603260,826,selenium_login:login_and_view_dashboard,Success,True
1613039603261,1034,selenium_login,Success,True
.test_0_selenium_a_login,Total:316 Passed:316 Failed:0
1613039603861,542,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:317 Passed:317 Failed:0
1613039604572,709,selenium_create_page:open_create_page_editor,Success,True
1613039605981,710,selenium_create_page:save_created_page,Success,True
1613039605981,2118,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:318 Passed:318 Failed:0
1613039607697,1715,selenium_edit_page:open_create_page_editor,Success,True
1613039608685,966,selenium_edit_page:save_edited_page,Success,True
1613039608685,2702,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:319 Passed:319 Failed:0
1613039609646,396,selenium_create_comment:write_comment,Success,True
1613039610281,634,selenium_create_comment:save_comment,Success,True
1613039610281,1594,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:320 Passed:320 Failed:0
1613039611021,738,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:321 Passed:321 Failed:0
1613039612739,1716,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:322 Passed:322 Failed:0
1613039615436,2696,selenium_app_custom_action:view_page,Success,True
1613039615436,2696,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:323 Passed:323 Failed:0
1613039615635,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:324 Passed:324 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.42s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039615817,129,selenium_login:open_login_page,Success,True
1613039616781,880,selenium_login:login_and_view_dashboard,Success,True
1613039616781,1094,selenium_login,Success,True
.test_0_selenium_a_login,Total:325 Passed:325 Failed:0
1613039617485,640,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:326 Passed:326 Failed:0
1613039618319,831,selenium_create_page:open_create_page_editor,Success,True
1613039619612,662,selenium_create_page:save_created_page,Success,True
1613039619612,2125,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:327 Passed:327 Failed:0
1613039621665,2051,selenium_edit_page:open_create_page_editor,Success,True
1613039622852,1166,selenium_edit_page:save_edited_page,Success,True
1613039622853,3238,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:328 Passed:328 Failed:0
1613039624258,838,selenium_create_comment:write_comment,Success,True
1613039624887,628,selenium_create_comment:save_comment,Success,True
1613039624887,2033,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:329 Passed:329 Failed:0
1613039625598,709,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:330 Passed:330 Failed:0
1613039627284,1684,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:331 Passed:331 Failed:0
1613039629821,2535,selenium_app_custom_action:view_page,Success,True
1613039629821,2536,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:332 Passed:332 Failed:0
1613039630029,206,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:333 Passed:333 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.35s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039630210,125,selenium_login:open_login_page,Success,True
1613039631764,1473,selenium_login:login_and_view_dashboard,Success,True
1613039631764,1679,selenium_login,Success,True
.test_0_selenium_a_login,Total:334 Passed:334 Failed:0
1613039632809,987,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:335 Passed:335 Failed:0
1613039633631,819,selenium_create_page:open_create_page_editor,Success,True
1613039634901,634,selenium_create_page:save_created_page,Success,True
1613039634901,2089,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:336 Passed:336 Failed:0
1613039636443,1541,selenium_edit_page:open_create_page_editor,Success,True
1613039637629,1164,selenium_edit_page:save_edited_page,Success,True
1613039637629,2726,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:337 Passed:337 Failed:0
1613039639362,772,selenium_create_comment:write_comment,Success,True
1613039639995,633,selenium_create_comment:save_comment,Success,True
1613039639996,2364,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:338 Passed:338 Failed:0
1613039640606,609,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:339 Passed:339 Failed:0
1613039642472,1863,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:340 Passed:340 Failed:0
1613039645869,3395,selenium_app_custom_action:view_page,Success,True
1613039645869,3395,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:341 Passed:341 Failed:0
1613039646070,199,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:342 Passed:342 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.99s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039646245,124,selenium_login:open_login_page,Success,True
1613039647217,891,selenium_login:login_and_view_dashboard,Success,True
1613039647218,1097,selenium_login,Success,True
.test_0_selenium_a_login,Total:343 Passed:343 Failed:0
1613039647750,471,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:344 Passed:344 Failed:0
1613039648536,784,selenium_create_page:open_create_page_editor,Success,True
1613039649830,658,selenium_create_page:save_created_page,Success,True
1613039649830,2077,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:345 Passed:345 Failed:0
1613039651456,1624,selenium_edit_page:open_create_page_editor,Success,True
1613039652260,782,selenium_edit_page:save_edited_page,Success,True
1613039652260,2428,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:346 Passed:346 Failed:0
1613039653426,720,selenium_create_comment:write_comment,Success,True
1613039654057,630,selenium_create_comment:save_comment,Success,True
1613039654057,1795,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:347 Passed:347 Failed:0
1613039654824,765,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:348 Passed:348 Failed:0
1613039656653,1827,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:349 Passed:349 Failed:0
1613039659957,3302,selenium_app_custom_action:view_page,Success,True
1613039659957,3303,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:350 Passed:350 Failed:0
1613039660163,204,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:351 Passed:351 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.05s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039660344,128,selenium_login:open_login_page,Success,True
1613039661237,810,selenium_login:login_and_view_dashboard,Success,True
1613039661237,1021,selenium_login,Success,True
.test_0_selenium_a_login,Total:352 Passed:352 Failed:0
1613039661667,401,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:353 Passed:353 Failed:0
1613039662461,791,selenium_create_page:open_create_page_editor,Success,True
1613039663788,697,selenium_create_page:save_created_page,Success,True
1613039663788,2119,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:354 Passed:354 Failed:0
1613039664877,1088,selenium_edit_page:open_create_page_editor,Success,True
1613039665614,715,selenium_edit_page:save_edited_page,Success,True
1613039665614,1825,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:355 Passed:355 Failed:0
1613039666672,684,selenium_create_comment:write_comment,Success,True
1613039667312,639,selenium_create_comment:save_comment,Success,True
1613039667312,1696,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:356 Passed:356 Failed:0
1613039668645,1332,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:357 Passed:357 Failed:0
1613039670380,1732,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:358 Passed:358 Failed:0
1613039672741,2359,selenium_app_custom_action:view_page,Success,True
1613039672741,2359,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:359 Passed:359 Failed:0
1613039672942,200,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:360 Passed:360 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.74s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039673155,124,selenium_login:open_login_page,Success,True
1613039674026,785,selenium_login:login_and_view_dashboard,Success,True
1613039674026,994,selenium_login,Success,True
.test_0_selenium_a_login,Total:361 Passed:361 Failed:0
1613039675122,1034,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:362 Passed:362 Failed:0
1613039675914,790,selenium_create_page:open_create_page_editor,Success,True
1613039677184,637,selenium_create_page:save_created_page,Success,True
1613039677184,2060,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:363 Passed:363 Failed:0
1613039678718,1532,selenium_edit_page:open_create_page_editor,Success,True
1613039680188,1447,selenium_edit_page:save_edited_page,Success,True
1613039680188,3003,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:364 Passed:364 Failed:0
1613039681983,698,selenium_create_comment:write_comment,Success,True
1613039682602,618,selenium_create_comment:save_comment,Success,True
1613039682602,2412,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:365 Passed:365 Failed:0
1613039696167,13563,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:366 Passed:366 Failed:0
1613039698033,1864,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:367 Passed:367 Failed:0
1613039701171,3136,selenium_app_custom_action:view_page,Success,True
1613039701171,3136,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:368 Passed:368 Failed:0
1613039701383,211,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:369 Passed:369 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 28.36s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613039701608,170,selenium_login:open_login_page,Success,True
1613039702757,1040,selenium_login:login_and_view_dashboard,Success,True
1613039702758,1319,selenium_login,Success,True
.test_0_selenium_a_login,Total:370 Passed:370 Failed:0
1613039703251,460,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:371 Passed:371 Failed:0
1613039703963,710,selenium_create_page:open_create_page_editor,Success,True
1613039705327,664,selenium_create_page:save_created_page,Success,True
1613039705327,2074,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:372 Passed:372 Failed:0
1613039706355,1026,selenium_edit_page:open_create_page_editor,Success,True
1613039707161,783,selenium_edit_page:save_edited_page,Success,True
1613039707161,1832,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:373 Passed:373 Failed:0
1613039708239,720,selenium_create_comment:write_comment,Success,True
1613039708859,619,selenium_create_comment:save_comment,Success,True
1613039708859,1696,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:374 Passed:374 Failed:0
1613039709353,492,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:375 Passed:375 Failed:0
1613039711326,1971,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:376 Passed:376 Failed:0
1613039714663,3334,selenium_app_custom_action:view_page,Success,True
1613039714663,3335,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:377 Passed:377 Failed:0
1613039714864,200,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:378 Passed:378 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.44s =========================
