============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py first driver inits
1613036365678,319,selenium_login:open_login_page,Success,True
1613036366583,825,selenium_login:login_and_view_dashboard,Success,True
1613036366583,1225,selenium_login,Success,True
.test_0_selenium_a_login,Total:1 Passed:1 Failed:0
1613036367224,604,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:2 Passed:2 Failed:0
1613036368033,807,selenium_create_page:open_create_page_editor,Success,True
1613036369303,576,selenium_create_page:save_created_page,Success,True
1613036369304,2078,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:3 Passed:3 Failed:0
1613036370883,1577,selenium_edit_page:open_create_page_editor,Success,True
1613036371591,687,selenium_edit_page:save_edited_page,Success,True
1613036371591,2285,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:4 Passed:4 Failed:0
1613036372748,687,selenium_create_comment:write_comment,Success,True
1613036373362,613,selenium_create_comment:save_comment,Success,True
1613036373362,1769,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:5 Passed:5 Failed:0
1613036374067,704,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:6 Passed:6 Failed:0
1613036375732,1663,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:7 Passed:7 Failed:0
1613036378516,2782,selenium_app_custom_action:view_page,Success,True
1613036378516,2782,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:8 Passed:8 Failed:0
1613036378714,196,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:9 Passed:9 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.49s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036378890,122,selenium_login:open_login_page,Success,True
1613036379745,775,selenium_login:login_and_view_dashboard,Success,True
1613036379746,978,selenium_login,Success,True
.test_0_selenium_a_login,Total:10 Passed:10 Failed:0
1613036380251,450,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:11 Passed:11 Failed:0
1613036380954,702,selenium_create_page:open_create_page_editor,Success,True
1613036382314,724,selenium_create_page:save_created_page,Success,True
1613036382314,2061,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:12 Passed:12 Failed:0
1613036383936,1620,selenium_edit_page:open_create_page_editor,Success,True
1613036384708,752,selenium_edit_page:save_edited_page,Success,True
1613036384708,2393,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:13 Passed:13 Failed:0
1613036385822,710,selenium_create_comment:write_comment,Success,True
1613036386449,626,selenium_create_comment:save_comment,Success,True
1613036386449,1739,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:14 Passed:14 Failed:0
1613036387153,702,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:15 Passed:15 Failed:0
1613036388840,1685,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:16 Passed:16 Failed:0
1613036391735,2893,selenium_app_custom_action:view_page,Success,True
1613036391735,2893,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:17 Passed:17 Failed:0
1613036391930,193,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:18 Passed:18 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.17s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036392104,122,selenium_login:open_login_page,Success,True
1613036393018,832,selenium_login:login_and_view_dashboard,Success,True
1613036393018,1036,selenium_login,Success,True
.test_0_selenium_a_login,Total:19 Passed:19 Failed:0
1613036393621,577,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:20 Passed:20 Failed:0
1613036394383,759,selenium_create_page:open_create_page_editor,Success,True
1613036395638,619,selenium_create_page:save_created_page,Success,True
1613036395638,2015,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:21 Passed:21 Failed:0
1613036396791,1150,selenium_edit_page:open_create_page_editor,Success,True
1613036397594,783,selenium_edit_page:save_edited_page,Success,True
1613036397594,1954,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:22 Passed:22 Failed:0
1613036398772,716,selenium_create_comment:write_comment,Success,True
1613036399388,616,selenium_create_comment:save_comment,Success,True
1613036399388,1792,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:23 Passed:23 Failed:0
1613036400739,1349,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:24 Passed:24 Failed:0
1613036402453,1712,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:25 Passed:25 Failed:0
1613036405176,2721,selenium_app_custom_action:view_page,Success,True
1613036405176,2722,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:26 Passed:26 Failed:0
1613036405372,193,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:27 Passed:27 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.40s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036405552,122,selenium_login:open_login_page,Success,True
1613036406428,793,selenium_login:login_and_view_dashboard,Success,True
1613036406428,997,selenium_login,Success,True
.test_0_selenium_a_login,Total:28 Passed:28 Failed:0
1613036407043,585,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:29 Passed:29 Failed:0
1613036407879,834,selenium_create_page:open_create_page_editor,Success,True
1613036409198,675,selenium_create_page:save_created_page,Success,True
1613036409198,2153,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:30 Passed:30 Failed:0
1613036410909,1709,selenium_edit_page:open_create_page_editor,Success,True
1613036411917,984,selenium_edit_page:save_edited_page,Success,True
1613036411917,2717,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:31 Passed:31 Failed:0
1613036413147,697,selenium_create_comment:write_comment,Success,True
1613036413772,624,selenium_create_comment:save_comment,Success,True
1613036413772,1853,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:32 Passed:32 Failed:0
1613036414463,689,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:33 Passed:33 Failed:0
1613036416148,1683,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:34 Passed:34 Failed:0
1613036418974,2824,selenium_app_custom_action:view_page,Success,True
1613036418974,2824,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:35 Passed:35 Failed:0
1613036419172,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:36 Passed:36 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.75s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036419346,122,selenium_login:open_login_page,Success,True
1613036420259,831,selenium_login:login_and_view_dashboard,Success,True
1613036420259,1035,selenium_login,Success,True
.test_0_selenium_a_login,Total:37 Passed:37 Failed:0
1613036420725,406,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:38 Passed:38 Failed:0
1613036421459,732,selenium_create_page:open_create_page_editor,Success,True
1613036422734,643,selenium_create_page:save_created_page,Success,True
1613036422734,2008,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:39 Passed:39 Failed:0
1613036425021,2285,selenium_edit_page:open_create_page_editor,Success,True
1613036425776,732,selenium_edit_page:save_edited_page,Success,True
1613036425776,3041,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:40 Passed:40 Failed:0
1613036426903,669,selenium_create_comment:write_comment,Success,True
1613036427533,629,selenium_create_comment:save_comment,Success,True
1613036427533,1755,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:41 Passed:41 Failed:0
1613036428132,597,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:42 Passed:42 Failed:0
1613036429817,1683,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:43 Passed:43 Failed:0
1613036432658,2839,selenium_app_custom_action:view_page,Success,True
1613036432658,2839,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:44 Passed:44 Failed:0
1613036432857,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:45 Passed:45 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.64s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036433038,129,selenium_login:open_login_page,Success,True
1613036433938,815,selenium_login:login_and_view_dashboard,Success,True
1613036433938,1029,selenium_login,Success,True
.test_0_selenium_a_login,Total:46 Passed:46 Failed:0
1613036434573,568,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:47 Passed:47 Failed:0
1613036435375,801,selenium_create_page:open_create_page_editor,Success,True
1613036436651,635,selenium_create_page:save_created_page,Success,True
1613036436652,2077,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:48 Passed:48 Failed:0
1613036438612,1959,selenium_edit_page:open_create_page_editor,Success,True
1613036439935,1302,selenium_edit_page:save_edited_page,Success,True
1613036439935,3282,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:49 Passed:49 Failed:0
1613036441231,763,selenium_create_comment:write_comment,Success,True
1613036441868,636,selenium_create_comment:save_comment,Success,True
1613036441868,1931,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:50 Passed:50 Failed:0
1613036442513,643,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:51 Passed:51 Failed:0
1613036444211,1696,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:52 Passed:52 Failed:0
1613036447133,2920,selenium_app_custom_action:view_page,Success,True
1613036447133,2921,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:53 Passed:53 Failed:0
1613036447346,211,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:54 Passed:54 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.45s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036447525,127,selenium_login:open_login_page,Success,True
1613036448440,826,selenium_login:login_and_view_dashboard,Success,True
1613036448440,1042,selenium_login,Success,True
.test_0_selenium_a_login,Total:55 Passed:55 Failed:0
1613036449385,916,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:56 Passed:56 Failed:0
1613036450109,723,selenium_create_page:open_create_page_editor,Success,True
1613036451428,649,selenium_create_page:save_created_page,Success,True
1613036451428,2042,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:57 Passed:57 Failed:0
1613036452445,1015,selenium_edit_page:open_create_page_editor,Success,True
1613036453658,1190,selenium_edit_page:save_edited_page,Success,True
1613036453658,2229,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:58 Passed:58 Failed:0
1613036455338,782,selenium_create_comment:write_comment,Success,True
1613036455957,618,selenium_create_comment:save_comment,Success,True
1613036455957,2296,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:59 Passed:59 Failed:0
1613036456611,653,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:60 Passed:60 Failed:0
1613036458409,1795,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:61 Passed:61 Failed:0
1613036461276,2866,selenium_app_custom_action:view_page,Success,True
1613036461276,2866,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:62 Passed:62 Failed:0
1613036461470,192,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:63 Passed:63 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.08s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036461647,125,selenium_login:open_login_page,Success,True
1613036462556,824,selenium_login:login_and_view_dashboard,Success,True
1613036462556,1034,selenium_login,Success,True
.test_0_selenium_a_login,Total:64 Passed:64 Failed:0
1613036463180,567,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:65 Passed:65 Failed:0
1613036464035,853,selenium_create_page:open_create_page_editor,Success,True
1613036465341,673,selenium_create_page:save_created_page,Success,True
1613036465341,2159,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:66 Passed:66 Failed:0
1613036467147,1804,selenium_edit_page:open_create_page_editor,Success,True
1613036468099,929,selenium_edit_page:save_edited_page,Success,True
1613036468099,2756,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:67 Passed:67 Failed:0
1613036469159,598,selenium_create_comment:write_comment,Success,True
1613036469794,634,selenium_create_comment:save_comment,Success,True
1613036469794,1694,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:68 Passed:68 Failed:0
1613036470446,650,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:69 Passed:69 Failed:0
1613036472160,1713,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:70 Passed:70 Failed:0
1613036475062,2900,selenium_app_custom_action:view_page,Success,True
1613036475062,2900,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:71 Passed:71 Failed:0
1613036475265,201,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:72 Passed:72 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.75s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036475448,130,selenium_login:open_login_page,Success,True
1613036476344,813,selenium_login:login_and_view_dashboard,Success,True
1613036476344,1026,selenium_login,Success,True
.test_0_selenium_a_login,Total:73 Passed:73 Failed:0
1613036477074,704,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:74 Passed:74 Failed:0
1613036477815,739,selenium_create_page:open_create_page_editor,Success,True
1613036479087,634,selenium_create_page:save_created_page,Success,True
1613036479087,2011,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:75 Passed:75 Failed:0
1613036481380,2291,selenium_edit_page:open_create_page_editor,Success,True
1613036482785,1384,selenium_edit_page:save_edited_page,Success,True
1613036482785,3696,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:76 Passed:76 Failed:0
1613036484002,717,selenium_create_comment:write_comment,Success,True
1613036484639,636,selenium_create_comment:save_comment,Success,True
1613036484639,1852,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:77 Passed:77 Failed:0
1613036485340,699,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:78 Passed:78 Failed:0
1613036487046,1705,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:79 Passed:79 Failed:0
1613036490133,3085,selenium_app_custom_action:view_page,Success,True
1613036490134,3085,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:80 Passed:80 Failed:0
1613036490333,198,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:81 Passed:81 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.02s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036490511,124,selenium_login:open_login_page,Success,True
1613036491365,769,selenium_login:login_and_view_dashboard,Success,True
1613036491365,979,selenium_login,Success,True
.test_0_selenium_a_login,Total:82 Passed:82 Failed:0
1613036491844,420,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:83 Passed:83 Failed:0
1613036492647,801,selenium_create_page:open_create_page_editor,Success,True
1613036493929,648,selenium_create_page:save_created_page,Success,True
1613036493929,2083,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:84 Passed:84 Failed:0
1613036495549,1618,selenium_edit_page:open_create_page_editor,Success,True
1613036496288,716,selenium_edit_page:save_edited_page,Success,True
1613036496288,2357,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:85 Passed:85 Failed:0
1613036497376,648,selenium_create_comment:write_comment,Success,True
1613036498000,623,selenium_create_comment:save_comment,Success,True
1613036498000,1710,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:86 Passed:86 Failed:0
1613036498677,675,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:87 Passed:87 Failed:0
1613036500364,1685,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:88 Passed:88 Failed:0
1613036503396,3031,selenium_app_custom_action:view_page,Success,True
1613036503396,3031,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:89 Passed:89 Failed:0
1613036503589,191,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:90 Passed:90 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.21s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036503768,120,selenium_login:open_login_page,Success,True
1613036504682,831,selenium_login:login_and_view_dashboard,Success,True
1613036504682,1034,selenium_login,Success,True
.test_0_selenium_a_login,Total:91 Passed:91 Failed:0
1613036505095,387,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:92 Passed:92 Failed:0
1613036505893,796,selenium_create_page:open_create_page_editor,Success,True
1613036507195,668,selenium_create_page:save_created_page,Success,True
1613036507195,2098,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:93 Passed:93 Failed:0
1613036508326,1128,selenium_edit_page:open_create_page_editor,Success,True
1613036509067,720,selenium_edit_page:save_edited_page,Success,True
1613036509068,1870,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:94 Passed:94 Failed:0
1613036510087,657,selenium_create_comment:write_comment,Success,True
1613036510704,616,selenium_create_comment:save_comment,Success,True
1613036510704,1634,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:95 Passed:95 Failed:0
1613036511201,496,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:96 Passed:96 Failed:0
1613036512876,1674,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:97 Passed:97 Failed:0
1613036515942,3064,selenium_app_custom_action:view_page,Success,True
1613036515942,3064,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:98 Passed:98 Failed:0
1613036516141,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:99 Passed:99 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.50s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036516322,127,selenium_login:open_login_page,Success,True
1613036517255,849,selenium_login:login_and_view_dashboard,Success,True
1613036517255,1060,selenium_login,Success,True
.test_0_selenium_a_login,Total:100 Passed:100 Failed:0
1613036517687,406,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:101 Passed:101 Failed:0
1613036518468,779,selenium_create_page:open_create_page_editor,Success,True
1613036519740,633,selenium_create_page:save_created_page,Success,True
1613036519740,2051,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:102 Passed:102 Failed:0
1613036520825,1083,selenium_edit_page:open_create_page_editor,Success,True
1613036521621,775,selenium_edit_page:save_edited_page,Success,True
1613036521621,1880,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:103 Passed:103 Failed:0
1613036522812,727,selenium_create_comment:write_comment,Success,True
1613036523436,623,selenium_create_comment:save_comment,Success,True
1613036523436,1813,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:104 Passed:104 Failed:0
1613036524118,679,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:105 Passed:105 Failed:0
1613036525954,1835,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:106 Passed:106 Failed:0
1613036528800,2845,selenium_app_custom_action:view_page,Success,True
1613036528801,2845,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:107 Passed:107 Failed:0
1613036529000,198,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:108 Passed:108 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.82s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036529195,121,selenium_login:open_login_page,Success,True
1613036530057,779,selenium_login:login_and_view_dashboard,Success,True
1613036530057,984,selenium_login,Success,True
.test_0_selenium_a_login,Total:109 Passed:109 Failed:0
1613036531023,935,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:110 Passed:110 Failed:0
1613036531739,713,selenium_create_page:open_create_page_editor,Success,True
1613036533020,644,selenium_create_page:save_created_page,Success,True
1613036533020,1995,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:111 Passed:111 Failed:0
1613036534074,1052,selenium_edit_page:open_create_page_editor,Success,True
1613036535253,1152,selenium_edit_page:save_edited_page,Success,True
1613036535253,2231,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:112 Passed:112 Failed:0
1613036536842,712,selenium_create_comment:write_comment,Success,True
1613036537473,631,selenium_create_comment:save_comment,Success,True
1613036537473,2219,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:113 Passed:113 Failed:0
1613036538877,1403,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:114 Passed:114 Failed:0
1613036540646,1767,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:115 Passed:115 Failed:0
1613036543684,3036,selenium_app_custom_action:view_page,Success,True
1613036543684,3036,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:116 Passed:116 Failed:0
1613036543882,196,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:117 Passed:117 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.82s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036544062,129,selenium_login:open_login_page,Success,True
1613036545022,877,selenium_login:login_and_view_dashboard,Success,True
1613036545022,1089,selenium_login,Success,True
.test_0_selenium_a_login,Total:118 Passed:118 Failed:0
1613036545489,438,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:119 Passed:119 Failed:0
1613036546260,769,selenium_create_page:open_create_page_editor,Success,True
1613036547567,666,selenium_create_page:save_created_page,Success,True
1613036547567,2077,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:120 Passed:120 Failed:0
1613036549177,1608,selenium_edit_page:open_create_page_editor,Success,True
1613036549996,798,selenium_edit_page:save_edited_page,Success,True
1613036549996,2427,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:121 Passed:121 Failed:0
1613036551162,761,selenium_create_comment:write_comment,Success,True
1613036551793,631,selenium_create_comment:save_comment,Success,True
1613036551794,1796,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:122 Passed:122 Failed:0
1613036552314,519,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:123 Passed:123 Failed:0
1613036554134,1818,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:124 Passed:124 Failed:0
1613036557339,3203,selenium_app_custom_action:view_page,Success,True
1613036557339,3204,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:125 Passed:125 Failed:0
1613036557534,194,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:126 Passed:126 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.61s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036557713,128,selenium_login:open_login_page,Success,True
1613036558597,802,selenium_login:login_and_view_dashboard,Success,True
1613036558597,1011,selenium_login,Success,True
.test_0_selenium_a_login,Total:127 Passed:127 Failed:0
1613036559102,479,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:128 Passed:128 Failed:0
1613036559905,801,selenium_create_page:open_create_page_editor,Success,True
1613036561146,606,selenium_create_page:save_created_page,Success,True
1613036561146,2043,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:129 Passed:129 Failed:0
1613036562172,1024,selenium_edit_page:open_create_page_editor,Success,True
1613036562874,672,selenium_edit_page:save_edited_page,Success,True
1613036562874,1726,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:130 Passed:130 Failed:0
1613036563989,641,selenium_create_comment:write_comment,Success,True
1613036564612,622,selenium_create_comment:save_comment,Success,True
1613036564612,1736,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:131 Passed:131 Failed:0
1613036565419,805,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:132 Passed:132 Failed:0
1613036567095,1674,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:133 Passed:133 Failed:0
1613036570257,3160,selenium_app_custom_action:view_page,Success,True
1613036570257,3160,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:134 Passed:134 Failed:0
1613036570450,192,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:135 Passed:135 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.87s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036570627,125,selenium_login:open_login_page,Success,True
1613036571508,796,selenium_login:login_and_view_dashboard,Success,True
1613036571508,1006,selenium_login,Success,True
.test_0_selenium_a_login,Total:136 Passed:136 Failed:0
1613036572556,1022,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:137 Passed:137 Failed:0
1613036573226,668,selenium_create_page:open_create_page_editor,Success,True
1613036574556,660,selenium_create_page:save_created_page,Success,True
1613036574556,1998,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:138 Passed:138 Failed:0
1613036577206,2649,selenium_edit_page:open_create_page_editor,Success,True
1613036578438,1211,selenium_edit_page:save_edited_page,Success,True
1613036578439,3881,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:139 Passed:139 Failed:0
1613036580018,715,selenium_create_comment:write_comment,Success,True
1613036580647,629,selenium_create_comment:save_comment,Success,True
1613036580647,2207,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:140 Passed:140 Failed:0
1613036581268,619,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:141 Passed:141 Failed:0
1613036582955,1685,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:142 Passed:142 Failed:0
1613036586155,3198,selenium_app_custom_action:view_page,Success,True
1613036586155,3198,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:143 Passed:143 Failed:0
1613036586356,199,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:144 Passed:144 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.87s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036586540,125,selenium_login:open_login_page,Success,True
1613036587747,1122,selenium_login:login_and_view_dashboard,Success,True
1613036587747,1332,selenium_login,Success,True
.test_0_selenium_a_login,Total:145 Passed:145 Failed:0
1613036588312,536,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:146 Passed:146 Failed:0
1613036589039,725,selenium_create_page:open_create_page_editor,Success,True
1613036590334,623,selenium_create_page:save_created_page,Success,True
1613036590334,2020,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:147 Passed:147 Failed:0
1613036592613,2277,selenium_edit_page:open_create_page_editor,Success,True
1613036593459,825,selenium_edit_page:save_edited_page,Success,True
1613036593459,3124,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:148 Passed:148 Failed:0
1613036594646,691,selenium_create_comment:write_comment,Success,True
1613036595273,626,selenium_create_comment:save_comment,Success,True
1613036595273,1812,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:149 Passed:149 Failed:0
1613036596616,1342,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:150 Passed:150 Failed:0
1613036598501,1883,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:151 Passed:151 Failed:0
1613036601709,3207,selenium_app_custom_action:view_page,Success,True
1613036601710,3207,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:152 Passed:152 Failed:0
1613036601919,207,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:153 Passed:153 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.51s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036602104,126,selenium_login:open_login_page,Success,True
1613036603003,812,selenium_login:login_and_view_dashboard,Success,True
1613036603003,1025,selenium_login,Success,True
.test_0_selenium_a_login,Total:154 Passed:154 Failed:0
1613036603432,401,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:155 Passed:155 Failed:0
1613036604207,773,selenium_create_page:open_create_page_editor,Success,True
1613036605506,654,selenium_create_page:save_created_page,Success,True
1613036605507,2072,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:156 Passed:156 Failed:0
1613036607057,1548,selenium_edit_page:open_create_page_editor,Success,True
1613036607925,846,selenium_edit_page:save_edited_page,Success,True
1613036607925,2417,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:157 Passed:157 Failed:0
1613036609000,741,selenium_create_comment:write_comment,Success,True
1613036609634,633,selenium_create_comment:save_comment,Success,True
1613036609634,1707,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:158 Passed:158 Failed:0
1613036610272,637,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:159 Passed:159 Failed:0
1613036611995,1720,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:160 Passed:160 Failed:0
1613036615296,3299,selenium_app_custom_action:view_page,Success,True
1613036615296,3300,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:161 Passed:161 Failed:0
1613036615505,207,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:162 Passed:162 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.54s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036615683,126,selenium_login:open_login_page,Success,True
1613036616583,820,selenium_login:login_and_view_dashboard,Success,True
1613036616584,1027,selenium_login,Success,True
.test_0_selenium_a_login,Total:163 Passed:163 Failed:0
1613036617091,481,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:164 Passed:164 Failed:0
1613036617942,849,selenium_create_page:open_create_page_editor,Success,True
1613036619265,653,selenium_create_page:save_created_page,Success,True
1613036619265,2172,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:165 Passed:165 Failed:0
1613036621161,1895,selenium_edit_page:open_create_page_editor,Success,True
1613036622293,1110,selenium_edit_page:save_edited_page,Success,True
1613036622293,3027,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:166 Passed:166 Failed:0
1613036623637,749,selenium_create_comment:write_comment,Success,True
1613036624266,628,selenium_create_comment:save_comment,Success,True
1613036624266,1971,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:167 Passed:167 Failed:0
1613036624862,595,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:168 Passed:168 Failed:0
1613036626740,1877,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:169 Passed:169 Failed:0
1613036629471,2729,selenium_app_custom_action:view_page,Success,True
1613036629471,2729,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:170 Passed:170 Failed:0
1613036629665,193,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:171 Passed:171 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.12s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036629843,126,selenium_login:open_login_page,Success,True
1613036630791,866,selenium_login:login_and_view_dashboard,Success,True
1613036630791,1074,selenium_login,Success,True
.test_0_selenium_a_login,Total:172 Passed:172 Failed:0
1613036631269,447,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:173 Passed:173 Failed:0
1613036632050,779,selenium_create_page:open_create_page_editor,Success,True
1613036633322,634,selenium_create_page:save_created_page,Success,True
1613036633322,2051,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:174 Passed:174 Failed:0
1613036634373,1049,selenium_edit_page:open_create_page_editor,Success,True
1613036635073,675,selenium_edit_page:save_edited_page,Success,True
1613036635073,1749,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:175 Passed:175 Failed:0
1613036636122,681,selenium_create_comment:write_comment,Success,True
1613036636800,676,selenium_create_comment:save_comment,Success,True
1613036636800,1725,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:176 Passed:176 Failed:0
1613036637540,739,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:177 Passed:177 Failed:0
1613036639235,1692,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:178 Passed:178 Failed:0
1613036642451,3215,selenium_app_custom_action:view_page,Success,True
1613036642451,3215,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:179 Passed:179 Failed:0
1613036642647,194,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:180 Passed:180 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.94s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036642823,124,selenium_login:open_login_page,Success,True
1613036643886,980,selenium_login:login_and_view_dashboard,Success,True
1613036643886,1187,selenium_login,Success,True
.test_0_selenium_a_login,Total:181 Passed:181 Failed:0
1613036644347,434,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:182 Passed:182 Failed:0
1613036645073,725,selenium_create_page:open_create_page_editor,Success,True
1613036646353,634,selenium_create_page:save_created_page,Success,True
1613036646353,2005,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:183 Passed:183 Failed:0
1613036647941,1587,selenium_edit_page:open_create_page_editor,Success,True
1613036648693,729,selenium_edit_page:save_edited_page,Success,True
1613036648693,2338,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:184 Passed:184 Failed:0
1613036649652,627,selenium_create_comment:write_comment,Success,True
1613036650277,624,selenium_create_comment:save_comment,Success,True
1613036650278,1583,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:185 Passed:185 Failed:0
1613036650919,640,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:186 Passed:186 Failed:0
1613036652602,1681,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:187 Passed:187 Failed:0
1613036655873,3269,selenium_app_custom_action:view_page,Success,True
1613036655873,3270,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:188 Passed:188 Failed:0
1613036656073,198,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:189 Passed:189 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.38s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036656251,127,selenium_login:open_login_page,Success,True
1613036657148,812,selenium_login:login_and_view_dashboard,Success,True
1613036657148,1024,selenium_login,Success,True
.test_0_selenium_a_login,Total:190 Passed:190 Failed:0
1613036657686,474,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:191 Passed:191 Failed:0
1613036658415,727,selenium_create_page:open_create_page_editor,Success,True
1613036659667,627,selenium_create_page:save_created_page,Success,True
1613036659667,1979,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:192 Passed:192 Failed:0
1613036661262,1593,selenium_edit_page:open_create_page_editor,Success,True
1613036661984,699,selenium_edit_page:save_edited_page,Success,True
1613036661984,2315,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:193 Passed:193 Failed:0
1613036663118,694,selenium_create_comment:write_comment,Success,True
1613036663749,630,selenium_create_comment:save_comment,Success,True
1613036663749,1763,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:194 Passed:194 Failed:0
1613036664484,733,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:195 Passed:195 Failed:0
1613036666227,1741,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:196 Passed:196 Failed:0
1613036669371,3142,selenium_app_custom_action:view_page,Success,True
1613036669371,3142,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:197 Passed:197 Failed:0
1613036669575,202,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:198 Passed:198 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.46s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036669760,126,selenium_login:open_login_page,Success,True
1613036670667,826,selenium_login:login_and_view_dashboard,Success,True
1613036670668,1034,selenium_login,Success,True
.test_0_selenium_a_login,Total:199 Passed:199 Failed:0
1613036671229,533,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:200 Passed:200 Failed:0
1613036671899,667,selenium_create_page:open_create_page_editor,Success,True
1613036673189,655,selenium_create_page:save_created_page,Success,True
1613036673189,1958,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:201 Passed:201 Failed:0
1613036674742,1551,selenium_edit_page:open_create_page_editor,Success,True
1613036675510,746,selenium_edit_page:save_edited_page,Success,True
1613036675510,2319,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:202 Passed:202 Failed:0
1613036676536,644,selenium_create_comment:write_comment,Success,True
1613036677180,643,selenium_create_comment:save_comment,Success,True
1613036677180,1669,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:203 Passed:203 Failed:0
1613036677869,687,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:204 Passed:204 Failed:0
1613036679654,1783,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:205 Passed:205 Failed:0
1613036682832,3176,selenium_app_custom_action:view_page,Success,True
1613036682832,3176,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:206 Passed:206 Failed:0
1613036683030,196,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:207 Passed:207 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.41s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036683207,125,selenium_login:open_login_page,Success,True
1613036684057,766,selenium_login:login_and_view_dashboard,Success,True
1613036684057,975,selenium_login,Success,True
.test_0_selenium_a_login,Total:208 Passed:208 Failed:0
1613036685169,1052,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:209 Passed:209 Failed:0
1613036685959,787,selenium_create_page:open_create_page_editor,Success,True
1613036687222,631,selenium_create_page:save_created_page,Success,True
1613036687222,2050,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:210 Passed:210 Failed:0
1613036688236,1013,selenium_edit_page:open_create_page_editor,Success,True
1613036689409,1151,selenium_edit_page:save_edited_page,Success,True
1613036689410,2186,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:211 Passed:211 Failed:0
1613036691054,740,selenium_create_comment:write_comment,Success,True
1613036691680,625,selenium_create_comment:save_comment,Success,True
1613036691680,2268,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:212 Passed:212 Failed:0
1613036692214,533,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:213 Passed:213 Failed:0
1613036693975,1759,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:214 Passed:214 Failed:0
1613036697260,3284,selenium_app_custom_action:view_page,Success,True
1613036697260,3284,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:215 Passed:215 Failed:0
1613036697463,201,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:216 Passed:216 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.39s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036697643,128,selenium_login:open_login_page,Success,True
1613036698546,819,selenium_login:login_and_view_dashboard,Success,True
1613036698546,1031,selenium_login,Success,True
.test_0_selenium_a_login,Total:217 Passed:217 Failed:0
1613036698962,384,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:218 Passed:218 Failed:0
1613036699726,762,selenium_create_page:open_create_page_editor,Success,True
1613036701092,726,selenium_create_page:save_created_page,Success,True
1613036701092,2128,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:219 Passed:219 Failed:0
1613036702649,1555,selenium_edit_page:open_create_page_editor,Success,True
1613036703376,705,selenium_edit_page:save_edited_page,Success,True
1613036703376,2283,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:220 Passed:220 Failed:0
1613036704538,767,selenium_create_comment:write_comment,Success,True
1613036705161,623,selenium_create_comment:save_comment,Success,True
1613036705161,1783,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:221 Passed:221 Failed:0
1613036705926,763,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:222 Passed:222 Failed:0
1613036707634,1705,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:223 Passed:223 Failed:0
1613036710361,2726,selenium_app_custom_action:view_page,Success,True
1613036710361,2726,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:224 Passed:224 Failed:0
1613036710562,199,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:225 Passed:225 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.06s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036710741,128,selenium_login:open_login_page,Success,True
1613036711608,785,selenium_login:login_and_view_dashboard,Success,True
1613036711609,996,selenium_login,Success,True
.test_0_selenium_a_login,Total:226 Passed:226 Failed:0
1613036712170,503,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:227 Passed:227 Failed:0
1613036712972,801,selenium_create_page:open_create_page_editor,Success,True
1613036714212,599,selenium_create_page:save_created_page,Success,True
1613036714212,2041,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:228 Passed:228 Failed:0
1613036716947,2733,selenium_edit_page:open_create_page_editor,Success,True
1613036717778,810,selenium_edit_page:save_edited_page,Success,True
1613036717778,3564,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:229 Passed:229 Failed:0
1613036718905,740,selenium_create_comment:write_comment,Success,True
1613036719531,625,selenium_create_comment:save_comment,Success,True
1613036719531,1752,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:230 Passed:230 Failed:0
1613036720202,669,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:231 Passed:231 Failed:0
1613036721885,1681,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:232 Passed:232 Failed:0
1613036724255,2368,selenium_app_custom_action:view_page,Success,True
1613036724255,2368,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:233 Passed:233 Failed:0
1613036724450,193,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:234 Passed:234 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.85s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036724669,124,selenium_login:open_login_page,Success,True
1613036725615,859,selenium_login:login_and_view_dashboard,Success,True
1613036725615,1071,selenium_login,Success,True
.test_0_selenium_a_login,Total:235 Passed:235 Failed:0
1613036726139,494,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:236 Passed:236 Failed:0
1613036726918,777,selenium_create_page:open_create_page_editor,Success,True
1613036728193,639,selenium_create_page:save_created_page,Success,True
1613036728194,2053,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:237 Passed:237 Failed:0
1613036729941,1746,selenium_edit_page:open_create_page_editor,Success,True
1613036731048,1084,selenium_edit_page:save_edited_page,Success,True
1613036731048,2853,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:238 Passed:238 Failed:0
1613036732293,732,selenium_create_comment:write_comment,Success,True
1613036732930,636,selenium_create_comment:save_comment,Success,True
1613036732930,1881,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:239 Passed:239 Failed:0
1613036733504,572,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:240 Passed:240 Failed:0
1613036735196,1689,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:241 Passed:241 Failed:0
1613036738462,3264,selenium_app_custom_action:view_page,Success,True
1613036738462,3264,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:242 Passed:242 Failed:0
1613036738651,188,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:243 Passed:243 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.12s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036738933,224,selenium_login:open_login_page,Success,True
1613036739821,808,selenium_login:login_and_view_dashboard,Success,True
1613036739821,1113,selenium_login,Success,True
.test_0_selenium_a_login,Total:244 Passed:244 Failed:0
1613036740245,410,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:245 Passed:245 Failed:0
1613036740963,716,selenium_create_page:open_create_page_editor,Success,True
1613036742231,635,selenium_create_page:save_created_page,Success,True
1613036742231,1984,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:246 Passed:246 Failed:0
1613036743861,1628,selenium_edit_page:open_create_page_editor,Success,True
1613036744648,766,selenium_edit_page:save_edited_page,Success,True
1613036744648,2415,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:247 Passed:247 Failed:0
1613036745774,685,selenium_create_comment:write_comment,Success,True
1613036746403,629,selenium_create_comment:save_comment,Success,True
1613036746404,1754,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:248 Passed:248 Failed:0
1613036747070,665,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:249 Passed:249 Failed:0
1613036748754,1682,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:250 Passed:250 Failed:0
1613036751997,3241,selenium_app_custom_action:view_page,Success,True
1613036751997,3241,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:251 Passed:251 Failed:0
1613036752208,209,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:252 Passed:252 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.51s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036752385,125,selenium_login:open_login_page,Success,True
1613036753309,841,selenium_login:login_and_view_dashboard,Success,True
1613036753309,1049,selenium_login,Success,True
.test_0_selenium_a_login,Total:253 Passed:253 Failed:0
1613036753725,387,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:254 Passed:254 Failed:0
1613036754496,769,selenium_create_page:open_create_page_editor,Success,True
1613036755758,625,selenium_create_page:save_created_page,Success,True
1613036755758,2031,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:255 Passed:255 Failed:0
1613036757325,1565,selenium_edit_page:open_create_page_editor,Success,True
1613036758157,810,selenium_edit_page:save_edited_page,Success,True
1613036758157,2397,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:256 Passed:256 Failed:0
1613036759195,694,selenium_create_comment:write_comment,Success,True
1613036759836,641,selenium_create_comment:save_comment,Success,True
1613036759837,1678,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:257 Passed:257 Failed:0
1613036761177,1339,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:258 Passed:258 Failed:0
1613036762919,1740,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:259 Passed:259 Failed:0
1613036766298,3377,selenium_app_custom_action:view_page,Success,True
1613036766298,3377,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:260 Passed:260 Failed:0
1613036766508,208,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:261 Passed:261 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.26s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036766682,122,selenium_login:open_login_page,Success,True
1613036767619,856,selenium_login:login_and_view_dashboard,Success,True
1613036767619,1059,selenium_login,Success,True
.test_0_selenium_a_login,Total:262 Passed:262 Failed:0
1613036768276,631,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:263 Passed:263 Failed:0
1613036768958,680,selenium_create_page:open_create_page_editor,Success,True
1613036770236,648,selenium_create_page:save_created_page,Success,True
1613036770236,1958,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:264 Passed:264 Failed:0
1613036772958,2720,selenium_edit_page:open_create_page_editor,Success,True
1613036773801,821,selenium_edit_page:save_edited_page,Success,True
1613036773801,3563,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:265 Passed:265 Failed:0
1613036775048,755,selenium_create_comment:write_comment,Success,True
1613036775670,622,selenium_create_comment:save_comment,Success,True
1613036775670,1867,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:266 Passed:266 Failed:0
1613036776411,738,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:267 Passed:267 Failed:0
1613036778131,1719,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:268 Passed:268 Failed:0
1613036780885,2752,selenium_app_custom_action:view_page,Success,True
1613036780885,2752,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:269 Passed:269 Failed:0
1613036781082,195,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:270 Passed:270 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.53s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036781258,125,selenium_login:open_login_page,Success,True
1613036782178,835,selenium_login:login_and_view_dashboard,Success,True
1613036782178,1044,selenium_login,Success,True
.test_0_selenium_a_login,Total:271 Passed:271 Failed:0
1613036782580,376,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:272 Passed:272 Failed:0
1613036783377,795,selenium_create_page:open_create_page_editor,Success,True
1613036784722,708,selenium_create_page:save_created_page,Success,True
1613036784722,2140,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:273 Passed:273 Failed:0
1613036787348,2624,selenium_edit_page:open_create_page_editor,Success,True
1613036788157,788,selenium_edit_page:save_edited_page,Success,True
1613036788157,3433,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:274 Passed:274 Failed:0
1613036789202,687,selenium_create_comment:write_comment,Success,True
1613036789836,633,selenium_create_comment:save_comment,Success,True
1613036789836,1677,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:275 Passed:275 Failed:0
1613036790623,786,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:276 Passed:276 Failed:0
1613036792323,1697,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:277 Passed:277 Failed:0
1613036795632,3307,selenium_app_custom_action:view_page,Success,True
1613036795632,3307,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:278 Passed:278 Failed:0
1613036795831,197,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:279 Passed:279 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.71s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036796006,123,selenium_login:open_login_page,Success,True
1613036796916,825,selenium_login:login_and_view_dashboard,Success,True
1613036796916,1033,selenium_login,Success,True
.test_0_selenium_a_login,Total:280 Passed:280 Failed:0
1613036797476,504,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:281 Passed:281 Failed:0
1613036798270,792,selenium_create_page:open_create_page_editor,Success,True
1613036799539,643,selenium_create_page:save_created_page,Success,True
1613036799539,2061,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:282 Passed:282 Failed:0
1613036801130,1589,selenium_edit_page:open_create_page_editor,Success,True
1613036801945,795,selenium_edit_page:save_edited_page,Success,True
1613036801945,2405,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:283 Passed:283 Failed:0
1613036803141,735,selenium_create_comment:write_comment,Success,True
1613036803763,621,selenium_create_comment:save_comment,Success,True
1613036803763,1816,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:284 Passed:284 Failed:0
1613036804470,706,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:285 Passed:285 Failed:0
1613036806196,1724,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:286 Passed:286 Failed:0
1613036808956,2758,selenium_app_custom_action:view_page,Success,True
1613036808956,2758,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:287 Passed:287 Failed:0
1613036809199,241,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:288 Passed:288 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.33s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036809380,130,selenium_login:open_login_page,Success,True
1613036810279,815,selenium_login:login_and_view_dashboard,Success,True
1613036810279,1029,selenium_login,Success,True
.test_0_selenium_a_login,Total:289 Passed:289 Failed:0
1613036811327,986,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:290 Passed:290 Failed:0
1613036812028,700,selenium_create_page:open_create_page_editor,Success,True
1613036813322,654,selenium_create_page:save_created_page,Success,True
1613036813322,1994,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:291 Passed:291 Failed:0
1613036814878,1554,selenium_edit_page:open_create_page_editor,Success,True
1613036816049,1150,selenium_edit_page:save_edited_page,Success,True
1613036816049,2725,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:292 Passed:292 Failed:0
1613036817628,706,selenium_create_comment:write_comment,Success,True
1613036818252,623,selenium_create_comment:save_comment,Success,True
1613036818252,2201,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:293 Passed:293 Failed:0
1613036818818,565,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:294 Passed:294 Failed:0
1613036820597,1777,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:295 Passed:295 Failed:0
1613036823912,3313,selenium_app_custom_action:view_page,Success,True
1613036823912,3314,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:296 Passed:296 Failed:0
1613036824124,210,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:297 Passed:297 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.88s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036824298,123,selenium_login:open_login_page,Success,True
1613036825184,801,selenium_login:login_and_view_dashboard,Success,True
1613036825184,1009,selenium_login,Success,True
.test_0_selenium_a_login,Total:298 Passed:298 Failed:0
1613036825774,559,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:299 Passed:299 Failed:0
1613036826626,849,selenium_create_page:open_create_page_editor,Success,True
1613036827898,634,selenium_create_page:save_created_page,Success,True
1613036827898,2121,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:300 Passed:300 Failed:0
1613036829649,1749,selenium_edit_page:open_create_page_editor,Success,True
1613036830816,1145,selenium_edit_page:save_edited_page,Success,True
1613036830816,2917,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:301 Passed:301 Failed:0
1613036832138,730,selenium_create_comment:write_comment,Success,True
1613036832770,631,selenium_create_comment:save_comment,Success,True
1613036832770,1952,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:302 Passed:302 Failed:0
1613036833418,646,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:303 Passed:303 Failed:0
1613036835174,1755,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:304 Passed:304 Failed:0
1613036838158,2982,selenium_app_custom_action:view_page,Success,True
1613036838158,2982,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:305 Passed:305 Failed:0
1613036838366,206,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:306 Passed:306 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.20s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036838541,122,selenium_login:open_login_page,Success,True
1613036839545,924,selenium_login:login_and_view_dashboard,Success,True
1613036839545,1127,selenium_login,Success,True
.test_0_selenium_a_login,Total:307 Passed:307 Failed:0
1613036840180,577,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:308 Passed:308 Failed:0
1613036841018,836,selenium_create_page:open_create_page_editor,Success,True
1613036842297,638,selenium_create_page:save_created_page,Success,True
1613036842297,2115,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:309 Passed:309 Failed:0
1613036844057,1757,selenium_edit_page:open_create_page_editor,Success,True
1613036845095,1017,selenium_edit_page:save_edited_page,Success,True
1613036845095,2795,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:310 Passed:310 Failed:0
1613036846398,730,selenium_create_comment:write_comment,Success,True
1613036847033,635,selenium_create_comment:save_comment,Success,True
1613036847033,1936,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:311 Passed:311 Failed:0
1613036847591,556,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:312 Passed:312 Failed:0
1613036849407,1813,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:313 Passed:313 Failed:0
1613036852527,3118,selenium_app_custom_action:view_page,Success,True
1613036852527,3119,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:314 Passed:314 Failed:0
1613036852727,198,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:315 Passed:315 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 14.32s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036852905,125,selenium_login:open_login_page,Success,True
1613036853767,780,selenium_login:login_and_view_dashboard,Success,True
1613036853767,987,selenium_login,Success,True
.test_0_selenium_a_login,Total:316 Passed:316 Failed:0
1613036854316,535,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:317 Passed:317 Failed:0
1613036854888,570,selenium_create_page:open_create_page_editor,Success,True
1613036856206,633,selenium_create_page:save_created_page,Success,True
1613036856206,1889,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:318 Passed:318 Failed:0
1613036858001,1793,selenium_edit_page:open_create_page_editor,Success,True
1613036858945,922,selenium_edit_page:save_edited_page,Success,True
1613036858945,2736,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:319 Passed:319 Failed:0
1613036860006,559,selenium_create_comment:write_comment,Success,True
1613036860649,643,selenium_create_comment:save_comment,Success,True
1613036860650,1703,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:320 Passed:320 Failed:0
1613036861216,564,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:321 Passed:321 Failed:0
1613036862914,1697,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:322 Passed:322 Failed:0
1613036866202,3286,selenium_app_custom_action:view_page,Success,True
1613036866202,3286,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:323 Passed:323 Failed:0
1613036866409,205,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:324 Passed:324 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.64s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036866596,128,selenium_login:open_login_page,Success,True
1613036867575,896,selenium_login:login_and_view_dashboard,Success,True
1613036867575,1107,selenium_login,Success,True
.test_0_selenium_a_login,Total:325 Passed:325 Failed:0
1613036868036,401,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:326 Passed:326 Failed:0
1613036868764,726,selenium_create_page:open_create_page_editor,Success,True
1613036870063,664,selenium_create_page:save_created_page,Success,True
1613036870063,2025,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:327 Passed:327 Failed:0
1613036871185,1120,selenium_edit_page:open_create_page_editor,Success,True
1613036871941,735,selenium_edit_page:save_edited_page,Success,True
1613036871941,1876,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:328 Passed:328 Failed:0
1613036873022,702,selenium_create_comment:write_comment,Success,True
1613036873648,626,selenium_create_comment:save_comment,Success,True
1613036873648,1705,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:329 Passed:329 Failed:0
1613036874247,597,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:330 Passed:330 Failed:0
1613036876039,1790,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:331 Passed:331 Failed:0
1613036878792,2751,selenium_app_custom_action:view_page,Success,True
1613036878792,2752,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:332 Passed:332 Failed:0
1613036878988,194,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:333 Passed:333 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.53s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036879167,127,selenium_login:open_login_page,Success,True
1613036880194,947,selenium_login:login_and_view_dashboard,Success,True
1613036880194,1155,selenium_login,Success,True
.test_0_selenium_a_login,Total:334 Passed:334 Failed:0
1613036880646,394,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:335 Passed:335 Failed:0
1613036881365,716,selenium_create_page:open_create_page_editor,Success,True
1613036882649,646,selenium_create_page:save_created_page,Success,True
1613036882649,2001,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:336 Passed:336 Failed:0
1613036884205,1554,selenium_edit_page:open_create_page_editor,Success,True
1613036884954,724,selenium_edit_page:save_edited_page,Success,True
1613036884954,2303,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:337 Passed:337 Failed:0
1613036886007,709,selenium_create_comment:write_comment,Success,True
1613036886636,628,selenium_create_comment:save_comment,Success,True
1613036886636,1680,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:338 Passed:338 Failed:0
1613036887186,548,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:339 Passed:339 Failed:0
1613036888854,1667,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:340 Passed:340 Failed:0
1613036892075,3219,selenium_app_custom_action:view_page,Success,True
1613036892075,3219,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:341 Passed:341 Failed:0
1613036892273,196,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:342 Passed:342 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.24s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036892450,125,selenium_login:open_login_page,Success,True
1613036893315,779,selenium_login:login_and_view_dashboard,Success,True
1613036893315,989,selenium_login,Success,True
.test_0_selenium_a_login,Total:343 Passed:343 Failed:0
1613036893875,493,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:344 Passed:344 Failed:0
1613036894592,715,selenium_create_page:open_create_page_editor,Success,True
1613036895852,630,selenium_create_page:save_created_page,Success,True
1613036895852,1975,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:345 Passed:345 Failed:0
1613036896889,1035,selenium_edit_page:open_create_page_editor,Success,True
1613036897629,715,selenium_edit_page:save_edited_page,Success,True
1613036897629,1776,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:346 Passed:346 Failed:0
1613036898678,687,selenium_create_comment:write_comment,Success,True
1613036899299,620,selenium_create_comment:save_comment,Success,True
1613036899299,1668,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:347 Passed:347 Failed:0
1613036900016,715,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:348 Passed:348 Failed:0
1613036901700,1683,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:349 Passed:349 Failed:0
1613036904637,2935,selenium_app_custom_action:view_page,Success,True
1613036904637,2935,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:350 Passed:350 Failed:0
1613036904832,193,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:351 Passed:351 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 12.52s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036905012,127,selenium_login:open_login_page,Success,True
1613036905973,879,selenium_login:login_and_view_dashboard,Success,True
1613036905974,1089,selenium_login,Success,True
.test_0_selenium_a_login,Total:352 Passed:352 Failed:0
1613036906368,370,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:353 Passed:353 Failed:0
1613036907086,716,selenium_create_page:open_create_page_editor,Success,True
1613036908390,642,selenium_create_page:save_created_page,Success,True
1613036908390,2020,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:354 Passed:354 Failed:0
1613036910538,2146,selenium_edit_page:open_create_page_editor,Success,True
1613036911327,768,selenium_edit_page:save_edited_page,Success,True
1613036911327,2935,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:355 Passed:355 Failed:0
1613036912375,711,selenium_create_comment:write_comment,Success,True
1613036912992,616,selenium_create_comment:save_comment,Success,True
1613036912992,1663,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:356 Passed:356 Failed:0
1613036913694,701,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:357 Passed:357 Failed:0
1613036915401,1705,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:358 Passed:358 Failed:0
1613036918554,3151,selenium_app_custom_action:view_page,Success,True
1613036918554,3151,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:359 Passed:359 Failed:0
1613036918747,191,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:360 Passed:360 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.87s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036918974,138,selenium_login:open_login_page,Success,True
1613036919975,918,selenium_login:login_and_view_dashboard,Success,True
1613036919975,1138,selenium_login,Success,True
.test_0_selenium_a_login,Total:361 Passed:361 Failed:0
1613036920482,450,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:362 Passed:362 Failed:0
1613036921326,842,selenium_create_page:open_create_page_editor,Success,True
1613036922636,671,selenium_create_page:save_created_page,Success,True
1613036922636,2152,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:363 Passed:363 Failed:0
1613036924803,2165,selenium_edit_page:open_create_page_editor,Success,True
1613036926233,1406,selenium_edit_page:save_edited_page,Success,True
1613036926233,3595,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:364 Passed:364 Failed:0
1613036927451,783,selenium_create_comment:write_comment,Success,True
1613036928084,632,selenium_create_comment:save_comment,Success,True
1613036928084,1849,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:365 Passed:365 Failed:0
1613036928701,616,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:366 Passed:366 Failed:0
1613036930573,1869,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:367 Passed:367 Failed:0
1613036933798,3224,selenium_app_custom_action:view_page,Success,True
1613036933798,3224,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:368 Passed:368 Failed:0
1613036933998,198,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:369 Passed:369 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 15.17s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036934176,126,selenium_login:open_login_page,Success,True
1613036935346,1085,selenium_login:login_and_view_dashboard,Success,True
1613036935346,1296,selenium_login,Success,True
.test_0_selenium_a_login,Total:370 Passed:370 Failed:0
1613036935877,496,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:371 Passed:371 Failed:0
1613036936703,823,selenium_create_page:open_create_page_editor,Success,True
1613036938020,662,selenium_create_page:save_created_page,Success,True
1613036938020,2141,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:372 Passed:372 Failed:0
1613036939081,1059,selenium_edit_page:open_create_page_editor,Success,True
1613036939870,768,selenium_edit_page:save_edited_page,Success,True
1613036939870,1848,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:373 Passed:373 Failed:0
1613036941104,769,selenium_create_comment:write_comment,Success,True
1613036941725,621,selenium_create_comment:save_comment,Success,True
1613036941725,1853,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:374 Passed:374 Failed:0
1613036942352,625,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:375 Passed:375 Failed:0
1613036944078,1725,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:376 Passed:376 Failed:0
1613036947307,3227,selenium_app_custom_action:view_page,Success,True
1613036947307,3227,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:377 Passed:377 Failed:0
1613036947509,200,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:378 Passed:378 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.47s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036947687,125,selenium_login:open_login_page,Success,True
1613036948656,883,selenium_login:login_and_view_dashboard,Success,True
1613036948656,1094,selenium_login,Success,True
.test_0_selenium_a_login,Total:379 Passed:379 Failed:0
1613036949155,467,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:380 Passed:380 Failed:0
1613036949788,631,selenium_create_page:open_create_page_editor,Success,True
1613036951080,650,selenium_create_page:save_created_page,Success,True
1613036951080,1923,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:381 Passed:381 Failed:0
1613036952712,1630,selenium_edit_page:open_create_page_editor,Success,True
1613036953492,756,selenium_edit_page:save_edited_page,Success,True
1613036953492,2411,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:382 Passed:382 Failed:0
1613036954570,653,selenium_create_comment:write_comment,Success,True
1613036955218,647,selenium_create_comment:save_comment,Success,True
1613036955218,1724,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:383 Passed:383 Failed:0
1613036955899,680,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:384 Passed:384 Failed:0
1613036957594,1692,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:385 Passed:385 Failed:0
1613036960802,3206,selenium_app_custom_action:view_page,Success,True
1613036960802,3206,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:386 Passed:386 Failed:0
1613036961000,196,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:387 Passed:387 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.45s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.6
collected 9 items

selenium_ui/confluence_ui.py get driver from global
1613036961180,124,selenium_login:open_login_page,Success,True
1613036962084,821,selenium_login:login_and_view_dashboard,Success,True
1613036962084,1029,selenium_login,Success,True
.test_0_selenium_a_login,Total:388 Passed:388 Failed:0
1613036962599,454,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:389 Passed:389 Failed:0
1613036963350,749,selenium_create_page:open_create_page_editor,Success,True
1613036964642,652,selenium_create_page:save_created_page,Success,True
1613036964642,2041,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:390 Passed:390 Failed:0
1613036966308,1664,selenium_edit_page:open_create_page_editor,Success,True
1613036967233,903,selenium_edit_page:save_edited_page,Success,True
1613036967233,2590,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:391 Passed:391 Failed:0
1613036968350,665,selenium_create_comment:write_comment,Success,True
1613036969041,690,selenium_create_comment:save_comment,Success,True
1613036969041,1807,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:392 Passed:392 Failed:0
1613036969716,673,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:393 Passed:393 Failed:0
1613036971432,1714,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:394 Passed:394 Failed:0
1613036974587,3153,selenium_app_custom_action:view_page,Success,True
1613036974587,3153,selenium_app_custom_action,Success,True
.test_1_selenium_custom_action,Total:395 Passed:395 Failed:0
1613036974793,204,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:396 Passed:396 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 9 passed, 1 warning in 13.75s =========================
